### ISSUE TITLE
Zoom affecting all charts on page

### ISSUE THREAD

**Issue by vigneshv59** [chartjs/chartjs-plugin-zoom#102]
I'm running chart.js version 2.5.0, with multiple charts on one page. However, when I zoom into one chart and scroll through the page, all the other charts reflect the zooming change made in the other chart. Is there an option to disable this behavior that I didn't find in the documentation, or is this a bug?

**Comment by benmccann** [comment]
https://github.com/chartjs/chartjs-plugin-zoom/pull/104 was just merged. I'm not sure if it improves the behavior for you at all
