### ISSUE TITLE
Unable to set fillStyle color for drag zoom

### ISSUE THREAD

**Issue by CalvinChhour** [chartjs/chartjs-plugin-zoom#106]
Currently the drag zoom highlight color is hard coded to `rgba(225,225,225,0.3)`. This color isn't easily visible and changing background colors isn't a viable option in my case. It would be nice to be able to set this color to any color.

**Comment by jledentu** [comment]
I suggest to add options in `zoom` configuration:

```js
{
  zoom: {
    drag: true,
    dragBorderColor: 'rgba(225,225,225,0.3)'
    dragBorderWidth: 5,
    dragBackgroundColor: 'rgb(225,225,225)'
  }
}
```

Or more succinct properties, but implying a breaking change:

```js
{
  zoom: {
    drag: {
      enabled: true,
      borderColor: 'rgba(225,225,225,0.3)'
      borderWidth: 5,
      backgroundColor: 'rgb(225,225,225)'
    }
  }
}
```
