### ISSUE TITLE
resetZoom()

### ISSUE THREAD

**Issue by junbinku** [chartjs/chartjs-plugin-zoom#111]
The function resetZoom() does not support chartjs2. Where when used it will go undefined.

**Comment by benmccann** [comment]
An example of resetting zoom: https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html#L21

**Comment by jledentu** [comment]
`resetZoom` works correctly and must be called on the chart instance. An example is mentioned in the README, so I suggest to close this issue. @junbinku please free to reopen this issue if you have any question.
