### ISSUE TITLE
zoom limit

### ISSUE THREAD

**Issue by byeonghun-lee** [chartjs/chartjs-plugin-zoom#112]
Hi. Is this zoom limit use zoom rangeMin and rangeMax? 

I mean just put a number that?

if my data [50, 100, 200, 240, 300, 350, 400, 340, 430, 500, 70] and label 0~10.

```
zoom: {
            enabled: true,
            mode: 'x',
            rangeMin: {
                x: 3,
                y: 200
            },
            rangeMax: {
                x: 10,
                y: 600
            }
        }
```

this is right? what's "Format of min(max) zoom range depends on scale type"?? plz some help....

**Comment by BarnabyShearer** [comment]
The rangeMin and rangeMax always take a single value which need to be the same data type as your scale. In your example they are both numbers so this is correct.
Where I initially tripped up is that; for pan the rangeMin and rangeMax should normally be the min and max values that appear in your dataset. However for zoom the rangeMax should normally be the diffrence between the rangeMin and rangeMax you used for the pan. The min of the zoom can be 0 if you want them to zoom all the way in, or some fraction of the rangeMax value.

**Comment by JanOonk** [comment]
When you use a date axis be sure to have rangeMin and rangeMax in **Unix timestamp in milliseconds**. For example if you want to limit panning to your first and last date on your (first horizontal date) x-axis:
```
chart.options.pan.rangeMin.x = chart.scales["x-axis-0"].min.valueOf();
chart.options.pan.rangeMax.y = chart.scales["x-axis-0"].max.valueOf();
```

Took me some hours to figure that out, that you had to use **Unix timestamp in milliseconds**. I first tried date strings, then tried moment time objects.

**Comment by gundupatil** [comment]
facing same problem converted date to Unix timestamp in milliseconds. still not working
