### ISSUE TITLE
How to reset Zoom

### ISSUE THREAD

**Issue by joojoo102030** [chartjs/chartjs-plugin-zoom#116]
Hi, 
I do not find the lastest solution for zooming out. 
I have a lot of data on the chart, and I do not want to redraw the chart, just zoom out

**Comment by benmccann** [comment]
See https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html#L21

**Comment by aptarmy** [comment]
Well, this issue should be closed.
