### ISSUE TITLE
Getting  Array.prototype.some called on null or undefined

### ISSUE THREAD

**Issue by mac10046** [chartjs/chartjs-plugin-zoom#120]
although when you search for this error - you will find that this error occurs in moment v2.13 and the solution is to downgrade it to v2.12,

but I am already using moment v2.9 in my system - and this plugin uses moment 2.18 (chartjs-plugin-zoom@0.5.0)

So what Can i do to solve the issue - other than removing this plugin from my system ?

**Comment by jledentu** [comment]
`moment` is not a direct dependency of `chartjs-plugin-zoom`. This issue may be related to different versions of `moment` in your project, but has nothing to do with this plugin.

If you use Webpack for instance, you can prevent the usage of several moment instances by defining an alias:

```js
alias: {
  moment: require.resolve('moment')
}
```

I close this issue for now.
