### ISSUE TITLE
doing zoom to 2 charts on page

### ISSUE THREAD

**Issue by arif-hanif** [chartjs/chartjs-plugin-zoom#121]
We have an application where we need to have a hidden chart on the page to export consistent resolution images. Is there a way to have zoom apply to both the shown chart and the hidden chart?

**Comment by jledentu** [comment]
@arif-hanif You can use `onPan` and/or `onZoom` to listen to zoom events, and get `min`/`max` of the scales in order to apply them on scales of another charts. Please see https://github.com/chartjs/chartjs-plugin-zoom/issues/238 that addresses the same issue.
