### ISSUE TITLE
ZoomIn and zoomOut buttons

### ISSUE THREAD

**Issue by lovro1210** [chartjs/chartjs-plugin-zoom#123]
Is there programmatic access to zoom? so we can implement zoom buttons for quick zooming (+ and - buttons)

**Comment by vdesdoigts** [comment]
Hello, somebody has found a solution?

**Comment by kartik-ramachandran** [comment]
added this after the _wheelHandler function and works good on button click 

 chartInstance.ZoomIn = function () {
                        var rect = document.getElementById(chartInstance.canvas.id).getBoundingClientRect();

                        var center = {
                            x: rect.width / 2,
                            y: rect.height / 2
                        };

                        doZoom(chartInstance,1.1,center);
                    };


                    chartInstance.ZoomOut = function () {
                        var rect = document.getElementById(chartInstance.canvas.id).getBoundingClientRect();

                        var center = {
                            x: rect.width / 2,
                            y: rect.height / 2
                        };

                        doZoom(chartInstance,0.909,center);
                    };

**Comment by albmac** [comment]
What is doZoom(  ) ? It is not implemented.
There seems to be no direct zoom-in function.
I use instead the workaround of generating a mouse scroll event:
`	var evt = document.createEvent('MouseEvents');
	evt.initEvent('wheel', true, true);
	evt.deltaY = 100;
	document.getElementById("canvasInstance").dispatchEvent(evt);
`
`fgdfgd
fgdfg
dfg
`

**Comment by benmccann** [comment]
You can set the scale min and max and then call update if you'd like to manually zoom

**Comment by albmac** [comment]
That unfortunately will prevent panning over the whole range.
Waiting for direct zoom-in function I am happy with my workaround.

**Comment by anubhavng** [comment]
@albmac can you please help in implementing your workaround in react?

**Comment by albmac** [comment]
What do you mean? This is a task for the developers of chartjs

**Comment by nandhakumar23** [comment]
@albmac  Thanks for posting your workaround, helped me solve my problem.

**Comment by jledentu** [comment]
I close this issue since it's a duplicate of #43
