### ISSUE TITLE
Zooming to a specific value

### ISSUE THREAD

**Issue by ghost** [chartjs/chartjs-plugin-zoom#126]
Is it true that there currently is no way to force to zoom to a specific location, or is there just no documentation for this?

* It would make integration with a range slider possible

**Comment by olivercortinas** [comment]
I have the same thing, how we can make a zoom to a specific range on chart?

**Comment by benmccann** [comment]
Set `ticks.min` and `ticks.max` then call `update`

**Comment by olivercortinas** [comment]
Thanks, but i only see that properties on yAxes, i need to do it on xAxes, any idea?

**Comment by benmccann** [comment]
It doesn't depend on x or y, but on whether you're using linear, logarithmic, category, or time scale. Which scale type is your x axis?

**Comment by olivercortinas** [comment]
Time scale, but i could solve it with this: https://github.com/chartjs/chartjs-plugin-zoom/issues/43

**Comment by olivercortinas** [comment]
One question, how i can make a pan to a specific date range of the xAxis? i am trying to understand the doPan(chartInstance, deltaX, deltaY) but how i can now which value i have to set to deltaX and deltaY for that?
Any idea?

**Comment by benmccann** [comment]
To zoom or pan to specific place on a time axis do:

```
chart.options.scales.xAxes[0].time.min = yourMinValue;
chart.options.scales.xAxes[0].time.max = yourMaxValue;
chart.update();
```

**Comment by olivercortinas** [comment]
That works perfect, thanks a lot for the response!!!!

**Comment by benmccann** [comment]
I'm going to leave this open because it gets asked enough that we should add it to the documentation

**Comment by joseRelvasF3m** [comment]
Amazing, it works! Thank you so much!
