### ISSUE TITLE
options.time.format is deprecated and replaced by options.time.parser.

### ISSUE THREAD

**Issue by RakouskyS** [chartjs/chartjs-plugin-zoom#129]
Hello,

I am getting this warning in chrome everytime I move my mouse on a line chart in which the X-Axis is time based (moment.js).

[warning in chrome](https://imgur.com/UUhwPjh)

```
pan: {
    enabled: true,
   // Panning directions. Remove the appropriate direction to disable
   // Eg. 'y' would only allow panning in the y direction
   mode: 'xy',
   },
// Container for zoom options
zoom: {
    // Boolean to enable zooming
    enabled: true,

     // Enable drag-to-zoom behavior
     drag: true,

     // Zooming directions. Remove the appropriate direction to disable
     // Eg. 'y' would only allow zooming in the y direction
    mode: 'xy',
}
```

Chart.bundle.min.js 2.7.1
chartjs-plugin-zoom.js 0.6.3

**Comment by tobybloem** [comment]
I had this problem too and fixed it by replacing
`xAxes: [{
                                gridLines: {
                                    display: true
                                },
                                type: "time",
                                time: {
                                    format: "DD/MM/YYYY"
                                }
                            }]`
with
`xAxes: [{
                                gridLines: {
                                    display: true
                                },
                                type: "time",
                                time: {
                                    parser: "DD/MM/YYYY"
                                }
                            }]`

**Comment by RakouskyS** [comment]
@tobybloem thanks a ton, this fixed the issue :)
