### ISSUE TITLE
Zoom event

### ISSUE THREAD

**Issue by Lelenaic** [chartjs/chartjs-plugin-zoom#130]
I would like to update gauges when the zoom changes.
It would be great to be able to catch an event, something like:

```
myChart.onZoom(function (x, y, data){
    //doSomething
});
```
Thanks

**Comment by buddyp450** [comment]
I've submitted a PR request, it was pretty easy to implement. Note that the callbacks are invoked after the chart instance's update call.

**Comment by Lelenaic** [comment]
Thanks, it works perfectly!

**Comment by benmccann** [comment]
Closing as fixed
