### ISSUE TITLE
Pan doesn't work without `zoom.enabled`

### ISSUE THREAD

**Issue by danilvalov** [chartjs/chartjs-plugin-zoom#132]
I need a panning only (without zooming).
But if I disable zoom (`zoom: {enabled: false}`), pan doesn't work.

If I remove the following lines:
https://github.com/chartjs/chartjs-plugin-zoom/blob/d5caf6919b3472f60d66dca1f036178d957e8b8e/src/chart.zoom.js#L347-L349
and add checking `if (options.zoom && options.zoom.drag) {` instead the following line:
https://github.com/chartjs/chartjs-plugin-zoom/blob/d5caf6919b3472f60d66dca1f036178d957e8b8e/src/chart.zoom.js#L350
then pan works without zoom.

Why did you disable pan without zoom? Which problems did you have?

**Comment by Mrostgaard** [comment]
This should get a bug tag. I had so much problem with this!

**Comment by cabal95** [comment]
As a temporary work around, I set my options like this and it seems to work:
```
zoom: {
    enabled: true,
    mode: ''
}
```

**Comment by glukki** [comment]
@cabal95 this works, thank you! but still prevents page scroll, when mouse is over chart :(
@axelchalon are you going to make a PR?

**Comment by axelchalon** [comment]
don't think so, had the same issue and I don't know what the rationale was behind that line of code

**Comment by linzhoulxyz** [comment]
> As a temporary work around, I set my options like this and it seems to work:
> 
> ```
> zoom: {
>     enabled: true,
>     mode: ''
> }
> ```

```
zoom: {
  enabled: true,
  drag: true,  
 }
```

look into source code, this will work fine, and page can scroll too
