### ISSUE TITLE
Issue with RequireJS

### ISSUE THREAD

**Issue by tjugg** [chartjs/chartjs-plugin-zoom#137]
Hi, 

I would like to use this plugin via requirejs, but im having some troubles getting it to work. I got datalabels plugin to work using mapping, example below
```
require.config({
  paths: {
    chart: "//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min",
    datalabels: "//cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.3.0/dist/chartjs-plugin-datalabels.min",
    zoom: "//cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/0.5.0/chartjs-plugin-zoom.min"
  },
  map: {
    datalabels: {
      "chart.js": "chart"
    },
    zoom: {
      "chart.js": "chart"
    }
  }
});
```
After trying to use the plugin, i always get the error `TypeError: Cannot read property 'helpers' of undefined`. Any idea what is wrong?

I guess the error is coming from here on row 11.
https://github.com/chartjs/chartjs-plugin-zoom/blob/master/src/chart.zoom.js

**Comment by benmccann** [comment]
Please see https://www.chartjs.org/docs/latest/getting-started/integration.html#require-js
