### ISSUE TITLE
Zoom chart on click event

### ISSUE THREAD

**Issue by manhar-developer** [chartjs/chartjs-plugin-zoom#141]
Trying to achieve [zoomooz](http://jaukia.github.io/zoomooz/) plugin like functionality . Since npm does not support zoomooz. Is it possible to have same functionality i.e. animated zoom on click. I  want to zoom the div/canvas section on click and back to normal

Refer demo url here https://stackblitz.com/edit/ng2-chart-example

**Comment by etimberg** [comment]
I don't think this is the correct library for that functionality
