### ISSUE TITLE
Zoom option for Pie Chart

### ISSUE THREAD

**Issue by jayanthrajpramuk** [chartjs/chartjs-plugin-zoom#142]
I would like to know if zoom option is available for pie chart as well.

![image](https://user-images.githubusercontent.com/11515976/39965262-37b11c16-56b3-11e8-841b-4a499cf2715f.png)

For dataset apart from green , we will not be able to see as it will be very small.

**Comment by jledentu** [comment]
No, it's not available in pie/doughnut charts. Do you have any example of library/app that would allow zooming in pie charts? I can't figure out it could be implemented...

**Comment by benmccann** [comment]
I think basically you want to disable the Green section and see what's remaining? This plugin is really meant for cartesian axes, so I don't think we'd implement it here anyway
