### ISSUE TITLE
Fix category scale Zoom/Pan proportion problems

### ISSUE THREAD

**Issue by subogero** [chartjs/chartjs-plugin-zoom#151]
Plus panning on indexScale when zoomed in also causes zoom.

Zoom: the `zoom` parameter is a proportion. On linearScale it does work like that, but on the indexScale it's adding/removing 1 label at a time. Totally broken with large datasets. Make it work like linearScale.

Pan: calculate `dIndex` first, limit if `0 .. lastLabelIndex` range would be exceeded, *then* modify `minIndex`, `maxIndex` with the exact same `dIndex`.

Pan on indexScale currently unusable with large datasets. Make pan distance proportional to mouse/touch gesture size. 

Probably fixes some other related issues.

Pull request coming immediately.

**Comment by subogero** [comment]
Also see https://www.reddit.com/r/webdev/comments/8nqcq0/best_js_lib_for_charts/

**Comment by benmccann** [comment]
Also reported in https://github.com/chartjs/chartjs-plugin-zoom/issues/190

**Comment by benmccann** [comment]
Pending PR: https://github.com/chartjs/chartjs-plugin-zoom/pull/152

**Comment by kurkle** [comment]
I believe this was fixed in #476
