### ISSUE TITLE
Global variables set options not working.

### ISSUE THREAD

**Issue by Jerome1337** [chartjs/chartjs-plugin-zoom#157]
I used `Chart.Zoom.defaults` to set default zoom options.

```
Chart.Zoom.defaults.zoom.drag = true;
Chart.Zoom.defaults.zoom.enabled = true;
Chart.Zoom.defaults.zoom.mode = 'x';
```

This not seem to be working and not overriding default option.

When I use directly inside `Chart` instance options, the zoom is working well.

```
zoom: {
  drag: true,
  enabled: true,
  mode: 'x',
},
```

Also tried with `Chart.defaults.global` but this seem not accessible with `0.6.3` for the moment.

**Comment by jledentu** [comment]
It works with `Chart.defaults.global`:

```js

**Comment by Jerome1337** [comment]
Ok good news :+1:
