### ISSUE TITLE
[Question] Zoom without x-axis as type =time

### ISSUE THREAD

**Issue by kashwath** [chartjs/chartjs-plugin-zoom#158]
This question is because of [this](https://github.com/chartjs/Chart.js/issues/5649) chart.js issue.

Is there a way I can work with zoom when x-axis is timescale without having to mention type=time?

The zoom is not working if type=time is not mentioned in this case.

Fiddle:
[Current](https://jsfiddle.net/mhpLq1gx/9/)
[Problem](https://jsfiddle.net/mhpLq1gx/10/) - Need to work the same as above

**Comment by benmccann** [comment]
Please ask questions on StackOverflow: https://stackoverflow.com/questions/tagged/chart.js
