### ISSUE TITLE
zoom and pan do not work when using the "parse" option with moment.js

### ISSUE THREAD

**Issue by madacol** [chartjs/chartjs-plugin-zoom#165]
I was feeding data in unix time in seconds, and parsing it with moment.js using the parse option:
`parser: function(str) {return moment.unix(str);}`, time data was correctly displayed(labels and points), but for some reason zoom and pan didn't work.

I spent the whole day trying to figure out what was wrong, and my solution was to feed unix-time in microseconds (in integer), that way the library detect's the time without parsing, and now zoom and pan works.

Now it's cleaner I admit, but I think this could easily be a killer-issue for someone who really relys on parsing time and needs zoom/pan functionalities.

**Comment by benmccann** [comment]
What version of Chart.js were you using? I expect this will work in Chart.js 2.8.0

`rangeMin` and `rangeMax` probably do require timestamps though and we should document that

**Comment by etimberg** [comment]
Closing as out of date
