### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by veakey** [chartjs/chartjs-plugin-zoom#172]
On the source code we see the version enabling
 * onPan
 * onZoom
callbacks

But the version we have using 
```shell
npm install chartjs-plugin-zoom
```
gives us a version which does not have these callbacks in the source code.

### What's in the source code on your repo at doPan method
![image](https://user-images.githubusercontent.com/6059287/46794066-59eee280-cd47-11e8-844b-9f0ae9155d99.png)

### What's in the source code on a freshly _npm install_  at doPan method
![image](https://user-images.githubusercontent.com/6059287/46794158-8b67ae00-cd47-11e8-876d-c40187bbdd94.png)

### Package version
"chartjs-plugin-zoom": "^0.6.5"

Maybe you forgot to increment to version and update the npm package.

For now a quick fix would be to use directly the master branch using
```shell
npm install --save https://github.com/chartjs/chartjs-plugin-zoom#master
```

Thanks for your help :)

**Comment by mlangwell** [comment]
I have ran into this same issue, and our team needs this fixed ASAP please!

**Comment by mlangwell** [comment]
Status update please! Our team is in desperate need of this feature!

**Comment by Techn1x** [comment]
Hey all, ran into this today as well. IF you are desperate and you need to use this feature, feel free to use my fork here; https://github.com/Techn1x/chartjs-plugin-zoom/tree/self-gulped

Specifically you need to use the 'self-gulped' branch. I only recommend using that fork/branch short term, it is the same as this project's master branch as of today, but I ran gulp so the build and minified files are updated.

In your package.json
```
"chartjs-plugin-zoom": "git+https://github.com/Techn1x/chartjs-plugin-zoom.git#self-gulped",
```

@benmccann If you have some spare time, could you please cut a release? Looks like lots of people really need onPan and onZoom...

**Comment by benmccann** [comment]
I released 0.6.6

**Comment by mlangwell** [comment]
Thank you for getting this in! Is there any way that we can get the chartInstance from the onZoom/onPan functions. We need to know the tick range for the currently zoomed/panned chart.

**Comment by Techn1x** [comment]
@mlangwell that's handy, I didn't know that. FWIW I made a PR which adds chartInstance (and some other args) to the onZoom onPan functions https://github.com/chartjs/chartjs-plugin-zoom/pull/178/files
