### ISSUE TITLE
iPad Zoom finger position

### ISSUE THREAD

**Issue by BDominik** [chartjs/chartjs-plugin-zoom#173]
On iPad zooming when your two zoming fingers are closing horizontal line, it's zooming only on X
when your fingers closing vertical line then it's zooming only on Y
And when your fingers closing a diagonal line than it's zooming on X and Y in the same time.
How can we avoid the first two scenario?
So aside from your finger position I want to zoom on X and Y in the same time.
Thanks for your help.

**Comment by etimberg** [comment]
This is working as designed. To only allow zoom in certain directions, the `mode` setting can be used. See https://www.chartjs.org/chartjs-plugin-zoom/guide/options.html#zoom-options
