### ISSUE TITLE
toggle options.zoom.drag true <=> false

### ISSUE THREAD

**Issue by pmbert** [chartjs/chartjs-plugin-zoom#176]
Would be nice if user could change between drag mode and zoom/pan mode.
Only changing options.zoom.drag value doesn't work.

**Comment by benmccann** [comment]
Looks like the listeners are setup in `beforeInit`. Could probably move the listener setup to happen in a different hook, but would have to be careful we don't duplicate them if the chart is updated. List of hooks here: https://www.chartjs.org/docs/latest/developers/plugins.html

**Comment by jledentu** [comment]
@benmccann I think we could setup all listeners in `beforeInit`, and check `options.zoom.drag` in the body of the listeners.

**Comment by benmccann** [comment]
That'd probably be easier to implement :-)

**Comment by benmccann** [comment]
It looks like there's a PR for this: https://github.com/chartjs/chartjs-plugin-zoom/pull/182
