### ISSUE TITLE
logarithmic x axis zoom bug

### ISSUE THREAD

**Issue by BDominik** [chartjs/chartjs-plugin-zoom#180]
If I using logarithmic x axis and linear y axis, 
the zooming not working correctly.
If the mouse pointer is neer to x axes 0 and than zooming, everything is correct.
But when I'm moving the mouse to the right, so at the bigger x position, and zooming then.
My rendered line is not correct.

**Comment by rtouron** [comment]
Hi, any timeline to have this issue solved? I stumbled upon this bug today and unfortunately for my use case the log scale is a requirement.
Let me know if I can be of any help.
Thanks

**Comment by kurkle** [comment]
No timeline. A simple test case (jsfiddle etc) with latest versions always helps. I'll be taking a look what is needed for Chart.js v3 in the coming days and might try to fix some bugs as well.

**Comment by rtouron** [comment]
I tried to reproduce the issue on this [codepen](https://codepen.io/ramirotouron/pen/NWdNmRB)
Note that when dragging to zoom, the section highlighted on the x axis, doesn't correspond with that after zoom is applied
e.g. select from 100 to 10000 and the zoom is applied from ~345 to ~200000
Hope that helps
