### ISSUE TITLE
Scrolling a page with charts leads to graph zooming

### ISSUE THREAD

**Issue by SimonKibsgaard** [chartjs/chartjs-plugin-zoom#181]
Could you add a setting to restrict zooming to e.g. Ctrl+scroll as is on many Google map embeds so I am able to scroll down a page with charts without accidentally zooming them?
Thnx for a great plugin

**Comment by SimonKibsgaard** [comment]
I tried a workaround enabling/disabling zoom to see if i could have the user scrolling past the charts this way, but it actually still captures scroll - this time it just totally cancels it, so still no scrolling past a chart with this plugin: https://codepen.io/SimonKibsgaard/pen/KrBPLK?editors=1010

**Comment by Karlito88** [comment]
jQuery with Keypress can be a workaround by toggling the propertie of zoomEneable

**Comment by kurthamilton** [comment]
> 
> 
> jQuery with Keypress can be a workaround by toggling the propertie of zoomEneable

Scrolling is still hijacked by the plugin even when zoom is disabled or even left out of the plugin config. Apparently just including the plugin takes control of the scroll behaviour.

**Comment by benmccann** [comment]
This should be fixed if you use 0.7.1 which was released yesterday

**Comment by kurthamilton** [comment]
> 
> 
> This should be fixed if you use 0.7.1 which was released yesterday

My comment was based on using the latest version. I have since realised that I can disable the plugin at config level, e.g.

```
{
  plugins: {
    zoom: false
  }
}
```
instead of 
```
{
  plugins: {
    zoom: {
      pan: {
        enabled: false
      },
      zoom: {
        enabled: false
      }
    }
  }
}
```
But this just causes new issues when turning the plugin on after an initial disabled state.

My current workaround is just to recreate the chart every time I want to toggle the enabled state of the zoom plugin.

**Comment by benmccann** [comment]
@kurthamilton I've sent a fix for the issue you described. Would you be able to test it out? https://github.com/chartjs/chartjs-plugin-zoom/pull/254

**Comment by kurthamilton** [comment]
Thanks, much appreciated. I'll test it tomorrow morning (UK time).

**Comment by kurthamilton** [comment]
@benmccann that's fixed the issue. Thanks for your speedy work!

![0 7 2](https://user-images.githubusercontent.com/4037252/61041934-1e16a580-a3cb-11e9-9f06-c80bada1fd5c.gif)
![listener-setup](https://user-images.githubusercontent.com/4037252/61041945-2242c300-a3cb-11e9-8931-e83c7abe6c64.gif)
