### ISSUE TITLE
X-axes ticks not working as expected when zooming

### ISSUE THREAD

**Issue by angelrc96** [chartjs/chartjs-plugin-zoom#185]
I have a problem with x-axes when I do zoom over my chart. Here is [my jsfiddle](https://jsfiddle.net/angelrc96/crjdf2kg/). 

I need to show the chart at the beginning like this (step size of 2 hours):
![withstepsize_beforezoom](https://user-images.githubusercontent.com/15228919/49401879-ae5f7e80-f748-11e8-9570-60626e319633.PNG)

My problem shows up when I do zoom and x-axes labels stop to appear with the propper frecuency:
![withstepsize_afterzoom](https://user-images.githubusercontent.com/15228919/49401967-de0e8680-f748-11e8-911f-ca8f9b0037e4.PNG)

This is how I would like to see the charts when I do zoom (in minute level): 
![withoutstepsize_afterzoom](https://user-images.githubusercontent.com/15228919/49402127-4eb5a300-f749-11e8-9848-96227f4760d7.PNG)

I just can get this result by deleting 'stepSize: 120' property in my chart options.
However, when I do this, this is how my chart is firstly displayed, which is pretty ugly and not user friendly:

![withoutstepsize_beforezoom](https://user-images.githubusercontent.com/15228919/49402219-963c2f00-f749-11e8-9e6e-bc312bef453a.PNG)

So how can I fix this issue? Isn´t it suposed that chartjs should do it automatically? As it says in the documentation? ["When building its ticks, it will automatically calculate the most comfortable unit base on the size of the scale."](https://www.chartjs.org/docs/latest/axes/cartesian/time.html#time-cartesian-axis)

Thanks in advance :)

**Comment by Techn1x** [comment]
I've also had a lot of trouble with zooming and time-based ticks. If you want it to recalculate the time unit to use, try commenting out `unit`. Now that the unit used changes with zoom, the 120 `stepSize` is probably not great so comment that out too

I would then add `autoSkip: true` and `autoSkipPadding: 50` to space out some of the ticks

Then a `maxRotation: 0` should help stop the ticks from rotating when millisecond unit is used

If that's not quite what you're after, I would recommend experimenting with the `ticks` options and `time` axis options found here
https://www.chartjs.org/docs/latest/axes/cartesian/#tick-configuration
https://www.chartjs.org/docs/latest/axes/cartesian/time.html

**Comment by angelrc96** [comment]
Indeed, I tried your suggestion and it works like a charm! Thank you so much 💃  @Techn1x

**Comment by chetankumarjc** [comment]
can you share your approach, please. i am also facing the same issue
![image](https://user-images.githubusercontent.com/24387156/120115146-02c00980-c1a0-11eb-85c4-37c0c51b8475.png)

**Comment by nmol2** [comment]
As the above comments said, refer to the ChartJs Ticks Configuration.

if **in Hurry...**
    ```
chartOptions.scales.x.ticks = {
      // stepSize: 50,
      maxTicksLimit: 10,
      source: "auto",
      major: {
        enabled: true,
      },
      maxRotation: 0,
    };
    
```
 maxTixksLimit - _limits the ticks to be shown at once on that axis ( in my case x-axis), so even on zoom or zoom out, you will have the same no. of ticks_.
 maxRotation - _it handles the rotation of the ticks, ( 0 prevents diagonal ticks)_
