### ISSUE TITLE
Wrong bigger as statement

### ISSUE THREAD

**Issue by Karlito88** [chartjs/chartjs-plugin-zoom#186]
https://github.com/chartjs/chartjs-plugin-zoom/blob/5a49fba798798d7033b22721c564262e868d19e7/chartjs-plugin-zoom.js#L61
https://github.com/chartjs/chartjs-plugin-zoom/blob/5a49fba798798d7033b22721c564262e868d19e7/chartjs-plugin-zoom.js#L62

Got one Question in Line 61. Should this be rangeMax> newMax to set the "newMax" value? In this case it would take the lower range. Or I am wrong?

**Comment by benmccann** [comment]
I think some of the variable names are a bit confusing. It looks to me like it's saying that if the max zoom is greater than the limit then return the limit. I don't see any bug here though arguably the code could be written more clearly. I'm going to close this issue for now unless you still think there's a bug here
