### ISSUE TITLE
problem with  rangeMax and Min in zoom

### ISSUE THREAD

**Issue by DiruzCode** [chartjs/chartjs-plugin-zoom#187]
Hi, 
When i try to use the rangeMax and Min in the property zoom, this not work, i don't know for what, but if use the same in the pan property it works

```
                 pan: { 
                   enabled: true,
                       mode: 'x',`
                       rangeMax: {
                      			x: new Date(),
                      			y: null
                       },
                       rangeMin: {
                      			x: new Date('2017-12-10'),
                      			y: null
                       }
                   },
                   zoom: {
                       enabled: true,
                       mode: 'x'
                       rangeMax: {
                      	 		x: new Date(),
                      			y: 40000
                        },
                        rangeMin: {
                       			x: new Date('2017-12-10'),
                       			y: 0
                        }
                   }
```

<img width="1186" alt="captura de pantalla 2018-12-18 a la s 17 59 20" src="https://user-images.githubusercontent.com/12041331/50182653-abd75a00-02ee-11e9-951d-284be1d2de19.png">

<img width="1157" alt="captura de pantalla 2018-12-18 a la s 18 02 28" src="https://user-images.githubusercontent.com/12041331/50182827-1f796700-02ef-11e9-91bb-1b4e2f09c6ad.png">

Any can help me? 

Regarts

**Comment by benmccann** [comment]
Please format code blocks by placing three backticks before the whole block and three after

**Comment by redbmk** [comment]
For me it seems like `rangeMax` works properly (doesn't allow me to zoom out past that date), but adding a `rangeMin` makes it so zoom doesn't work at all anymore. I've tried both `Date` objects as well as unix timestamps.

**Comment by benmccann** [comment]
You need to pass unix timestamps. But even then it's broken. I sent a PR to fix here: https://github.com/chartjs/chartjs-plugin-zoom/pull/208
