### ISSUE TITLE
Zoom events

### ISSUE THREAD

**Issue by webprokopenko** [chartjs/chartjs-plugin-zoom#188]
I would like to update gauges when the zoom changes. But when I use onZoom. in params object like this: 
onZoom: function(x, y, data){
                    console.log('x: ',x);
                    console.log('y: ',y);
                    console.log('data: ',data);
                  }
I'm get undefined at all params in onZoom constructor.

**Comment by webprokopenko** [comment]
Done! Guages datas exists in chart object. Like: this.chart.scales['x-axis-0'].min - minimal value after zooming in x-coordinates. this.chart.scales['x-axis-0'].max - maximal value after zooming in x-coordinates. In array this.chart.scales['y-axis-0'] exists y - params scale.

**Comment by webprokopenko** [comment]
> this.conf2 = {
            type: "line",
            data: {
              labels: [
              ], 
              datasets: [
                {
                    label: '',
                    data: [],
                    borderColor: [
                        'rgb(255, 255, 255)',
                    ],
                    backgroundColor: [
                        'rgba(255,0,0,0)'
                    ],
                    borderWidth: 2,
                }
              ]
            },
            options: {
              responsive: true,
              title: {
                display: false,
              },
              elements: { point: { radius: 0 } } ,
              scales: {
                xAxes: [
                  {
                    type: "time",
                    time: {
                      parser: "DD/MM/YYYY HH:mm",
                      tooltipFormat: "DD/MM/YYYY HH:mm",
                      displayFormats: {
                        'second': 'mm:ss ',
                        'minute': 'HH:mm',
                        'hour': 'DD.MM (HH:mm)',
                        'day': 'DD/MM',
                        'week': 'DD/MM',
                        'month': 'DD/MM',
                        'quarter': 'DD/MM',
                        'year': 'DD/MM/YY',
                      },
                    },
                    ticks: {
                      maxRotation: 0
                    },
                  }
                ],
                yAxes: [
                  {
                    scaleLabel: {
                      display: true,
                      labelString: "value"
                    },
                    ticks: {
                        beginAtZero: true,
                    }
                  }
                ]
              },
              pan: {
                enabled: true,
                mode: "xy",
                speed: 10,
                threshold: 10
              },
              zoom: {
                enabled: true,
                drag: false,
                mode: "xy",
                limits: {
                  max: 10,
                  min: 0.5
                },
                onZoom: function(){
                    **self.onZoomChange();**
                }
              },
            },
        };


> onZoomChange(){
        console.log('min: ' ,this.chart.scales['x-axis-0'].min);
        console.log('max: ' ,this.chart.scales['x-axis-0'].max);
    },

**Comment by Attrash-Islam** [comment]
```
this.chart.scales['x-axis-0'].min - minimal value after zooming in x-coordinates. this.chart.scales['x-axis-0'].max - maximal value after zooming in x-coordinates
```

Those values should be reported to the onZoom callback separately 👍 . Another things is it possible to stop the plugin zoom and take (as the developer) the responsible to update the data? [Sometimes you want to change the scale of the steps when zooming multiple times or with tiny distance]

**Comment by Attrash-Islam** [comment]
> Done! Guages datas exists in chart object. Like: this.chart.scales['x-axis-0'].min - minimal value after zooming in x-coordinates. this.chart.scales['x-axis-0'].max - maximal value after zooming in x-coordinates. In array this.chart.scales['y-axis-0'] exists y - params scale.

Those values should be reported to the onZoom callback separately 👍 . Another things is it possible to stop the plugin zoom and take (as the developer) the responsible to update the data? [Sometimes you want to change the scale of the steps when zooming multiple times or with tiny distance]
