### ISSUE TITLE
samples/zoom-log.html is broken

### ISSUE THREAD

**Issue by benmccann** [chartjs/chartjs-plugin-zoom#189]
In samples/zoom-log.html put your mouse right next to a point and zoom in. I'd expect to zoom in on that point, but the chart moves away from my mouse both horizontally and vertically.

**Comment by benmccann** [comment]
Looks like this was also reported in https://github.com/chartjs/chartjs-plugin-zoom/issues/180

**Comment by jledentu** [comment]
@benmccann Yeah I confirm, it's the same issue.

**Comment by jledentu** [comment]
I close this issue since it's a duplicate of #180
