### ISSUE TITLE
Check config in a correct place too (options.plugins)

### ISSUE THREAD

**Issue by PaulAnnekov** [chartjs/chartjs-plugin-zoom#195]
Currently this plugin waits for config in `options.zoom` and `options.pan` while the correct place for them is `options.plugins.zoom` and `options.plugins.pan` respectively (https://www.chartjs.org/docs/latest/developers/plugins.html#plugin-options). This problem also makes a pain to use the plugin with TypeScript, because it doesn't expect `options` to contain `zoom` and `pan` properties and emits an error.

**Comment by jledentu** [comment]
You're right. I suggest to handle this in the future 1.0 version as it would break the API. @benmccann We may create a 1.0 milestone to reference issues with breaking changes?

**Comment by benmccann** [comment]
We could read from both locations now and remove the old one at 1.0. We could add a `TODO(1.0)` in the code to track in lieu of an issue

**Comment by simonbrunel** [comment]
> @PaulAnnekov This problem also makes a pain to use the plugin with TypeScript

FYI, DefinitelyTyped/DefinitelyTyped#31440 now allows to extend the TypeScript definition for the plugin options. That means plugins can *independently* provide definition files for their public API. For example, the datalabels plugin now exposes these types in the [`/types` folder](/chartjs/chartjs-plugin-datalabels/tree/master/types) ([`9e0026597`](/chartjs/chartjs-plugin-datalabels/commit/9e0026597a618f7ab1b07f04c75bc6395f96bbf6)).

**Comment by benmccann** [comment]
@PaulAnnekov a PR would be welcome for this

**Comment by benmccann** [comment]
This has been fixed
