### ISSUE TITLE
Adding scales leads to errors in the resetZoom function.

### ISSUE THREAD

**Issue by jannisgt** [chartjs/chartjs-plugin-zoom#197]
Hi,

when you add dynamically new scales to your chart and uses resetZoom it throws an error. Because there are no originalOptions for scales which were not existing at the point of initialization.

	

```
afterInit: function(chartInstance) {
	helpers.each(chartInstance.scales, function(scale) {
		scale.originalOptions = helpers.clone(scale.options);
	});

	chartInstance.resetZoom = function() {
		helpers.each(chartInstance.scales, function(scale, id) {
			var timeOptions = scale.options.time;
			var tickOptions = scale.options.ticks;

         		 if (timeOptions) {
            			timeOptions.min = scale.originalOptions.time.min;
           			timeOptions.max = scale.originalOptions.time.max;
          		}

          		if (tickOptions) {
            			tickOptions.min = scale.originalOptions.ticks.min;
            			tickOptions.max = scale.originalOptions.ticks.max;
          		}
		});

		helpers.each(chartInstance.data.datasets, function(dataset, id) {
			dataset._meta = null;
		});

		chartInstance.update();
	};

},
```

A remedy would be to add a query if the originalOptions are existing otherwise just delete those options. Like that I think everyone would win.

```
afterInit: function(chartInstance) {
		helpers.each(chartInstance.scales, function(scale) {
			scale.originalOptions = helpers.clone(scale.options);
		});

		chartInstance.resetZoom = function() {
			helpers.each(chartInstance.scales, function(scale, id) {
				var timeOptions = scale.options.time;
				var tickOptions = scale.options.ticks;

                                if (scale.originalOptions) {

					if (timeOptions) {
						timeOptions.min = scale.originalOptions.time.min;
						timeOptions.max = scale.originalOptions.time.max;
					}

					if (tickOptions) {
						tickOptions.min = scale.originalOptions.ticks.min;
						tickOptions.max = scale.originalOptions.ticks.max;
					}
				} else {
		
					if (timeOptions) {
						delete timeOptions.min;
						delete timeOptions.max;
					}

					if (tickOptions) {
						delete tickOptions.min;
						delete tickOptions.max;
					}
				});

				helpers.each(chartInstance.data.datasets, function(dataset, id) {
					dataset._meta = null;
				});

			chartInstance.update();
		};

},
```

**Comment by jledentu** [comment]
What if you add dynamically a new scale with `min`/`max` options? It seems that you delete these options in `resetZoom` instead of restoring them.

**Comment by jannisgt** [comment]
Never tried, but your right. 
Also when you change from 'linear' to 'logarithmic' the originalOptions are getting deleted so you cannot restore anything. I think you would need to add the min max dynamically after every resetZoom.

**Comment by benmccann** [comment]
Maybe we need to change `afterInit` to `afterUpdate` or something along those lines

**Comment by jannisgt** [comment]
Hmm, I don`t think that this will work. If you switch it to `afterUpdate` the originalOptions will be updated with every change of the view. Instead of restoring the initial values you restore the updated and the view never gets initialized.

**Comment by jannisgt** [comment]
So I had a closer look again in chartjs-plugin-zoom and chart.js.

The groundwork for zooming/panning should be done in the chart.js component with setting `scale.originalOptions` **or** adding `originalMin` and `originalMax` to the `TickOptions` of chartjs.

I would prefer the second approach `originalMin/Max`, so resetZoom can restore them to the min/max values. It is the easiest way I think.

Or my initial approach, but this is only a workaround and does not fit for every case, but the approach right now without checking for originalOptions is just buggy.

**Comment by benmccann** [comment]
Really we probably should not be editing the chart.js objects by adding new properties to them. Imagine if another plugin also tried to set an `originalOptions` variable. This plugin should probably maintain its own data structure to store that info

**Comment by jannisgt** [comment]
But adding a scale is something done in the `chart.js` and not in `chartjs-plugin-zoom`. 
So the work for a proper work with a new scale should be done in `chart.js`. 
But if we want to keep it to the `chartjs-plugin-zoom`, a solution might be to extend the functions `doZoom`, `doPan` and `resetZoom`, by:
```
helpers.each(chartInstance.scales, function(scale) {
	if (!scale.hasOwnProperty('originalOptions')) {
		scale.originalOptions = helpers.clone(scale.options)
	}
}
```
This ensures that if you add a new scale with specific min/max values that they get stored in the originalOptions. But it is necessary to set the min/max values before you pan/zoom/reset the chart..

**Comment by benmccann** [comment]
We shouldn't edit `chart.js` to support a plugin, but it's fine to edit `doZoom`, `doPan` and `resetZoom` to store the original options. I would not store it on the scale though, but rather in a separate data structure:

```
var originalOptions;
function storeOriginalOptions() {
	originalOptions = {};
	helpers.each(chartInstance.scales, function(scale) {
		originalOptions[scale.id] = helpers.clone(scale.options)
	}
}
```

**Comment by jannisgt** [comment]
Just fine, if it works (haven't tried =)) will you do the change?

**Comment by benmccann** [comment]
I'm afraid I don't have time

**Comment by jannisgt** [comment]
Ok, I will try and send in an PR.
