### ISSUE TITLE
Single click on legend is interpreted as drag

### ISSUE THREAD

**Issue by benmccann** [chartjs/chartjs-plugin-zoom#205]
Clicking on the legend activates the drag feature. If possible, only clicking within the chart area should activate this feature

Additionally, a single click anywhere on the chart is interpreted as a drag. It perhaps should not be unless the mouse moves.

See this in the zoom-time.html sample

**Comment by thetinshusasi** [comment]
Hi,

Did anybody able to resolve this issue

**Comment by thetinshusasi** [comment]
Hi,

Single Click inside the chart is intercepted as drag. Any body is able resolve this issue

**Comment by benmccann** [comment]
This is fixed for a single click on the legend. It's still not fixed for a drag on the legend. For that we would need to listen to clicks only on the chart area and not the whole canvas
