### ISSUE TITLE
Zoom with a mobile device not properly working

### ISSUE THREAD

**Issue by ricvec** [chartjs/chartjs-plugin-zoom#218]
Dear team,
I have just found this plugin and it is wonderful! Thank you very much for what you did.

I am writing because there is a problem zooming a chart with a mobile device (tried with iPhone): when zooming using the fingers, the chart goes on top left of the website. I have gone through and tried to search the reason.
It can be fixed changing the row 501 from

doZoom(chartInstance, diff, center, xy);
to
doZoom(chartInstance, diff, **diff,** center, xy);

Hopefully this can be helpful for someone else!

BR,
Riccardo

**Comment by skhan02** [comment]
Hi @ricvec I am trying to run this on an iPhone - i tried the sample in a webview. Pan and zoom don't seem to work. Can you share how you went about it?

**Comment by ricvec** [comment]
hi @skhan02 , have you imported the library hammer.js?

**Comment by skhan02** [comment]
Thanks @ricvec that was the issue.
