### ISSUE TITLE
Zoom doesn't work in angular

### ISSUE THREAD

**Issue by joseRelvasF3m** [chartjs/chartjs-plugin-zoom#222]
I don't know why, but I can't perform zoom or pan in the charts. I've already installed the hammer.js and pasted the respective code in the options of my chart, but it just doesn't work. What could be?

**Comment by jledentu** [comment]
Hi,

Do you have a JSBin or any shareable code that could help us to understand your issue? 😃

**Comment by joseRelvasF3m** [comment]
Hi @jledentu ,

This is the code I got:

` this.LineChart = new Chart('lineChart', {
      type: 'line',
      data: {
      x: new Date(),
     
      datasets: [{
          label: 'Profundidade',
	  fill:false,
          lineTension:0.2,
          borderColor:"green",
          backgroundColor:"green",
          borderWidth: 1,
          pointHitRadius: 10,
            data: [
              { t: "2019-3-12 16:31", y: 2 },
              { t: "2019-3-13 16:31", y: 4.7 },
              { t: "2019-3-14 16:31", y: 4.8 },
              { t: "2019-3-15 16:31", y: 3.9 },
              { t: "2019-3-16 16:31", y: 3.1 },
              { t: "2019-3-17 16:31", y: 1.2 },
              { t: "2019-3-18 16:31", y: 4.1 },
              { t: "2019-3-19 16:31", y: 4 },
              { t: "2019-3-20 16:31", y: 0.2 },
              { t: "2019-3-21 16:31", y: 0.2 },
              { t: "2019-3-22 16:31", y: 0.1 },
              { t: "2019-3-23 16:31", y: 0.2 },
              { t: "2019-3-24 16:31", y: 0.2 },
              { t: "2019-3-25 16:31", y: 0.1 }
            ] } ] },
    options: {
      legend: {
        position: 'bottom',
        labels: {
          fontSize: 10,
          boxWidth: 20
       }
      },
      tooltips: {
        mode: 'index',
        callbacks: {
          // Use the footer callback to display the sum of the items showing in the tooltip
          footer: function(tooltipItems) {
            var multi = 1;
            tooltipItems.forEach(function(tooltipItem) {
              
              multi *= tooltipItem.yLabel;
            });
            return 'Resultado: ' + multi;
          },
        },
        footerFontStyle: 'normal'
      },
      // Container for pan options
      pan: {
        // Boolean to enable panning
        enabled: true,
    
        // Panning directions. Remove the appropriate direction to disable
        // Eg. 'y' would only allow panning in the y direction
        mode: 'xy',
        rangeMin: {
          // Format of min pan range depends on scale type
          x: null,
          y: null
        },
        rangeMax: {
          // Format of max pan range depends on scale type
          x: null,
          y: null
        },
        // Function called once panning is completed
        // Useful for dynamic data loading
        onPan: function({chart}) { console.log(`I was panned!!!`); }
      },
    
      // Container for zoom options
      zoom: {
        // Boolean to enable zooming
        enabled: true,
    
        // Enable drag-to-zoom behavior
        drag: true,
    
        // Drag-to-zoom rectangle style can be customized
        // drag: {
        // 	 borderColor: 'rgba(225,225,225,0.3)'
        // 	 borderWidth: 5,
        // 	 backgroundColor: 'rgb(225,225,225)'
        // },
    
        // Zooming directions. Remove the appropriate direction to disable
        // Eg. 'y' would only allow zooming in the y direction
        mode: 'xy',
    
        rangeMin: {
          // Format of min zoom range depends on scale type
          x: null,
          y: null
        },
        rangeMax: {
          // Format of max zoom range depends on scale type
          x: null,
          y: null
        },
    
        // Speed of zoom via mouse wheel
        // (percentage of zoom on a wheel event)
        speed: 0.1,
    
        // Function called once zooming is completed
        // Useful for dynamic data loading
        onZoom: function({chart}) { console.log(`I was zoomed!!!`); }
      },
    
    events: ['click'],
     scales: {
      xAxes: [{
        type: 'time',
        time: {
            unit: 'day'
        }
    }],
      yAxes: [{
        ticks: {
          // Include a dollar sign in the ticks
          callback: function(value) {
              return value + ' cm';
          }
      },
      scaleLabel: {
        show: true,
        labelString: 'Value'
      }
      }]
     } 
    }
  });
  }`

It just doesn't pan or zoom...

**Comment by water1212** [comment]
I had the same issue. I found a work around for it by using this library. 
It was pretty straightforward and simple to use. All you need to do is include it after Hammer.js has been added, and add the correct tags to your elements, then you should be good to go.  

http://ryanmullins.github.io/angular-hammer/

**Comment by benmccann** [comment]
@joseRelvasF3m @water1212 can you try again with chartjs-plugin-zoom 0.7.0? It will have HammerJS bundled with it so that you no longer need to include it separately

**Comment by joseRelvasF3m** [comment]
The problem is now solved. I just failed to do the correct imports for the main.ts.

```
import 'hammerjs'
import 'chartjs-plugin-zoom'
```
Thank you all.
