### ISSUE TITLE
Multiple Y Axes, does not zoom on both Y axes.

### ISSUE THREAD

**Issue by DevidCIC** [chartjs/chartjs-plugin-zoom#223]
As seen in the gif below Zoom Plugin does not zoom on both y axes. I think this is a bug.

![Alt Text](https://i.imgur.com/SLh2kaQ.gif)

**Comment by jledentu** [comment]
I tested, I think it works BUT you have to define the `type` on your second Y scale:

```js
yAxes: [{
	scaleLabel: {
		display: true,
		labelString: 'value'
	}
}, {
	id: 'y2',
	type: 'linear', // <- Explicit type
	scaleLabel: {
		display: true,
		labelString: 'y2'
	}
}]
```

@DevidCC Can you test this ? Anyway, we may consider that a scale is `linear` by default. Or is this something that `chart.js` should handle? @benmccann What do you think?

**Comment by benmccann** [comment]
Hmm. Chart.js is supposed to fill in the missing type: https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js#L56

It seems like there's a bug here where that's getting dropped or we're calling the plugin before that's been done

**Comment by benmccann** [comment]
I sent https://github.com/chartjs/Chart.js/pull/6137 to fix this

**Comment by benmccann** [comment]
We can fix it in this repo too. Here's another fix for it: https://github.com/chartjs/chartjs-plugin-zoom/pull/221/commits/f500fedb0a0e04c6bf64dca6d1f952bcfff0f20f

**Comment by benmccann** [comment]
The fix for this has been committed and will be included in the next release, which hopefully will be out sometime in the next week
