### ISSUE TITLE
Pan programmatically

### ISSUE THREAD

**Issue by SimoneMSR** [chartjs/chartjs-plugin-zoom#224]
Hello everyone. This is not actully an issue, nor a feature request: it's just an support request. Of course it can become a new feature

Do you think there is a way to enable a programmatical pan? Like
`myChart.pan(1,'x')`
that moves the chart for 1 unit/point/pixel (the measure unit can be a further desiderable, not really necessary!) on the 'x' axis?

**Comment by benmccann** [comment]
Change the scale min and max then call `update`
