### ISSUE TITLE
Line leaves a trail when panned (iOS/WKWebview)

### ISSUE THREAD

**Issue by kyoryud3v** [chartjs/chartjs-plugin-zoom#226]
![1](https://user-images.githubusercontent.com/48641871/54487630-9799fd80-48db-11e9-9f03-c4cf82dcfb4b.png)
![2](https://user-images.githubusercontent.com/48641871/54487632-9799fd80-48db-11e9-9c89-ecb8be7d7bc4.png)

Mostly happens when panning the canvas immediately after the device changes orientation (chart canvas resizes), only occurs in **iOS/WKWebview.**

**Comment by jledentu** [comment]
I don't have iOS device so I can't confirm or debug this bug. Could anyone help us please? :)

**Comment by etimberg** [comment]
Closing due to age and lack of test case
