### ISSUE TITLE
Pan does not work with recent change to panScale function

### ISSUE THREAD

**Issue by cabal95** [chartjs/chartjs-plugin-zoom#234]
I recently upgraded to version 0.7.0 of the plugin to get the fix for #132. This however brought about a new problem. A change was made to the `panScale` function. It used to determine the scale type by using `scale.options.type`, but now it uses just `scale.type`.

The problem is that `scale.type` is undefined which causes the panning to not function. If I revert that one line of code and make it use `scale.options.type` (which is defined) then the pan feature starts working again.

This is using ChartJS 2.7.0 and chartjs-plugin-zoom 0.7.0.  Below is a simple sample that reproduces the problem (meaning, you can't pan):

```
<canvas id="testChart" width="640px" height="120px"></canvas>

<script>
(function () {
    var config = {
        type: 'line',
        data: {
            datasets: [{
                label: 'Test',
                data: [
                    { x: '2019-01-01 13:00', y: 10 },
                    { x: '2019-01-01 14:00', y: 12 },
                    { x: '2019-01-01 15:00', y: 11 },
                    { x: '2019-01-01 16:00', y: 15 }
                ]
            }]
        },
        options: {
            plugins: {
                zoom: {
                    pan: {
                        enabled: true,
                        mode: 'x'
                    },
                }
            },
            scales: {
                xAxes: [{
                    type: 'time'
                }]
            }
        }
    };
    
    var chart = new Chart($('#testChart').get(0).getContext('2d'), config);
})();
</script>
```

Note: I realize I am not using the latest ChartJS, I don't have control over that. This is on an existing system that I am just adding a new page/chart to. The documentation states that the plugin works with ChartJS >= 2.6.0 so this should be fine - unless that is no longer correct with plugin 0.7.0.

**Comment by kurkle** [comment]
Closing as Chart.js v2 is no longer in development. Fixed for Chart.js v3.
