### ISSUE TITLE
Is it possible to customise this plugin in angular 7 by writing function?

### ISSUE THREAD

**Issue by sridhark158** [chartjs/chartjs-plugin-zoom#240]
Is it possible to customise this plugin in angular 7 by writing function?

**Comment by chaitrashenoy33** [comment]
+1

**Comment by chaitrashenoy33** [comment]
+1

**Comment by benmccann** [comment]
In what way do you want the behavior to change?

**Comment by sridhark158** [comment]
@benmccann  like zoom out restriction 
chart should allow only to zoom in at the starting .. should not allow zoom out at the starting 
after zoom in it should allow to zoom out

**Comment by benmccann** [comment]
Have you tried setting `zoom.rangeMin` and `zoom.rangeMax`? If that's not sufficient you would need to fork the repo and make your changes to it

**Comment by sridhark158** [comment]
https://codepen.io/anon/pen/rEeXxp

in this codepen example can't we make zoom out restriction because once chart get load data at the starting if we keep zooming out this it will become like this
![zoomoutIssue](https://user-images.githubusercontent.com/32831520/59653607-52be8500-91b0-11e9-8da3-3a0f188e8230.PNG)

so can't we make it zoom out restriction if we have't zoom in
