### ISSUE TITLE
Clicking on a chart without mouse movement zooms out

### ISSUE THREAD

**Issue by Janmm14** [chartjs/chartjs-plugin-zoom#241]
Clicking on he chart without mouse movements seems to zoom out into infinity, whole graph is away.
Zoom config:
```javascript
zoom: {
    pan: {
        enabled: true
    },
    zoom: {
        enabled: true,
        drag: true,
        mode: "x"
    }
}
```

**Comment by benmccann** [comment]
This may be fixed in master: https://github.com/chartjs/chartjs-plugin-zoom/commit/6d7164c8bc6f56f6548cea6bc0b5758f65561c60

**Comment by Janmm14** [comment]
Ok, so I'll to wait for a new release.

**Comment by tanishiking** [comment]
Great, do we have any plans to release the latest version as `v0.7.1` ?

**Comment by yogevyuval** [comment]
In my case, clicking makes the chart zooms in to a really small distance. Can we limit the minimum drag distance?
@benmccann

**Comment by benmccann** [comment]
Released the new version

@yogevyuval I'm curious to see what the feedback is from this new version, but that might not be a bad idea
