### ISSUE TITLE
Cannot get the zoom-time.html project to work

### ISSUE THREAD

**Issue by KileyCaravella** [chartjs/chartjs-plugin-zoom#243]
I'm trying to get the zoom-time.html file to work so I can incorporate it's code directly into a project I am working on. I put the code into an html file, and the only change I made to the file was on `line 9`, where I replaced the folder dependency path with the actual html path:

    <script src="../dist/chartjs-plugin-zoom.min.js"></script>
    //changed to:
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/0.6.6/chartjs-plugin-zoom.min.js"></script>

The chart shows up, randomizes properly, etc. but doesn't zoom no matter what I do. Is there something I'm missing to get this to work?

Also, here is the html file I have been using to try this out (in .txt form to upload it here)
[html example.txt](https://github.com/chartjs/chartjs-plugin-zoom/files/3315247/html.example.txt)

Thanks in advance!

**Comment by benmccann** [comment]
0.6.6 is an old version. The samples are written to work with the latest version. Does it work if you try 0.7.0?

**Comment by KileyCaravella** [comment]
Do you know the path to the source file for 0.7.0? I tried changing the url to `https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/0.7.0/chartjs-plugin-zoom.min.js` but it returned a 404

**Comment by benmccann** [comment]
It looks like it only has an old version: https://cdnjs.com/libraries/chartjs-plugin-zoom. I don't know why

You can use https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@0.7.0

**Comment by KileyCaravella** [comment]
That did it! Thank you!
