### ISSUE TITLE
Release a new version for the plugin

### ISSUE THREAD

**Issue by yogevyuval** [chartjs/chartjs-plugin-zoom#247]
There are some important bug fixes in the master that has not been published yet. Is it possible to release a new version to npm?

Sorry for opening an issue for this, but could not get any comment in another way.

**Comment by benmccann** [comment]
There was a regression in the latest release that I'd like to see be fixed first. See https://github.com/chartjs/chartjs-plugin-zoom/pull/244

**Comment by benmccann** [comment]
Done
