### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined happens in doZoom function

### ISSUE THREAD

**Issue by courchef** [chartjs/chartjs-plugin-zoom#25]
I use time scale and I enabled both pan and zoom for the horizontal scale only.

When I zoom in a lot, at the point where there are no more ticks on the horizontal scale, an error is raised in Chart.js, in method `getLabelMoment`. Here is the callstack:

```
Uncaught TypeError: Cannot read property 'null' of undefined
    getLabelMoment @ Chart.js:9931
    getPixelForValue @ Chart.js:10182
    getPixelForTick @ Chart.js:10205
    calculateTickRotation @ Chart.js:6769
    update @ Chart.js:6644
    getMinimumBoxSize @ Chart.js:5773
    helpers.each @ Chart.js:4611
    update @ Chart.js:5766
    update @ Chart.js:3917
    doZoom @ Chart.Zoom.js:114
    wheelHandler @ Chart.Zoom.js:198
```

I guess that since this is not a situation that normally occurs in Chart.js, there are no protections in method `getLabelMoment`.

I do not see other options than doing a pull request in Chart.js. What do you think?

**Comment by etimberg** [comment]
@courchef I think you are right that this would need to be fixed inside of Chart.js itself

**Comment by courchef** [comment]
I just did a pull request for Chart.js
https://github.com/chartjs/Chart.js/pull/3024

**Comment by compwright** [comment]
Fixed - https://github.com/chartjs/Chart.js/pull/3194
