### ISSUE TITLE
Zoom in and Zoom out issue

### ISSUE THREAD

**Issue by johnkuriakose89** [chartjs/chartjs-plugin-zoom#260]
While Adding upto 30 or more fields in the x axis the zoom out functinality gets stuck while zooming out. Please find the example below. 
[Code pen](
https://codepen.io/anon/pen/xovQPj)

Zoom in completely to blue and they try to zoom out it would get stuck in  A B C D. User cannot do anything apart from reloading the page. 
![image](https://user-images.githubusercontent.com/29803667/61325218-7259c500-a7d1-11e9-9fa4-926e9501f9c1.png)

![image](https://user-images.githubusercontent.com/29803667/61325327-b51b9d00-a7d1-11e9-9b1d-f22b03f22bf0.png)

**Comment by dbaronov** [comment]
Looks like "labels" array values have to unique:

`
labels: ["Red","Blue","Yellow","Green","Purple","Orange","Majenta","Violet","Teal","A","B","C","D","E","F","G","H","J","K","L","M","N","O","P","R"],
`

**Comment by benmccann** [comment]
Thanks @dbaronov for providing a solution!

**Comment by johnkuriakose89** [comment]
Yup that was the problem. Thanks for the solution.
