### ISSUE TITLE
Zooming the Chart using HTML "range" input type?

### ISSUE THREAD

**Issue by dbaronov** [chartjs/chartjs-plugin-zoom#261]
How would I go about implementing zooming in and out the Chart using HTML "range" input type?

I have created this function to handle such behaviour:

```
 handleSliderZoom() {
        const _self = this;
        let oldVal: Number = (<any>_self.$rangeSlider).value;
        let mouseEvt = document.createEvent('MouseEvents');

        mouseEvt.initEvent('wheel', true, true);

        ['change', 'input'].forEach(function(event) {
            _self.$rangeSlider.addEventListener(event, function() {
                let newVal = (<any>this).value;

                if (newVal > oldVal) {
                    (<any>mouseEvt).deltaY = (newVal * -1);
                    console.log("right", newVal);
                }
                else if (newVal < oldVal) {
                    (<any>mouseEvt).deltaY = Math.abs((newVal * 1.3);
                    console.log("left", newVal);
                }
                oldVal = newVal;

                _self.$chartHolder.dispatchEvent(mouseEvt);
            }, false);
        });
    }
```

but it is not always consistent as heavily dependant on how rapidly the range element gets swiped.

**Comment by benmccann** [comment]
You can set `chart.options.ticks.min` and `max`

https://www.chartjs.org/docs/latest/axes/cartesian/linear.html

**Comment by dbaronov** [comment]
How will this help my case?

**Comment by dbaronov** [comment]
... or may be someone is aware of implementation to have this functionality d3 way like here:
https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

**Comment by benmccann** [comment]
Use the slider to allow user to choose min and Max. Set `chart.options.ticks.min/max` to the user chose values and call `chart.update`

**Comment by dbaronov** [comment]
I am working in a mixed type chart (line and bars) at the moment. Would it make any difference in approach?

**Comment by benmccann** [comment]
No, that shouldn't make a difference

Btw, if you don't want to zoom based on the scroll wheel or dragging on the chart area then you won't need this plugin to implement your feature

**Comment by etimberg** [comment]
This effectively needs the zoom API requested in #82. Closing in favour of the older issue
