### ISSUE TITLE
Is x-drag zooming operational at all?

### ISSUE THREAD

**Issue by joergplewe** [chartjs/chartjs-plugin-zoom#263]
Hi!

With my own code but also with the https://codepen.io/anon/pen/PGabEK sample I cannot get zooming enabled with `drag: true`, even when switching off panning at all. 
The brush rectangle is rendered, but actually nothing happens ... which is not completely true: If I try often enough, *some* zooming happens with quite erratic boundaries ....

Please don't mind this is a newbie's observation...

**Comment by benmccann** [comment]
Dragging definitely works. I didn't check your link, but the samples in the the samples directory of this repo work and I believe there's one (I think the time sample) that demonstrates dragging.

**Comment by joergplewe** [comment]
Thx for the quick response. 
I confirm that the samples do work flawlessly, so the problem must be on my side.

The link actually is not *my* link, but from the plugin's README.md. That codepen seems to relate to an old release (0.3.0?).

**Comment by alexanderlamb** [comment]
@joergplewe Did you ever find an answer for the erratic zooming?  Hitting a similar problem as well.

**Comment by joergplewe** [comment]
@alexanderlamb I'm sorry, no.
