### ISSUE TITLE
enabling pan doesn't allow charts to show latest value.

### ISSUE THREAD

**Issue by sanyam8182** [chartjs/chartjs-plugin-zoom#267]
If I enable pan for a chart, the chart stops showing the latest value and to see the latest value I have to drag the chart towards left. 
Below is the code I am using for pan.
```
pan: {
    enabled: true,
    mode: "x",
    speed: 10,
    threshold: 10
},
```

**Comment by etimberg** [comment]
This needs a test case to be able to reproduce
