### ISSUE TITLE
Pan start region

### ISSUE THREAD

**Issue by albmac** [chartjs/chartjs-plugin-zoom#276]
Is it possible to restrict the starting point of a pan action to a certain region of the chart (like only around the middle)?
My problem is that in order to be readable on a smartphone, a chart should have full width, but then scrolling above it triggers a pan.
Having instead a smaller "pan start region" would allow both scrolling and panning.
Is this something you can add in the future?

**Comment by albmac** [comment]
Meanwhile I found a workaround: place some transparent rectangles above the chart where it should not be responsive to pan/zoom:
<div class="chart-container">
<canvas id="mycanvas"></canvas>
<div style="position:absolute;left:0;top:0;width:25%;height:100%;background:rgba(0,0,0,0);"></div>
<div style="position:absolute;right:0;top:0;width:25%;height:100%;background:rgba(0,0,0,0);"></div>
</div><br>
Now it will only see the mouse/finger in the central region (25% to 75%)

**Comment by JZubero** [comment]
@albmac Kinda workaroundy but does the trick. This was working for me as well.
