### ISSUE TITLE
Pan is not working

### ISSUE THREAD

**Issue by enriquepiatti** [chartjs/chartjs-plugin-zoom#277]
Even in the official example here:   
https://codepen.io/pen/PGabEK   
Zoom is working fine, but pan is not working at all, I'm using Chart.js v2.8.0

**Comment by lamebear** [comment]
You need to add a reference to Hammer.js before chartjs-plugin-zoom.js. See here: https://github.com/chartjs/chartjs-plugin-zoom/issues/53

**Comment by jledentu** [comment]
@lamebear is right, see the README [here](https://github.com/chartjs/chartjs-plugin-zoom#installation).

A working example: https://codepen.io/jledentu/pen/VwwGKve
