### ISSUE TITLE
Panning Broken with Chart.js 2.9.0

### ISSUE THREAD

**Issue by exwm** [chartjs/chartjs-plugin-zoom#279]
With the latest chart.js v2.9.0 the `scale.getValueForPixel` method has been changed and its use in chartjs-plugin-zoom (tested with v0.7.4) causes misbehavior of pan with numerical scales and possibly others. Specifically, panning causes the chart to zoom. Exactly one of either the start or end of the scale remains fixed while the other stretches outwards. 

The `panNumericalScale` function in chartjs-plugin-zoom uses `scale.getValueForPixel` to get the new minimum and maximum values for the scale (see https://github.com/chartjs/chartjs-plugin-zoom/blob/1cf272f43cef1545f63c927c15e54fcc41673177/src/plugin.js#L257).

I believe the changes that are causing this issue were made in this commit of chart.js: https://github.com/chartjs/Chart.js/commit/cbace1cfe2c1b70ac26d1ee798eb5841fcd978c5#diff-f0d8f86fecab28f396793911b0e9f36dR746.

A demonstration of the bug can be found here: https://codepen.io/exwm/pen/vYYZREw. Simply pan the chart by dragging with the mouse.

**Comment by benmccann** [comment]
FYI @kurkle. Maybe a bug in handling reverse support in `core.scale`

**Comment by etimberg** [comment]
Chart.js v2.9.1 has been released with a fix for this issue
