### ISSUE TITLE
Deprecation warning with Chart JS 2.9.1 - time scale: "time.max" is deprecated. Please use "ticks.max" instead

### ISSUE THREAD

**Issue by ndrake** [chartjs/chartjs-plugin-zoom#280]
When using this plugin (v 0.7.4), I see the following deprecation warning in the console when zooming my charts:

```Chart.js:1990 time scale: "time.max" is deprecated. Please use "ticks.max" instead```

**Comment by jledentu** [comment]
I confirm this issue. We could fix this issue by removing `zoomTimeScale` (and use `zoomNumericalScale` on `time` scales), but we'd then break the compatibility with previous `Chart.js` versions, I guess.
