### ISSUE TITLE
Deprecation against Chart.js v3.0

### ISSUE THREAD

**Issue by devenbj** [chartjs/chartjs-plugin-zoom#283]
Testing the latest git for chart.js, there is a deprecation that impacts chartjs-plugin-zoom, on the current chartjs-plugin-zoom master src/plugin.js...

Line 419:
		var node = chartInstance.$zoom._node = chartInstance.chart.ctx.canvas;

Needs to be updated to:
		var node = chartInstance.$zoom._node = chartInstance.ctx.canvas;

Line 620:
		var ctx = chartInstance.chart.ctx;

Needs to be updated to:
		var ctx = chartInstance.ctx;

**Comment by benmccann** [comment]
Yes. Thanks you for catching. Would you like to send a PR? I would be happy to merge

**Comment by devenbj** [comment]
Of course. Never done pull requests before. Please let me know if I've done anything incorrectly.

Thanks!

**Comment by benmccann** [comment]
You did it perfectly. Thanks!!
