### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by aardrasystems** [chartjs/chartjs-plugin-zoom#296]
Hi I am using this plugin with Chart js, i have manged to pan on my graph but for some reason i can not zoom into the graph. I am using a Line Chart.

I am also using the most recent version of the plugin and chart js.

Has anyone experienced the same issue?

**Comment by jledentu** [comment]
Hi, can you post some code in a codepen/jsfiddle?

**Comment by reedipher** [comment]
I too am having issues with the zoom functionality. Can't even seem to get the sample zoom.html working.

**Comment by TyrelCB** [comment]
Same here
https://codepen.io/BlahBlahBlahBlahBlahBlahBlahBlahBlah/pen/BaaqQvb?editors=1010#anon-signup

**Comment by chewlm86** [comment]
Not sure if it is the same for you, but I get a lot of error after updating chartjs to v2.9.0+.
So I had to downgrade chartjs to v2.8.0 to get the existing plugins to work properly.

**Comment by benmccann** [comment]
@reedipher I have no problem running the sample `zoom.html`

@TyrelCB to the extent that you can simplify the example, it will improve the odds that someone has time to figure out what's wrong. E.g. can you reproduce with just a single data line with a handful of points, fewer options, no options toggling?

@chewlm86 if you can provide details about the errors you get and how to reproduce them that would be helpful

**Comment by IDrissAitHafid** [comment]
Me too I have the same problem and I managed to resolve it by switching back to version 0.7.4.
So using npm run : `npm install --save chartjs-plugin-zoom@0.7.4` .
Or with script : `<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@0.7.4"></script>
`

**Comment by jledentu** [comment]
@TyrelCB I guess that zoom doesn't work well on `category` scales. Since you display timeseries data, you could use a `time` scale.

@IDrissAitHafid Can you post an example? My own examples are working, so I guess the bug depends on your chart data or options.

**Comment by TyrelCB** [comment]
@jledentu Switching to ``` time ``` scale looks to have done the trick. Any Idea as to why this doesn't work with ``` category ``` scales?
