### ISSUE TITLE
Drag mode hides tooltips, but not custom tooltips

### ISSUE THREAD

**Issue by jledentu** [chartjs/chartjs-plugin-zoom#298]
Hi,

I met some inconsistency between regular/custom tooltips on zoom in drag mode.
If `tooltips` are `enabled`, there are hidden during dragging, as you can see [in this fiddle](https://jsfiddle.net/yqa52tbh/) (tested in Firefox 70 and Chromium 78), although it's not explicitly handled by the zoom plugin. I think it's because the `update` call in the `mouseover` handler.

However, `tooltips.custom` is called while dragging, as you can see [here](https://jsfiddle.net/xfvbrdLe/).

I think we should explicit the behaviour in the plugin?

**Comment by etimberg** [comment]
Updated fiddles for v3
Regular tooltip: https://jsfiddle.net/dof9bgzt/
Custom tooltip: https://jsfiddle.net/m28kyL7u/

**Comment by jledentu** [comment]
As a workaround, I wrote a custom plugin that disables custom tooltips when dragging:

```js
beforeUpdate(chart) {
  chart.tooltip.prevent = !!chart.$zoom._dragZoomStart;
},
```

And in my tooltip callback, I early return if `chart.tooltip.prevent` is `true`. It's a bit ugly, so it would be nice if the plugin disabled tooltips natively. I don't know how to disable tooltips in a given `update` (by setting the `_active` property of the tooltip plugin?).
