### ISSUE TITLE
Stepped 'category' pan or smooth?

### ISSUE THREAD

**Issue by QuantumBob** [chartjs/chartjs-plugin-zoom#30]
I have been looking at implementing x axis panning for bar charts but was wondering if you were wanting a smooth pan like numerical pan or a stepped pan which jumps by one whole bar each time the pan initiates?

**Comment by etimberg** [comment]
@QuantumBob I think a stepped pan makes more sense. It'd be weird IMO to have half a bar visible

**Comment by QuantumBob** [comment]
OK. I was thinking the same. Will look into it.

**Comment by brendanmorrell** [comment]
I'd like to reopen this (very old) issue. Is it possible to achieve smooth panning for bar/line charts? I personally find the smooth scroll achievable in the scatter chart to be infinitely better UX in the stepped, slightly choppy panning in bar/line charts. When I use a scrollbar or am dragging an element, it is my expectation that it will move in a fluid motion, not jump at specific intervals.

Does anyone know if this is possible to do for bar/line charts? i have been searching for days to no avail. It's possible I will have to switch to a separate charting library.

**Comment by frimkus** [comment]
@brendanmorrell  Did you find a way or did you have to change chart library?

**Comment by brendanmorrell** [comment]
Unfortunately, I switched libraries (Victory Charts). Never found a fix.

**Comment by yay** [comment]
Wondering if smooth panning with a category axis is possible with the latest version of ECharts?

Example of smooth panning with a category axis: https://www.tradingview.com/chart/

It doesn't look weird to me to have half a bar visible. And it doesn't look weird to a whole lot of people: https://www.tradingview.com/blog/en/tradingview-world-s-top-100-websites-22725/

**Comment by yay** [comment]
An example where smooth panning with a category axis results in an arguably better user experience is axis labels.

Notice how axis labels are jumpy and hard to keep track of in ECharts:
https://github.com/user-attachments/assets/d80e5ae7-2119-4b6b-92c2-fe71b3b45d20

And compare to smooth continuous motion of bottom axis labels in TradingView charts:
https://github.com/user-attachments/assets/4c093cba-0394-48ae-950d-2bce1720b5d5
