### ISSUE TITLE
Problem zooming in mobile

### ISSUE THREAD

**Issue by mymggithub** [chartjs/chartjs-plugin-zoom#300]
I tried you live demo https://codepen.io/anon/pen/PGabEK

But it seams I am having trouble with mobile.

What more is needed for it to work on mobile phones?

Any help would be appericated.
Thank you.
Mark G

**Comment by jledentu** [comment]
The Codepen is outdated. I made a PR to update it: https://github.com/chartjs/chartjs-plugin-zoom/pull/301

You need to include hammerjs to make the plugin work on touch devices.

**Comment by benmccann** [comment]
Thanks for the fix @jledentu ! I've merged your PR, so marking this as fixed
