### ISSUE TITLE
ChartJs Zoom and Pan Range

### ISSUE THREAD

**Issue by carlottabacchini** [chartjs/chartjs-plugin-zoom#304]
Hi,
I'm using the chart js zoom plugin, but I have a problem with the zoomRange.
I have a chart on which I want the user to be able to zoom in, and not to zoom out (only in the Y axis). I mean that I don't want that the values on y-axis go below the zero, because if they do the graph would be unreadable. How can I do it?

Thi is the fiddle: https://jsfiddle.net/qf58p0at/

Thank you in advance!

**Comment by benmccann** [comment]
You can set the option `zoom.rangeMin.x`. Please see the readme

**Comment by carlottabacchini** [comment]
> You can set the option `zoom.rangeMin.x`. Please see the readme 
@benmccann 

It doesn't work as expected. Can you see the fiddle?

**Comment by benmccann** [comment]
You must set it as `plugins.zoom.zoom.rangeMin.x`. You are missing the `plugins.zoom` portion. Please follow the example on the readme
