### ISSUE TITLE
OnZoomCompleted not working properly on touch devices

### ISSUE THREAD

**Issue by MadMonkey87** [chartjs/chartjs-plugin-zoom#305]
Hi

I am using the OnPanComplete and the OnZoomComplete callbacks to reload the chart data from a server. This works fine except for the OnZoomComplete callback in touch devices where the event behaves like the OnZoom callback as it fires constantly durig zooming. Zooming using the scroll wheel however is working just fine and the event fires only when the zooming is completed.

edit: I was able to reproduce the problem on an android device as well as on a windows device with a touch screen

**Comment by benmccann** [comment]
Could possibly be related to https://github.com/chartjs/chartjs-plugin-zoom/issues/265. Can you make sure you're using 0.7.5?

**Comment by MadMonkey87** [comment]
Yes, I am using 0.7.5 (chart js: 2.9.3, hammer js 2.0.8). Could indeed be related to #265 but it is not exactly the same as the event is fired, just too often

**Comment by gvendraminetto** [comment]
Hi

I have the same problem, onZoomComplete callback fires constantly durig zooming in touch devices. I am using version 0.7.5. Any workaround?
