### ISSUE TITLE
Slow zoom for huge data 

### ISSUE THREAD

**Issue by koba-1** [chartjs/chartjs-plugin-zoom#306]
Even adding speed and sensitivity the zoom remains unusable with huge data. 
Do you know how to make it work?
https://codepen.io/thinkerBell/pen/ZNNwWV

Edit: I'm not talking about performance.

**Comment by benmccann** [comment]
I don't have time to look at the moment, but please make sure you've seen this page: https://www.chartjs.org/docs/latest/general/performance.html

In Chart.js 3.0 we will have really big performance improvements

**Comment by koba-1** [comment]
Thank you for the info but I'm not talking about performance, I'm saying that even setting "Speed" and "Sensitivity", with huge data, requires too many scrolls to actually zoom the chart...
