### ISSUE TITLE
A doubt about documentation v0.7.5

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-zoom#307]
Reading the README file which describes how to configure the plugin and comparing it with the code and samples of plugin, I don't find some properties.

Default options for PAN reports `speed` and `threshold` which are not mentioned.
Default options for ZOOM reports `sensitivity` which is not mentioned.

Into [zoom-log](https://github.com/chartjs/chartjs-plugin-zoom/blob/v0.7.5/samples/zoom-log.html) sample at `zoom` options there is [xScale0](https://github.com/chartjs/chartjs-plugin-zoom/blob/2e753e08a40d35d60e624ae600ec15c0bae9b9d9/samples/zoom-log.html#L184) property which is not mentioned.

Are these properties to consider as internal one or they are missing from documentation?

**Comment by benmccann** [comment]
`speed`, `threshold` and `sensitivity` should probably be documented. @jledentu does that make sense to you?

`xScale0` sounds internal

**Comment by jledentu** [comment]
@benmccann I agree.

`speed` is actually documented:

```js
// Speed of zoom via mouse wheel
// (percentage of zoom on a wheel event)
speed: 0.1,
```

The [Hammer.js documentation](http://hammerjs.github.io/recognizer-pan/) defines `threshold` as:

> Minimal pan distance required before recognizing

```js
// Minimal pan distance required before actually applying pan
threshold: 10
```
?

`sensitivity` could be documented as:

```js
// On category scale, minimal zoom level before actually applying zoom
sensitivity: 3
```

`sensitivity` may even be renamed `threshold`?

**Comment by stockiNail** [comment]
Thank you @jledentu 

> 
> `speed` is actually documented:
> 
> ```js
> // Speed of zoom via mouse wheel
> // (percentage of zoom on a wheel event)
> speed: 0.1,
> ```

Not really. This is the doc for ZOOM but not for PAN.

Having a look [here](https://github.com/chartjs/chartjs-plugin-zoom/blob/6a97a22b99e0325597b7bd7b38b083dde4949a60/src/plugin.js#L19), there are the defaults for PAN object where speed is set.
And it is set to 20, therefore not compliant with the description of speed on ZOOM, where I assume being a percentage is a value between 0 and 1.

Am I wrong?

**Comment by jledentu** [comment]
@stockiNail Oh you're right.

Mmh `pan.speed` seems to be used only on category scales, as a threshold (!) factor before applying pan.

**Comment by stockiNail** [comment]
Thank you  @jledentu for your reply.
 
You got my doubts about the configuration. I don't know who is really using those configuration properties but, writing a wrapper for this plugin to use in another project, I need to know how the developers can configure it.

Sorry for that.

**Comment by jledentu** [comment]
@stockiNail I added some documentation in #333. I suggest to close this issue for now, please reopen if you think something is missing.

**Comment by stockiNail** [comment]
@jledentu sounds good! Thank you
