### ISSUE TITLE
Panning does not work with draggable-date plugin

### ISSUE THREAD

**Issue by Zuckerbrot** [chartjs/chartjs-plugin-zoom#308]
I am using chart.js with the draggable data plugin
https://github.com/chrispahm/chartjs-plugin-dragdata

I would also like to use the panning functionality of the zoom-plugin.

However,I can only get either panning or data-dragging to work.
Example (works in Safari):
https://jsfiddle.net/zpq8an40/1/

This seems to be related to the fact that both panning and dragging use the same mouse gesture.

Would be nice to have both, like eg here
http://bl.ocks.org/stepheneb/1182434.

Would it be possible to allow the definition of a panKey, like {shift, ctrl, alt}, which, if pressed, toggles either the data-dragging or panning functionality?
This approach is used with highcharts to allow for both functionalities, cf. https://api.highcharts.com/highcharts/chart.panKey

Thanks very much and happy holidays!

**Comment by benmccann** [comment]
I would be open to a pull request to add this functionality. I don't have time to add it myself

**Comment by jledentu** [comment]
@Zuckerbrot Good idea. I'd suggest to call this new property `modifierKey`.

```js
plugins: {
	zoom: {
		pan: {
			enabled: true,
                        modifierKey: 'alt'
                },
                zoom: {
			enabled: true,
                        modifierKey: 'alt'
                }
        }
}
```

**Comment by etimberg** [comment]
Looks like this got merged
