### ISSUE TITLE
Resetting all charts zoom using jquery and canvas dom elements

### ISSUE THREAD

**Issue by Shadok** [chartjs/chartjs-plugin-zoom#312]
Hello,

I cam having trouble resetting multiple charts and access them though their canvas using jquery (the goal is to zoom on all charts, i found interesting leads in other issues)

I am using jQuery 3.3.1, Charts.js 2.9.3 and latest zoom plugin.

All my charts are created in a loop, pointing on a canvas id :
```
var chart   = new Chart( $('#' + cid), {
...
});
```
I can't use the chart var to reset it.

I was trying like this, but i get the error "ctx.resetZoom is not a function" :
```
    $('canvas').each( function( index ) {
        //var ctx = $(this)[0].getContext( '2d' );
        //var ctx = $(this).get(0).getContext( '2d' );
        var ctx = document.getElementById( $(this).attr('id') ).getContext( '2d' );
        ctx.resetZoom();
    })
```

What i am doing wrong ?

Thanks.

**Comment by jledentu** [comment]
Hi,

You try to call `resetZoom` on a native [`CanvasRenderingContext2D`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) instance. A `CanvasRenderingContext2D` doesn't have a such function.

You need to call `resetZoom` on a `chart` instance, so you need to keep a reference on charts you created:

```js
var ids = ['chart1', 'chart2', 'chart3'];
var charts = ids.map(id => new Chart(document.getElementById(id), {
...
}));

// Reset zooms
charts.forEach(chart => chart.resetZoom());
```

**Comment by Shadok** [comment]
I don't know how many charts i will have to draw in advance, so i can't use map this way.

**Comment by Shadok** [comment]
Too bad there is no way to access the chart options without keeping a reference on drawed charts.

**Comment by jledentu** [comment]
@Shadok Thanks for your feedback. How could we keep a reference without storing it in a variable?

Since you resolved your issue, I close this.
