### ISSUE TITLE
Data zoom option in chart.js

### ISSUE THREAD

**Issue by BattiniSantthosh** [chartjs/chartjs-plugin-zoom#316]
Is there any option to zoom the data as below link?

https://echarts.apache.org/examples/en/editor.html?c=area-simple

**Comment by benmccann** [comment]
No

**Comment by benmccann** [comment]
You'd have to create a second chart and then change the scale `min` and `max` on both. You could look at the code in the repo for an example of how to make a draggable area. But this plugin only works on one chart at a time and it will zoom that chart. In the example you provided the lower chart is not zoomed after dragging
