### ISSUE TITLE
Minimal step for "drag to zoom" on time chart

### ISSUE THREAD

**Issue by krulj** [chartjs/chartjs-plugin-zoom#317]
I am trying to limit "sensitivity" of drag to zoom functionality, more precisely I want to start zooming only when user select at least 2% of chart. 

When user clicks on chart and start to drag (in order to zoom in), after releasing mouse button, I need to calculate if user selected just small part of chart (for example below 2% of whole chart):
- If yes, then chart will not be zoomed
- If no, then chart will be zoomed as usual

If someone done something similar, I appreciate your help!

**Comment by cnojima** [comment]
I understand that this is an old issue.  I'm looking at the same need, i'm toying with a PR at the moment.

If you want a quick, hard-coded fix, change the `0` to `> 0` in this line: https://github.com/chartjs/chartjs-plugin-zoom/blob/master/src/plugin.js#L485

`2` works well to solve the issue i was trying to handle, other values may fit your use-case better.

If i do submit a PR, it'll be for a new option to set the drag-sensitivity to an integer.

**Comment by benmccann** [comment]
Closed by https://github.com/chartjs/chartjs-plugin-zoom/pull/347
