### ISSUE TITLE
drag-to-zoom does not work when `mode` is a function

### ISSUE THREAD

**Issue by SomeKittens** [chartjs/chartjs-plugin-zoom#319]
This is because [`directionEnabled`](https://github.com/chartjs/chartjs-plugin-zoom/blob/6a97a22b99e0325597b7bd7b38b083dde4949a60/src/plugin.js#L80-L88) only handles the case where `mode` is `undefined` or a string.

Happy to submit a PR to fix this.

**Comment by benmccann** [comment]
Sure, a PR would be welcome
