### ISSUE TITLE
When zooming in a lot in a line chart the tooltip disappears

### ISSUE THREAD

**Issue by yennor** [chartjs/chartjs-plugin-zoom#321]
I've got about 10 000 sample points seperated over a year.
When I plot them all, I need to zoom in a lot to see like a week. 
The problem is, that then the tooltip doesn't get drawn anymore, when hovering over a datapoint. As far as I could see, it seems to be drawn outside of the canvas.
When I zoom out enough, the tooltip gets drawn again (is visible again).

**Comment by jledentu** [comment]
Hi, could you provide a jsfiddle/codepen to reproduce your issue?

**Comment by yennor** [comment]
sure. 
But I'm sorry to say that it could take around two weeks. right now I'm swamped in work...

**Comment by yennor** [comment]
Sorry that it took me that long.
I've tried to reproduce the behaviour.
But I can't. I know that it happened regularly. 
But maybe the browser changed, maybe I've used other sample data. Maybe something else.
So sorry to bother you. I guess we can close that one. If it happens again, I'll record directly how I get there.

**Comment by maxwell-oroark** [comment]
The tooltip renders out of the canvas 'viewport'. This happens to me and I can reproduce. Basically if you are zoomed in and you hover over a point the tool tip is rendered below the current viewport on the canvas. If you zoom out you can see the tooltip again

**Comment by xpedigital** [comment]
The problem I guess still lives. Tooltip disappears on zoom in 200% which is an ADA/WCAG compliance.
