### ISSUE TITLE
Apply resetZoom animation event at duration:0

### ISSUE THREAD

**Issue by raevillena** [chartjs/chartjs-plugin-zoom#328]
I recently used chartjs and disabled animations using (duration:0)  with this, resetZoom animation will be also disabled.

with the current version of the plugin I havent found a way to enabled animation of resetZoom without editing the library.

if you wondered how did I modify that;

just change line 407: `chartInstance.resetZoom = function () { `-->` chartInstance.resetZoom = function (duration) {`
and then line 442: `chartInstance.update();` --> `chartInstance.update(duration);`

then in your component, you call the function like this: `Instanceref.resetZoom(1000)`

**Comment by kurkle** [comment]
Closing as Chart.js v2 is no longer in development. In Chart.js v3 the animations are much more flexible.
