### ISSUE TITLE
Not zooming on other zone that chartArea should be an option

### ISSUE THREAD

**Issue by Nortalle** [chartjs/chartjs-plugin-zoom#331]
Desired Behavior :
- When I zoom anywhere except on the chartArea I want the zoom not to be enabled

Actual behavior : 
- When I zoom ouside the chartArea, a zoom occurs.
![coucou](https://user-images.githubusercontent.com/23353545/75983150-4453fd00-5ee8-11ea-9a7b-78782e764e81.png)

**Comment by benmccann** [comment]
We should test this with Chart.js 3.0 when it's released since that may fix it

**Comment by etimberg** [comment]
I tested this in the samples and it does not appear resolved in v3. Dragging over the chart title still caused a zoom

**Comment by kurkle** [comment]
This can be done today: https://www.chartjs.org/chartjs-plugin-zoom/samples/pan-region.html
