### ISSUE TITLE
Cannot read property '_dragZoomEnd' of undefined

### ISSUE THREAD

**Issue by yennor** [chartjs/chartjs-plugin-zoom#332]
I'm trying to use the zoom plugin with chart js 2.9.3 (which is included in primefaces), and I get following error:

> chartjs-plugin-zoom@0.7.5:11 Uncaught TypeError: Cannot read property '_dragZoomEnd' of undefined
>     at Object.beforeDatasetsDraw (chartjs-plugin-zoom@0.7.5:11)
>     at Object.notify (chartjs.js.jsf?ln=primefaces&v=8.0:8015)
>     at Chart.drawDatasets (chartjs.js.jsf?ln=primefaces&v=8.0:9891)
>     at Chart.draw (chartjs.js.jsf?ln=primefaces&v=8.0:9828)
>     at Chart.render (chartjs.js.jsf?ln=primefaces&v=8.0:9782)
>     at Object.callback (chartjs.js.jsf?ln=primefaces&v=8.0:2204)
>     at Object.advance (chartjs.js.jsf?ln=primefaces&v=8.0:3528)
>     at Object.startDigest (chartjs.js.jsf?ln=primefaces&v=8.0:3501)
>     at chartjs.js.jsf?ln=primefaces&v=8.0:3490
> 

That error appears as soon as the chart gets loaded with the data, before the user can do any interaction.
You've got any idea what the problem could be there? I don't really think that primefaces changes the chartjs library. Since I'm using other plugins without any problems.
The zoom config is pretty standard:

> 		        zoom: {
>           			pan: {
> 		            	enabled: true,
>         		    	mode: "x"
>           			},
>           			zoom: {
> 			            enabled: true,
> 			            drag: false,
> 			            mode: "x",
>             			speed: 0.1
>           			}
>         		}
>

**Comment by benmccann** [comment]
This isn't quite enough information to reproduce the error. Are you able to create an interactive example using something like Codepen or Plunker?

**Comment by yennor** [comment]
i was afrid it wouldn't be enough information. I just hoped it would be a somehow known Problem (version, etc.)...
anyway, I've just found it out that minute. It seemed to be a timing issue...
As it seems the zoom js library was not completely loaded when the chart already started painting.
sorry about bothering you
