### ISSUE TITLE
Allow zooming only with a pressed modifier key

### ISSUE THREAD

**Issue by NicolasGoeddel** [chartjs/chartjs-plugin-zoom#335]
Hi,

when I create a nearly page filling graph with the zoom functionality enabled, it is nearly impossible to find a spot where is no canvas to scroll the page. It would be nice if one could set a modifier key like Alt, Ctrl or Shift to enable zooming with the scroll wheel.

If there is already such a functionality, can you please give me an example application?

**Comment by NicolasGoeddel** [comment]
I tried to change the `enabled` property with some key binds but although the property gets changed it does not enable the zooming functionality.

The `graphs` object stores all my graphs on the page and I iterate through them to change the state of the zoom.
```javascript
  $(document).keydown(function(event) {
    if (event.shiftKey) {
      for (var g in graphs) {
        graphs[g].options.plugins.zoom.zoom.enabled = true;
        console.log('enabled');
      }
    }
  });

  $(document).keyup(function(event) {
    if (event.shiftKey) {
      for (var g in graphs) {
        graphs[g].options.plugins.zoom.zoom.enabled = false;
        console.log('disabled');
      }
    }
  });
```

**Comment by KoalaBear84** [comment]
What if you also add?

`graphs[g].update();`

**Comment by etimberg** [comment]
A wheel modifier key was added in #382
