### ISSUE TITLE
Checking if zoom is active

### ISSUE THREAD

**Issue by tarockx** [chartjs/chartjs-plugin-zoom#343]
Hello everybody

I want to show a "reset zoom" button on my web page, but I only want to show it if the chart is actually zoomed (i.e.: if it isn't completely zoomed out).

However, I can't seem to find a way to do this. I tried using the "onZoomComplete" callback, but it only has the "chart" parameter (which is the chart object), but no parameter that tells me the current zoom level. 

Is there a way to get the current zoom level / know if zoom is active?

**Comment by Jiiieeef** [comment]
I am really interested by this enhancement to toggle the stacked option when the zoom is active or not :)
