### ISSUE TITLE
zoom with slider bar

### ISSUE THREAD

**Issue by pigobyte** [chartjs/chartjs-plugin-zoom#344]
> 
> 
> i have the chartjs-plugin-zoom.js file in my solution and just added two more function to the chart instance to zoom in and zoom out after the _WheelHandler function.
> 
> ```
>   chartInstance.ZoomIn = function () {
>                         var rect = document.getElementById(chartInstance.canvas.id).getBoundingClientRect();
> 
>                         var center = {
>                             x: rect.width / 2,
>                             y: rect.height / 2
>                         };
> 
>                         doZoom(chartInstance,1.1,center);
>                     };
> 
> 
>                     chartInstance.ZoomOut = function () {
>                         var rect = document.getElementById(chartInstance.canvas.id).getBoundingClientRect();
> 
>                         var center = {
>                             x: rect.width / 2,
>                             y: rect.height / 2
>                         };
> 
>                         doZoom(chartInstance,0.909,center);
>                     };
> ```
> 
> and then I just call them on the button click

Woul love to see working example, cant make it work.

_Originally posted by @ravau in https://github.com/chartjs/chartjs-plugin-zoom/issues/43#issuecomment-499963556_

hi .. could you explain better how to use this your solution?
thank you!

**Comment by etimberg** [comment]
Zoom and pan methods added to the chart in #464 along with an example that should answer this question
