### ISSUE TITLE
Document how to get new zoomed data range

### ISSUE THREAD

**Issue by JMRCGuedes** [chartjs/chartjs-plugin-zoom#345]
Hello guys!!

I'm trying to get the range x-axis values when i apply the zoom by dragging in the chart like in the following example:

![image](https://user-images.githubusercontent.com/64259581/80206068-9df0c200-8623-11ea-9a34-b247778cabd1.png)

**Comment by poiuytrez** [comment]
This is how I found what is selected:

```
onZoomComplete: function({chart}) {
              console.log(`I was zoomed!!!`);
              const start = new Date(chart.chart.boxes[2].min);
              const end = new Date(chart.chart.boxes[2].max);
              console.log(start);
              console.log(end);
            }

```

**Comment by kurkle** [comment]
`chart.getZoomedScaleBounds()` was added in #780
