### ISSUE TITLE
Category Zoom

### ISSUE THREAD

**Issue by QuantumBob** [chartjs/chartjs-plugin-zoom#35]
Hi,

I was going to look at the category zoom next.
My thinking is to use a similar method to panning with a one step zoom, testing whether the mouse is left or right of centre and showing that sides bar.
For pinch zoom we could have left bar, right bar, left bar etc or check which part of the screen has been pinched (that might be difficult!)
Any thoughts would be greatly appreciated

**Comment by etimberg** [comment]
I think that is a good way to approach it. You might find that the zoom becomes very sensitive when there are only a few labels. it might make sense to have some sort of parameter to control how much you need to zoom before stepping
