### ISSUE TITLE
zoom plugin is not compatible with Salesforce locker services..

### ISSUE THREAD

**Issue by venkatpolisetti** [chartjs/chartjs-plugin-zoom#357]
I am trying to use this plugin with chartjs and it does not load at all when I try to use it in Lightning Web Components. Salesforce simply throws an exception and does not even give any error message.

What does it take to make this plugin locker service compatible?

**Comment by etimberg** [comment]
Is there any documentation on what salesforce locker supports?

**Comment by kurkle** [comment]
Closing as Chart.js v2 is no longer in development, and missing a test case.
