### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by dospina97** [chartjs/chartjs-plugin-zoom#358]
I've been trying to make this plugin work in my project,  but I couldn't do it. I've downloaded the whole plugin folder to check the examples and try to figure out my mistake, but it turns out that the examples doesn't work either, they can't load a script:

Ha fallado la carga del <script> con origen "file:///C:/Users/dospi/Downloads/chart/chartjs-plugin-zoom-9fa70365e7b9b2a36baac7cd7c9a77ac7548af26/dist/chartjs-plugin-zoom.min.js".

That's the issue that i've found

**Comment by benmccann** [comment]
You have to run `npm install` and `gulp build` before running the examples locally
