### ISSUE TITLE
Zooming a category axis with the mouse wheel barely works

### ISSUE THREAD

**Issue by yoelz55** [chartjs/chartjs-plugin-zoom#360]
Hi there,

- **What version of the plugin and chart.js?**
Chartjs: 2.9.3
Zoom: 0.7.7

The zoom on the y-axis works perfectly.
The x-axis doesn't work at all when the mouse cursor while zooming is on the left side, and when the cursor is on the right side, it does the zoom but really really slow (even when changing the speed and sensitivity) .

I tried also the functionality of zoom by dragging, unfortunately, I got the same result, the x-axis didn't work but the y-axis worked fine.

Please check out this example:
[https://codepen.io/yoelz55/pen/WNQLxRN](https://codepen.io/yoelz55/pen/WNQLxRN)

Thank you in advance for any help,
Yoel

_Originally posted by @yoelz55 in https://github.com/chartjs/chartjs-plugin-zoom/issues/50#issuecomment-631043099_

**Comment by borjaseijo** [comment]
I have obtained the same issue but using date scale in the x-axis. I have used following library versions:
- Chartjs: 2.9.3
- Hammer.JS: 2.0.7 
- Zoom: 0.7.7

**Comment by DjovDev** [comment]
I resolved this with changing the type of X-axis to "time". In my case I had the "time" on the X-axis as well so it came out fine. Here is the piece of code defining my X-axes:

My X-data is populated with Date objects.

> xAxes: [{
>     type: "time",
>     time: {
>         format: 'HH:mm',
>         unit: 'minute'
>     }
> }]

**Comment by silasrm** [comment]
Any solution? My data has a incremental X value, not a datetime. Zoom plugin doesn't work on X axis.
![image](https://user-images.githubusercontent.com/197187/114615734-689e1380-9c7c-11eb-8cca-2bcbb6d14462.png)

**Comment by silasrm** [comment]
> Any solution? My data has a incremental X value, not a datetime. Zoom plugin doesn't work on X axis.
> ![image](https://user-images.githubusercontent.com/197187/114615734-689e1380-9c7c-11eb-8cca-2bcbb6d14462.png)

My solution is using seconds based on length of my data:

```
const ms = allTradesFull.length;
const startDate = moment().subtract(ms, 'second');

// chartjs config:
const config = {
  //...
  labels: allTradesFull.map((item, k) => moment(startDate).add(k + 1, 'second').toString()),
  //....
  // scales config:
  xAxes: [{
      type: "time",
      time: {
          unit: 'second',
      },
      display: false,
      scaleLabel: {
          display: true,
          labelString: 'Trade #'
      },
      ticks: {
          beginAtZero: true,
          maxRotation: 0,
      },
  }],
  // tooltip config:
  tooltips: {
      mode: 'index',
      intersect: false,
      callbacks: {
          title: function (tooltipItem) {
              return (typeof allTradesFull[tooltipItem[0].index] === 'object' && allTradesFull[tooltipItem[0].index] ? allTradesFull[tooltipItem[0].index].x : null);
          },
          label: function (tooltipItem) {
              return `${currency(tooltipItem.value, '', 2, {thousandsSeparator: '.', decimalSeparator: ','})}`;
          }
      }
  },
};

```

This is the result:
![image](https://user-images.githubusercontent.com/197187/114649932-c3a12c00-9cb7-11eb-8126-6d316bf0492b.png)

**Comment by kurkle** [comment]
Zoom seems to work fine with 1.0.0-beta.3, but pan does not work correctly (because of skipped labels):
https://codepen.io/kurkle/pen/JjEVWZx
