### ISSUE TITLE
Prevent scale change on pan

### ISSUE THREAD

**Issue by abhishekac** [chartjs/chartjs-plugin-zoom#361]
How to prevent zoom on panning. While panning, I can see the chart being zoomed. But there is no zoom event called. How to prevent that?

**Comment by riccardobellini** [comment]
I had a similar problem, it solved when I noticed that the time axis had this option:

`distribution: "series"`

I removed this line, so distribution defaults to "linear", and panning worked without zooming and distorting the chart.
Hope this helps.

**Comment by kurkle** [comment]
This should be already fixed in v1.0.0-beta.4
