### ISSUE TITLE
zoom on x axis on time/date csv series

### ISSUE THREAD

**Issue by BlueEther** [chartjs/chartjs-plugin-zoom#364]
using release 0.7.7 x-axis zoom using date / time in format YYY-MM-DDTHH:MM:SSZ format, using 0.7.4  and it seems to work:

```
function makeChart(temps) {

  var timeStamp = temps.map(function(d) {return d.Time});
  var DeckTemp = temps.map(function(d) {return +d.Deck});
  var BaseTemp = temps.map(function(d) {return +d.BaseStation});
  var G_aTemp = temps.map(function(d) {return +d.Ground_air});
  var G_30Temp = temps.map(function(d) {return +d.Ground_30cm});
  var LoungeTemp = temps.map(function(d) {return +d.Lounge});

  var chart = new Chart('chart', {
    type: 'line',
    options: {
      maintainAspectRatio: false,
      legend: {
        display: false
      },
      scales: {
        xAxes: [{
            type: 'time',
            distribution: 'linear',
            scaleLabel: {
              display: true,
              labelString: 'Home Temps',
              fontSize: 16
            }
          }
        ]
      },
      plugins: {
			  zoom: {
					  pan: {
						  enabled: true,
						  mode: 'x'
					  },
					  zoom: {
              enabled: true,
              drag: true,
              mode: 'x',
              onZoom: function({chart}) { console.log(`I'm zooming!!!`); },
              // Function called once zooming is completed
              onZoomComplete: function({chart}) { console.log(`I was zoomed!!!`);               }
					  }
				  }
			  }
    },
    data: {
      labels: timeStamp,
      datasets: [
        {//data: BaseTemp,
        backgroundColor:  ['rgba(255, 99, 132, 0.2)'],
        borderColor:      ['rgba(255, 99, 132, 1)'],
        borderWidth:1,
        pointRadius:0,
        },
        {data: DeckTemp,
        backgroundColor:  ['rgba(54, 162, 235, 0.2)'],
        borderColor:      ['rgba(54, 162, 235, 1)'],
        borderWidth:1,
        pointRadius:0,
        },
        {data: LoungeTemp,
        backgroundColor:  ['rgba(255, 159, 64, 0.2)'],
        borderColor:      ['rgba(255, 159, 64, 1)'],
        borderWidth:1,
        pointRadius:0,
        },
        {data: G_aTemp,
        backgroundColor:  ['rgba(75, 192, 192, 0.2)'],
        borderColor:      ['rgba(75, 192, 192, 1)'],
        borderWidth:1,
        pointRadius:0,
        },
        {data: G_30Temp,
        backgroundColor:  ['rgba(153, 255, 102, 0.2)'],
        borderColor:      ['rgba(153, 255, 102, 1)'],
        borderWidth:1,
        pointRadius:0,
        }
      ]
    }
    
  })
}

// Request data using D3 
d3.csv('https://........./temp.csv')  
.then(makeChart);
```

CSV format is:

*Time,Deck,Lounge,BaseStation,Ground_air,Ground_30cm,Bed_Cady,Bed_Ismay,Bed_Master,Kitchen
2020-06-09T07:03:37Z,12.13,21.13,31.44,11.19,12.5,,,,
2020-06-09T07:04:08Z,12.19,21.13,31.44,11.13,12.5,,,,
2020-06-09T07:04:39Z,12.13,21.13,31.44,11.13,12.5,,,,
2020-06-09T07:05:10Z,12.13,21.13,31.44,11.13,12.5,,,,
2020-06-09T07:05:41Z,12.13,21.13,31.44,11.19,12.56,,,,
2020-06-09T07:06:12Z,12.13,21.13,31.44,11.19,12.56,,,,
2020-06-09T07:06:43Z,12.06,21.13,31.44,11.19,12.5,,,,
2020-06-09T07:07:14Z,12,21.13,31.44,11.13,12.5,,,,
2020-06-09T07:07:45Z,11.94,21.13,31.38,11.13,12.5,,,,*

**Comment by benmccann** [comment]
Can you test with 0.7.5 and 0.7.6 to help narrow down when it broke?

The sample works still: https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html

**Comment by BlueEther** [comment]
0.7.5 and on doesn't work
Live code that i'm using here:
https://codepen.io/blueether/pen/xxZwXQb

**Comment by JelleBlaauw** [comment]
I have the same issue. Can confirm it doesn't work anymore since 0.7.5.

**Comment by benmccann** [comment]
@BlueEther I just tried looking at your codepen to debug this, but it doesn't load. Can you provide a working one? Note also that you included two versions of Chart.js (2.9.3 and 2.8.0-RC1) in the codepen and it'd be better to just use the latest to avoid any conflicts

There's not very many commits in 0.7.5, so that should help a lot in narrowing this down. Perhaps it's something related to https://github.com/chartjs/chartjs-plugin-zoom/pull/292

**Comment by jledentu** [comment]
@BlueEther Yeah, your codepen tries to load a CSV file from an URL that doesn't respond. Also, you loaded the chartjs-plugin-zoom library after the Chart.js library. Be sure you load Chart.js before.

**Comment by etimberg** [comment]
I updated the test case to v3, but it still fails due to a CORS issue when trying to load the CSV of data. https://codepen.io/etimberg/pen/ZELwVrq

**Comment by kurkle** [comment]
Closing as Chart.js v2 is no longer in development.
