### ISSUE TITLE
How can i set pan and zoom limits ?

### ISSUE THREAD

**Issue by ivanicharts** [chartjs/chartjs-plugin-zoom#37]
Can I somehow set limit on min and max values on the x axis so user couldn't pan beyond the 0 ?

**Comment by etimberg** [comment]
@ivanicharts this is not yet possible. I'd be happy to merge a PR that adds this functionality

**Comment by ivanicharts** [comment]
@etimberg, thanks, but there are any ways I can do it by myself ?

**Comment by nolanthorn** [comment]
@etimberg I have handled this (for TimeScales, at least, and it doesn't appear to me that the others are any harder), but it seems to me I need to compute the minimum and maximum x and y values from the data each time doPan is called. This is an obvious performance issue on large datasets, so my question is: can I access the minimum and maximum data values for each dataset on a property of the ChartInstance?

If so, I'm happy to try and make a PR for this, it is of fair urgency in a project I'm involved with.

**Comment by etimberg** [comment]
You'd need to modify the functions inhttps://github.com/chartjs/Chart.Zoom.js/blob/master/src/chart.zoom.js such as `zoomNumericalScale` and `zoomIndexScale` to check if the zoom goes over the limits and cap it if it does
