### ISSUE TITLE
Activating zoom after first click

### ISSUE THREAD

**Issue by flaushi** [chartjs/chartjs-plugin-zoom#370]
Is it possible to activate the zoom plugin only after the user clicks the canvas?

I have embedded several graphs in a long page, which has to be scrolled. It happens often that the cursor scrolls over the canvas (unintentionally), and then the next scroll event (mouse wheel) is eaten by the chart (instead of the main document).

I am afraid to destroy the mouse events if just intercepting 
```
$('#canvas').on('click', () => {
    chart.options.plugins.zoom.zoom.enabled = true; 
    chart.update();
});
```

Once zooming and panning is enabled, the click event is needed by the plugin, right?
Related issue: #335

**Comment by cederlof** [comment]
#382 didn't do it for me, I landed on the code provided in OP's post. I also added `tabindex="0"` to the canvas so I could catch the `blur`-event for disabling zoom upon clicking outside of the chart.
