### ISSUE TITLE
Many issues with zoom

### ISSUE THREAD

**Issue by dexion** [chartjs/chartjs-plugin-zoom#371]
I wrote [a gist](https://gist.github.com/dexion/ad3086eb83b8d330101e6c8dbcd90802) from samples which shows some problems:

- zoom with mouse wheel won't work (Chrome 83, FF 77). No one log event in console log
- `pan` event fires in console log meanwhile it was disabled in config (`I was panned`)
- `drag zoom`  works unexpectedly. We can see logs in console (`I'm zooming!!!` and `I was zoomed!!!`) but often chart doesn't redraws and still unzoomed

**Comment by jledentu** [comment]
Hi,

* The zoom with mouse wheel works if you set `drag: false`
* You're right, `onPanComplete` is called even if pan is disabled, don't know if we should remove this behavior
* Zoom is actually happening but `threshold` may be too high. You're using a `category` scale which is probably not the best for your need. You'll get better results with a `time` scale

**Comment by jledentu** [comment]
* #239 is about making able to enable both zoom wheel and drag at the same time
* `onPanComplete` is not called anymore if pan is disabled in latest version (1.0.0-beta.2)
* Zoom on category scale has been improved (#434)

I think we can close this issue

**Comment by kurkle** [comment]
Closing per previous comment
