### ISSUE TITLE
Zoom drag and pan together

### ISSUE THREAD

**Issue by OrenMe** [chartjs/chartjs-plugin-zoom#372]
Is there a way to set zoom on drag and pan together?
I want to have quick orientation by selecting via drag and fine tuning the selection by panning.
Currently if you set both zoom.drag true and pan then you can't pan cause the zoom drag always works.

Can we add like pan on left drag and zoom drag on rightclick drag or wheelclick and drag?

**Comment by flaudanum** [comment]
Actually when I set both, I can zoom by making a drag and drop which defines my zooming area. At the same time dragging translate the view which makes sense as both are triggered by the same mouse event. 

So I asked myself how is it implemented in famous diagram edition software solutions? I had a look on _InkScape_: the drag and drop is set by default for selection and they use window slide bars for translating the view. For instance, in _Yed Graph editor_ they toggle the drag and drop from '_select_' to '_translate view_' with a button in the toolbar. 
So, I guess I'm going to implement something like that.

However, I was surprised that enabling the 'drag zooming' **disables the 'wheel zooming'**.
