### ISSUE TITLE
Add callback for the start of pan/zoom

### ISSUE THREAD

**Issue by Remagpie** [chartjs/chartjs-plugin-zoom#373]
I'm currently working on a component that changes the internal state when the user is panning or zooming.
I implemented it using `onPan` and `onZoom` for now, but it'd be nice if there is an callback that's called only at the start of the panning or zooming just like the `onPanComplete` and `onZoomComplete`.

**Comment by ZaLiTHkA** [comment]
I've been working on a chart myself where `onPanStart` and `onZoomStart` would have been useful.. unfortunately, I'm currently chasing deadlines for this project, so I can't do anything now, but (unless someone else beats me to it) I might just fork this plugin and look at implementing these myself this coming weekend. (:
