### ISSUE TITLE
Compatibility with Chart js 3.0

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-zoom#376]
Do you have any plans to add next version compatible with Chart.Js@next(3.0)?

**Comment by benmccann** [comment]
At some point, but I was probably just going to wait for the final Chart.js 3.0 release

**Comment by entaroadun7** [comment]
Hi @benmccann, 

could you please share your thoughts how long does it take to prepare version compatible with Chart.Js@next(3.0) ? In our project we would like to use the newest chart.js (3.0) with this awesome plugin, but our customer would like to know the release dates ?

**Comment by stockiNail** [comment]
@benmccann I have forked the project and I have planned to work on that next week, if I can finish Intl implementation in my library.
I can try to change it without changing the model, architetture or adding features.
Just a pure porting.
Could you help?
If you are already working in that, I can try to wait for.
Let me know.

**Comment by stockiNail** [comment]
Submitted PR as promsed.
I have tested with CHART.JS dist/master and it should work everything but please have a look.

**Comment by KoalaBear84** [comment]
Thanks! How to use?

https://github.com/chartjs/chartjs-plugin-zoom/pull/390#issuecomment-731737515

**Comment by stockiNail** [comment]
> 
> 
> Thanks! How to use?
> 
> [#390 (comment)](https://github.com/chartjs/chartjs-plugin-zoom/pull/390#issuecomment-731737515)

@KoalaBear84 you don't have to put the `plugin.js` in `<script>` as is. Before you should build it and then take the result of build and put in `<script>`.
This version is not released yet.
Let me add the built plugin (in a zip) here that you can use it (waiting for the release).

[chartjs-plugin-zoom.min.zip](https://github.com/chartjs/chartjs-plugin-zoom/files/5601994/chartjs-plugin-zoom.min.zip)

You have to use the file `chartjs-plugin-zoom.min.js`

**Comment by KoalaBear84** [comment]
Thanks for your quick response. Tried it and it indeed works as expected. Will await the release.
