### ISSUE TITLE
Do not register plugin globally when using module import

### ISSUE THREAD

**Issue by qnp** [chartjs/chartjs-plugin-zoom#377]
When using ES6 style modules (_e.g._ with a module bundler such as webpack), I would expect that when importing the plugin, it would **not** be registered globally to Chart, but instead the choice would be given to the programmer.

For instance, in my implementation with VueJS, I have a vue chart component wrapping Chart.js for which this plugin is activated conditionnaly by a prop. I have several dashboards for which this plugin is not used but doing such imports it is registered to Chart globally. Yet, this plugin is catching any touch events so that the dashboard cannot be scrolled down by a mobile user.

The actual workaround I found is to unregister the plugin right after the import:
```js
import chartJsPluginZoom from 'chartjs-plugin-zoom';
Chart.plugins.unregister(chartJsPluginZoom);
```
and later doing such a thing (simplified for the sake of the example):
```js
props: {
   zoomEnabled: {
      type: Boolean,
      default: false,
   },
},
mounted() {
  this.chart = new Chart(this.$refs.chartCanvas, {
     plugins: this.zoomEnabled ? [chartJsPluginZoom] : []
     ...
  })
}
```
So that the plugin is only registered in the Chart *instance* whenever I need it.

I guess that line should be removed:
https://github.com/chartjs/chartjs-plugin-zoom/blob/17b29b93ac27bfc36a77ed41b7dc263d1a574e01/src/plugin.js#L722

What do you think ?

Best regards

**Comment by etimberg** [comment]
That appears to be the case as of April 25, 2021 in the master branch. https://github.com/chartjs/chartjs-plugin-zoom/blob/78f0386d33d5fd5ff4b46de92f03e4f83b0910a8/src/index.esm.js#L1-L3

**Comment by qnp** [comment]
Awesome. Thanks for the feedback.
