### ISSUE TITLE
Zoom is very slow in ChartJS Zoom Plugin-mode 'x' 

### ISSUE THREAD

**Issue by giaccomgl** [chartjs/chartjs-plugin-zoom#379]
I'm trying to build a webpage with some graphs. In order to get it, I'm using ChartJS. Sometimes can happen there are too many data to see in just one canvas, so I need to use the ChartJS zoom plugin. I install and use it well, unless I have a big problem: Setting the mode as 'x', the zoom applied on canvas is really really slow (even if I put 100000 as speed value). I want to make it faster. How can I solve it? In this codepen you can see better what I mean:
https://codepen.io/giacomo-maraglino/pen/dyMRaRz

**Comment by jepperaskdk** [comment]
Yep, same here. Hardly anything happens when trying to zoom.

**Comment by leon9508** [comment]
hi, giaccomgl, I meet the same problem as you, have you solved it ?

**Comment by leon9508** [comment]
Hi, I have read the source code just now,and know that how to make the zoom's speed of x-axis faster.
![image](https://user-images.githubusercontent.com/25746834/110352066-6ee31380-8070-11eb-924e-b84efff6f6d2.png)
