### ISSUE TITLE
resolveOptions() called before dependent properties are set in beforeInit()

### ISSUE THREAD

**Issue by BarryPSmith** [chartjs/chartjs-plugin-zoom#384]
`resolveOptions` is called early in `beforeInit`.

`resolveOptions` has a section that is responsible for installing listeners, and references `chart.$zoom._*handler` (wheel, mouseMove, etc.) functions. However, the `_*handler` functions are only defined later in `beforeInit`.

This does not apparently cause functional problems because `resolveOptions` is also called by `beforeUpdate`, at which point `beforeInit` has run to completion and it now the `_*handler` functions are available to be assigned properly. However, as currently written it makes the code more difficult to understand and debug.

Possible solutions: add a comment to `resolveOptions` indicating that it is expected to be called before all the handlers have been defined but this is not a problem because it will be called again by `beforeUpdate`, -OR- split it into two methods (e.g. `resolveOptions` and `assignHandlers`) and do not call `assignHandlers` early in `beforeInit`.

**Comment by kurkle** [comment]
This has been fixed by moving the initialization to `start` hook and by other refactoring.
