### ISSUE TITLE
Plugin ignores option changes of pan.threshold and zoom.threshold, 

### ISSUE THREAD

**Issue by BarryPSmith** [chartjs/chartjs-plugin-zoom#385]
The pan threshold is explicitly captured in `beforeInit` on line 447.

The `options` object used to calculated the zoom threshold on line 485 is captured in `beforeInit` on line 446.

It is unclear why these are captured, given the functions elsewhere ensure they use the current options with e.g. line 492 
```
var zoomOptions = chartInstance.$zoom._options.zoom;
```

**Comment by etimberg** [comment]
@kurkle is this still an issue with the work you've done to remove `$zoom`?

**Comment by kurkle** [comment]
Options are captured here:

https://github.com/chartjs/chartjs-plugin-zoom/blob/3b106e1d849af2eb7178248d2475ccd08fab8d92/src/plugin.js#L48-L52

So should not be an issue anymore.

**Comment by etimberg** [comment]
Cool, closing as resolved
