### ISSUE TITLE
Incosistent documentation of directionEnabled, repeated code

### ISSUE THREAD

**Issue by BarryPSmith** [chartjs/chartjs-plugin-zoom#386]
The comment above the definition of the function `directionEnabled` indicates that the parameter `mode` must be  a string, however the code indicates that it will accept a function which returns a string. The only apparent purpose of the `chart` parameter is to be passed to the `mode` function when required.

Functions that call `directionEnabled` always do a check to see if `mode` is a function before calling it. From the documentation this is correct, but from the code this seems unnecessary given that `directionEnabled` does the same check.

Requested change:
Change the code of `directionEnabled` to remove the function check and the `chart` parameter
-OR- 
Change the documentation to reflect that `mode` can be a function, and update the calling functions to remove the function check.

**Comment by kurkle** [comment]
This has been changed in #425
