### ISSUE TITLE
Not working when a time adapter is used

### ISSUE THREAD

**Issue by RobCzikkel** [chartjs/chartjs-plugin-zoom#387]
Hi all,

I have been struggling with this for a while and this is my last resort.

I can't seem to get this plugin working with financial charts at all. I managed to narrow it down to an issue with time adapters as without one a simple line chart seems to work, but as soon as I import a time adapter (as required by financial charts) it stops working. Any known issues with luxon or moment adapters I should be aware of?

I'm clueless at this point.

**Comment by etimberg** [comment]
Do you have a test case that reproduces this? https://jsfiddle.net/tfcqs395/ is an example of working with a time scale in v3 with the moment adapter.

**Comment by kurkle** [comment]
Closing for now. Please re-open if you have the time to create a reproduce for this.
