### ISSUE TITLE
When round is set,  I can not pan the graph to the right.

### ISSUE THREAD

**Issue by Nemurino-kai** [chartjs/chartjs-plugin-zoom#388]
When round is set, the graph's pan cannot be moved to the right.

I created a graph with the following code.
https://codepen.io/nemurino-kai/pen/QWNexKJ?editors=0010
![graph (2)](https://user-images.githubusercontent.com/40136659/95461754-95156200-09b1-11eb-89c6-3474e5a953a6.jpg)

I can pan the graph to the left, but not to the right.
If I don't set round, I can pan it to the right.

How can I pan the graph to the right?

**Comment by kurkle** [comment]
Reproduces with 1.0.0-beta.3: https://codepen.io/kurkle/pen/XWpQKMj
