### ISSUE TITLE
cannot overload the chartjs due to the instance is not cleared

### ISSUE THREAD

**Issue by mithinK** [chartjs/chartjs-plugin-zoom#389]
I think my issue is a known one, whenever load the new data to the canvas, the old charts flash in and out all the time. I tried to clear the chart instance using destroy, clear, but non is working.

when trying to use the destroy, getting an error:

**ERROR TypeError: Cannot read property 'parentNode' of null**

when trying to use the clear:

**NOT Clearing the instance**

**Comment by kurkle** [comment]
No way to help without a reproduce.
