### ISSUE TITLE
Zooming does not respect "minUnit" option for a time axis

### ISSUE THREAD

**Issue by Rollinc2198** [chartjs/chartjs-plugin-zoom#391]
As title says, basically. I am using Date objects for x values, each at an interval of 1 second. I want to limit the x axis ticks to only display the time in seconds or larger. This can easily be accomplished with ChartJS with the following option:
```javascript
options: {
	scales: {
		xAxes: [{
			type: "time",
			time: {
				minUnit: "second"
			}
		}]
	}
}
```
This setting works, as beforehand it would start with milliseconds on the x axis and after it begins with seconds. However, if I scroll in, the x axis units changes back to milliseconds.

Edit:
I've done some more testing, and discovered that zooming seems to replace the xAxes and yAxes objects. This causes me many different issues. I have multiple y axes that are color coded, and when I zoom out it removes my color coding and labels for every y axis! To work around this, I added an onZoom handler that simply replaces the yAxes object and calls update(). This causes my chart to no longer zoom in the y axis. This isn't a huge problem for me, but it's definitely not desirable. I tried solving the issue above by resettings my xAxes object, which then disabled scrolling on my chart entirely. This clued me in on the fact that scrolling must be messing with the x and y axes objects. Is there a workaround I'm missing, or is this a major oversight in the design of this plugin?

Edit 2:
I've managed to make it work by observing the differences between my xAxes/yAxes and the new objects that get set when scrolling. On scroll, I now manually set the xAxes minUnit back to seconds, and for every y axis I reset its color and label. I would still like to see this plugin actually respecting these options when set initially.

**Comment by mepc36** [comment]
Hey @Rollinc2198, I'm having the same exact problem with the chartjs-zoom-plugin right now — do you mind please supplying some of your code so I can learn how you fixed it? That'd be awesome! Specifically, I'm wondering about these parts of your responses:

> I've done some more testing, and discovered that zooming seems to replace the xAxes and yAxes objects. 

In what file and folder does this happen in in the chart-js-zoom dependency?

1. > To work around this, I added an onZoom handler that simply replaces the yAxes object and calls update().
2. > I tried solving the issue above by resettings my xAxes object, which then disabled scrolling on my chart entirely.
3. >  On scroll, I now manually set the xAxes minUnit back to seconds, and for every y axis I reset its color and label.

Would you mind please commenting with these 3 parts of your code when you get a chance? Thanks man!

**Comment by mepc36** [comment]
Here's my solution, for anyone who runs into a similar problem in the future. I define a custom plugin (this was with `react-chartjs-2`), and then pass it in. The stage at which the plugin runs is really important; for me, it had to be 'beforeUpdate'. My own problem was that this zoom plugin's hardcoding of a scale's `max` value was overriding the `suggestedMax` behavior that I need. So, I basically just take the chart's last data point from Redux; take that last data point's x value; see if it's larger or smaller than the max value calculated by zoom; and overwrite it if it is. 

Check it out:

```
import { Bubble } from 'react-chartjs-2'
import 'chartjs-plugin-zoom'

class _DraggableGraph extends GraphInput {
   ...

  render() {
    const {
      chartData
    } = this.props
    const { axisX1Pts } = chartData

    const xValLastDataPt = axisX1Pts.length > 0 && axisX1Pts[axisX1Pts.length - 1].x
    const zoomRangeMax = xValLastDataPt < 12 ? 12 : Math.ceil(xValLastDataPt) + 1

    const data = this.getData()
    const opts = this.getOpts(zoomRangeMax)

    const plugins = [{
      beforeUpdate: (chart) => {
        const chartScales = chart.options && chart.options.scales
        const xAxis = chartScales && chartScales.xAxes[0]
        const lastVal = axisX1Pts[axisX1Pts.length - 1]
        const xLastVal = lastVal && lastVal.x
        const tickMax = xAxis && xAxis.ticks && xAxis.ticks.max
        if (xLastVal && xAxis && xLastVal > tickMax) {
          xAxis.ticks.max = Math.ceil(xLastVal) + 1
        }
      }
    }]

    return (
      <div>
        <Bubble
          height={150}
          data={data}
          options={opts}
          ref={this.chartRef}
          plugins={plugins}
        />
      </div>
    );
  }
}
```

**Comment by etimberg** [comment]
Closing due to lack of test case
