### ISSUE TITLE
Unable to scroll page on mobile phone even after disabling zoom

### ISSUE THREAD

**Issue by Aravindh-SNR** [chartjs/chartjs-plugin-zoom#392]
This is similar to #181 but for mobile phones. Even if zoom is disabled, page scroll does not work on a mobile phone if the scroll gesture is made on the chart area.
I see that fix #254 deals with 'wheel', 'mouseup', 'mousedown' and 'mousemove' events. Can you please include touch events so that this fix works for touch devices also?

**Comment by kurkle** [comment]
Touch events were included in #455
