### ISSUE TITLE
plugin doesn't work when data coming from axios

### ISSUE THREAD

**Issue by ryuchaehwa** [chartjs/chartjs-plugin-zoom#395]
Hello there,

I just couldn't figure it out what's wrong with my setup but seems like your plugin doesn't work when the data coming from axios. I'm sorry that I don't have a jsFiddle for this example but you can simply make your own and test it out or let me know if there's a any free number api that I can make a jsFiddle or test project.

It works with the already setup data.
cheers.

**Comment by benmccann** [comment]
this is not an issue with the plugin, but the way you're using it. I'm sorry, but don't have time to offer support
