### ISSUE TITLE
Disable CTRL+Mouse wheel zoom and disable trackpad zooming

### ISSUE THREAD

**Issue by Jamesking56** [chartjs/chartjs-plugin-zoom#397]
Is there a way using this plugin to disable zooming via keyboard and trackpad? I ideally only want zooming via buttons.

I have already implemented zooming via buttons so I just want to disable the keyboard / mouse zooming

**Comment by kurkle** [comment]
This plugin is actually all about the gesture zooming. I don't think you need this plugin at all for zooming by buttons.
