### ISSUE TITLE
loosing x-axis time parameter since last chartjs update

### ISSUE THREAD

**Issue by scenaristeur** [chartjs/chartjs-plugin-zoom#398]
Hi All, great plugin !!! 
But I've got a chartjs x-scale configured with time like that : 

```
        scales: {
          xAxes: [{
            type: 'time',
            time: {
              unit: 'hour' ,
              displayFormats: {
                hour : 'DD/MM | HH:mm'
              }
            },

```
last week, an npm update upgraded chartjs to : 
(in  package-lock.json)
```
  "chartjs-plugin-zoom": {
      "version": "0.7.7",
}
...
    "vue-chartjs": {
      "version": "3.5.1",
      "resolved": "https://registry.npmjs.org/vue-chartjs/-/vue-chartjs-3.5.1.tgz",
      "integrity": "sha512-foocQbJ7FtveICxb4EV5QuVpo6d8CmZFmAopBppDIGKY+esJV8IJgwmEW0RexQhxqXaL/E1xNURsgFFYyKzS/g==",
      "requires": {
        "@types/chart.js": "^2.7.55"
      }
    },
...
    "chart.js": {
      "version": "2.9.4",
}

```

Now as soon as i drag the mouse to zoom, the x-axis time parameter seems to be lost :

Before zoom : 

![image](https://user-images.githubusercontent.com/4020744/98534645-0e3ff780-2285-11eb-9761-0a9103ccdb6c.png)

As soon as i drag the mouse for zooming

![image](https://user-images.githubusercontent.com/4020744/98535632-b7d3b880-2286-11eb-9524-d51b026bbf8a.png)

This worked OK before the chartjs update (with chartjs 2.9.3). Must charts-plugin-zoom be updated or do i have something to do on my side ? Thxs

**Comment by kbs1** [comment]
Same here with chart.js version 2.9.4. Ticks callback stops getting called and default formatting is used instead.

**Comment by aarbakkeinnovation** [comment]
Same problem here. Changes to default time formatting immediately when i start zooming.

**Comment by kurkle** [comment]
Does not happen with chart.js v3 / zoom beta.2: https://codepen.io/kurkle/pen/QWdPEWP
