### ISSUE TITLE
pan step size config 

### ISSUE THREAD

**Issue by bakkiung** [chartjs/chartjs-plugin-zoom#401]
hi team , thanks for the awesome masterpiece artwork plugin.

is there any chance to provide the step size config option for panning ? 

it will be great if we can control it to pan by exactly one unit (one column) on x axis .

thanks ,.

**Comment by kurkle** [comment]
This would probably be a workaround for the historically poor functionality with category scale. Its been improved lately, and I'm not sure this would be needed anymore.
