### ISSUE TITLE
Points/lines at the bottom of a graph get cut off

### ISSUE THREAD

**Issue by Skuhoo** [chartjs/chartjs-plugin-zoom#41]
Chart.Zoom.js causes the bottom half of points and lines at the bottom of a graph to be cut off.

**Without Chart.Zoom.js:**
![image](https://cloud.githubusercontent.com/assets/20829776/18737288/6a2dfb38-805d-11e6-8643-07f7db24f946.png)

**With Chart.Zoom.js:**
![image](https://cloud.githubusercontent.com/assets/20829776/18737291/7395d8b2-805d-11e6-946a-d0214cadc81b.png)

I understand the reason behind it is so that the points and lines don't overflow the boundaries of the graph, but this is especially annoying if you are only using 'x' panning or drag zooming.

**Comment by etimberg** [comment]
@Skuhoo this is indeed annoying. I don't know what the best solution is. One possibility is to do the clipping on a more complex polygon. Right now we clip on the chart area rectangle. If we project the boundaries of all points onto that rectangle and then generate a polygon for the bounds that we need to draw. This could cause performance problems though

**Comment by rajkumar-osm** [comment]
+ 1
I am also having the same issue.

@Skuhoo - Did you find a work around?

**Comment by benmccann** [comment]
I've just merged a fix for this
