### ISSUE TITLE
Missing type definition (d.ts)  causes incompatibility with Typescript noImplicityAny compiler flag

### ISSUE THREAD

**Issue by BeGj** [chartjs/chartjs-plugin-zoom#417]
Using ZoomPlugin with latest Angular 11 with strict Typescript options.

```
import * as ZoomPlugin from 'chartjs-plugin-zoom;
```

Causes error in vscode and when compiling.
```
Could not find declaration file for module chartjs-plugin-zoom. ..... Implicitly has an 'any' type.
Try `npm install @types/chartjs-plugin-zoom`
```

How do I solve this? Without disabling noImplicityAny flag, or creating a d.ts file manually. Would be nice if a simple type definition was made available. Or if there is any smarter solutions?

**Comment by NickAger** [comment]
I solved with:

```typescript
// @ts-ignore - chartjs-plugin-zoom has no types
import 'chartjs-plugin-zoom'
```
