### ISSUE TITLE
Release a version for chart.js v3

### ISSUE THREAD

**Issue by hellow554** [chartjs/chartjs-plugin-zoom#423]
I would like to see a 0.8.0-alpha.1 (or similar) on npmjs so I can easily use it, instead of manually downloading and including it like https://github.com/chartjs/chartjs-plugin-zoom/issues/376#issuecomment-734198189 suggests.

What are the plans on this?

**Comment by hellow554** [comment]
So, the reason for this is: when I do `npm i git+https://github.com/chartjs/chartjs-plugin-zoom -P`, the folder is empty:

    $ ls node_modules/chartjs-plugin-zoom/
        LICENSE.md  package.json  README.md

that's it. There are no module downloaded, whatsoever. Is there a reason for it? Can this be fixed?

**Comment by hellow554** [comment]
hey @kurkle and @benmccann 
Can you leave a comment on this issue please?

**Comment by jledentu** [comment]
@hellow554 The reason is that the Git repository doesn't contain the `/dist` files. They are dynamically generated by the CI when a version of the npm package is released.

A solution would be to create a pre-release that supports Chart.js v3. I don't know what are the plans about it.

**Comment by kurkle** [comment]
v1.0.0-beta.1 has been released
