### ISSUE TITLE
Zoom time sample is not working

### ISSUE THREAD

**Issue by michael-harley** [chartjs/chartjs-plugin-zoom#424]
Hi, any idea why is this Zoom Time Sample is not working?
I can't seem to scroll with my mouse wheel. Am I missing something?
Sample: https://codesandbox.io/s/young-leftpad-bce7e?file=/index.html

https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html

Thanks!

**Comment by stockiNail** [comment]
@michael-harley I think that the plugin is not loaded.

Line 9 of `index.html` contains:

```html
<script src="../dist/chartjs-plugin-zoom.js"></script>
```

In the sandbox there isn't any file at that location. If you click on the scr url you got:

![bugzoom](https://user-images.githubusercontent.com/11741250/107815159-46b70c00-6d73-11eb-9225-3e111faba867.PNG)

**Comment by stockiNail** [comment]
@michael-harley I have forked and changed my fork. I have loaded the plugin and it works.

https://codesandbox.io/s/immutable-morning-81158?file=/index.html

**Comment by michael-harley** [comment]
Ah, my bad I was not reading the code carefully. Thanks!
