### ISSUE TITLE
Reset Button Created Automatically?

### ISSUE THREAD

**Issue by maxwell-oroark** [chartjs/chartjs-plugin-zoom#430]
The reset button is just added to the DOM under my chartjs canvas auto-magically after I zoom. Is it possible to prevent this behavior and add my own custom reset zoom button and just use the resetZoom function?

**Comment by maxwell-oroark** [comment]
Looking a little bit at the src. Seems like we could modify the `if(!chart.crosshair.button)` logic a bit to allow this:

```
			if (!chart.crosshair.button) {
				// add restore zoom button
				var shouldCreate = this.getOption(chart, 'zoom', 'resetButtonEnabaled')
				if ( shouldCreate ) {
					var button = document.createElement('button');

					var buttonText = this.getOption(chart, 'zoom', 'zoomButtonText');
					var buttonClass = this.getOption(chart, 'zoom', 'zoomButtonClass');
	
					var buttonLabel = document.createTextNode(buttonText);
					button.appendChild(buttonLabel);
					button.className = buttonClass;
					button.addEventListener('click', function() {
						this.resetZoom(chart);
					}.bind(this));
					chart.canvas.parentNode.appendChild(button);
					chart.crosshair.button = button;
				}
			}
```

**Comment by stockiNail** [comment]
@maxwell-oroark forgive my lack of knowledge but I don't understand where the above code is coming.

I doesn't seem part of this plugin. As far as I know, the plugin doesn't add any DOM element automatically.

But maybe I'm wrong.

**Comment by maxwell-oroark** [comment]
Oh whoops. This is apart of the chartjs crosshair plugin which supports zooming. My bad.
