### ISSUE TITLE
Issue with 'xy' zoom in combination with 'horizontalBar'

### ISSUE THREAD

**Issue by angelnikolov** [chartjs/chartjs-plugin-zoom#431]
Basically, I've got a `horizontalBar` chart and want to use a draggable 'xy' zoom with `no panning`.
Here's an example - https://codepen.io/darkysharky/pen/GRNBVWm
Try dragging vertically and see what happens. Horizontal zoom works fine, but vertical doesnt.
Interestingly enough, the issue only occurs when `drag` is set to `true`, but this option is crucial for my project's needs.
I've tried hacking something up by monkey patching the `mouseMoveHandler` so I can get access to the `_dragStart` and capture it and later do custom calculations to figure out the zoom, but they didnt work out nicely.
Let me know if I can assist further.

**Comment by vaasu070** [comment]
@angelnikolov , any progress on this? This feature is critical for my project as well.

**Comment by angelnikolov** [comment]
@vaasu070 Nope, just my hacked version which I explained in the description :)

**Comment by kurkle** [comment]
Works fine with v1.0.0-beta.2: https://codepen.io/kurkle/pen/vYgPRav
