### ISSUE TITLE
resetzoom triggering after drag (beta)

### ISSUE THREAD

**Issue by pgp80** [chartjs/chartjs-plugin-zoom#441]
I'm trying out the betas of both chartjs and zoom, and I'm noticing some behavior which is different from the current versions I have on a project. I have drag zoom enabled and in the current version, it zooms and then I have onClick: resetZoom and it reverts to original form. In the beta, I drag and as soon as I release the mouse the resetZoom occurs immediately (so it doesn't stay zoomed in).  Removing the onClick in the beta does result in a stable zooming. Just thought I'd share!
``  
options: {
  
    
    scales: {
      x: {
      	type: 'time',
          unit: 'hour'
      },//end x
      y: {
        
      }//end y
    },//end scales
     
    plugins: {
      zoom: {
        
        zoom: {
          enabled: true,
          drag: true,
          mode: 'x',
        
        }
      }
    },
    onClick: resetZoom,
 }//end options

![recording (1)](https://user-images.githubusercontent.com/60016497/111176710-f3a5c400-857f-11eb-936a-4881758a1c11.gif)

**Comment by kurkle** [comment]
Thanks for the heads up, I'm guessing it should not call "onClick" when dragging.

**Comment by jledentu** [comment]
@kurkle  I think it's the native behavior to have `mouseup` and `click` events triggered simultaneously, even if `mousemove` events were triggered between the `mousedown` and `mouseup`. I don't know why it worked in previous versions, but I think that a `onClick` callback is expected when a `click` event natively happens, don't you think?

@pgp80 There are some tricks to distinguish quick click and "drag" events: https://stackoverflow.com/questions/6042202/how-to-distinguish-mouse-click-and-drag.

**Comment by pgp80** [comment]
I've been trying the latest betas and the drag still appears to be triggering the onClick: resetZoom on my end. I suppose I can try the tricks per the above, but just figured I'd let you know in case this still isn't intended behavior, thanks!

**Comment by kurkle** [comment]
@pgp80 is your click handler on the chart options or in the canvas element?
