### ISSUE TITLE
Zoom with X axis only never zooms

### ISSUE THREAD

**Issue by Scotsoo** [chartjs/chartjs-plugin-zoom#442]
Ran into a bug where I only want to zoom on the x-axis value, the `onZoom`  and `onZoomComplete` functions both get called, but no zooming actually starts. Codepen here: https://codepen.io/scotsoo/pen/dyNozar

**Versions:**
`chart.js`: `2.9.3`
`chartjs-plugin-zoom`: `^0.7.7`

**Comment by Scotsoo** [comment]
Adding `type: 'time',` to the xAxes made the zoom work, but it's odd that it doesn't work with any xAxes type.

**Comment by etimberg** [comment]
Still an issue with chart.js v3. https://codepen.io/etimberg/pen/MWJLZZz

**Comment by kurkle** [comment]
Looks like this is fixed in beta.2: https://codepen.io/kurkle/pen/JjExxgy
