### ISSUE TITLE
Zoom on desktop horizontal/vertical

### ISSUE THREAD

**Issue by KoalaBear84** [chartjs/chartjs-plugin-zoom#445]
Is there a way to only zoom horizontal or vertical?

Already tried CTRL/ALT/SHIFT, but doesn't seem to be possible.

A nice way would be to be able to zoom by dragging on the scales, like there is in TradingView.com.

**Comment by jledentu** [comment]
You can specify the direction with `mode`:

```
   // Zooming directions. Remove the appropriate direction to disable
   // Eg. 'y' would only allow zooming in the y direction
   // A function that is called as the user is zooming and returns the
   // available directions can also be used:
   //   mode: function({ chart }) {
   //     return 'xy';
   //   },
   mode: 'xy',
```

**Comment by KoalaBear84** [comment]
Thanks @jledentu 

I've made some sort of 'workaround'. Looks like the settings are not applied instantly but require an extra 'scroll' before applied, but good enough for now. Would be nice if this could be implemented by default to make it work instantly/correctly.

```javascript
function processModifierKeys(event) {
	yourchart.config.options.plugins.zoom.zoom.mode = event.shiftKey ? 'x' : (event.ctrlKey ? 'y' : 'xy');
}

document.body.addEventListener('keydown', processModifierKeys);
document.body.addEventListener('keyup', processModifierKeys);
```

If anybody knows a better way, not dependent on the hardcoded chart object, that would be great.

**Comment by jledentu** [comment]
@KoalaBear84 Do you call `chart.update()` after having changed the settings?

**Comment by KoalaBear84** [comment]
OK, no, I didn't. But I know do, and every time it becomes unresponsive, takes full CPU core which is 25% of CPU. When I remove the .update part, it doesn't become unresponsive. Very strange.
