### ISSUE TITLE
Additional event handlers on axes called unexpectedly on zoom/pan

### ISSUE THREAD

**Issue by jbsgh** [chartjs/chartjs-plugin-zoom#448]
I've attached some additional event handler functions to axes:

```
scales: {
	 'x-axis': {
		onMyEvent: function() { console.log('onMyEvent'); }
	 }
}
```

Such handlers are called in onPan, onZoom and other event handlers of the plugin that call storeOriginalOptions(). This function  triggers the call of scriptable options of the axes. In effect, when cloning the options, the event functions are called erroneously because storeOriginalOptions() can't decide whether the functions are event handlers, that should not be called on cloning, or scriptable options, that should be called on cloning.

Versions:
* chartjs 3.1.0
* chartjs-plugin-zoom: github-trunk (1.0.0-beta.1)

**Comment by kurkle** [comment]
Fixed in #452, only `min`/`max` are now read from scale options.
