### ISSUE TITLE
Intervals expand when panning

### ISSUE THREAD

**Issue by SamMcKay** [chartjs/chartjs-plugin-zoom#49]
When panning, the tick intervals expand.  This is most easily reproduced by creating a chart that can pan horizontally and then panning rapidly side to side.  You will notice that the tick intervals expand.  I do not have time to create a pull request and test thoroughly however I can offer the cause of the issue and a potential fix.   

When, for example the panNumericalScale function is called, the following code calculates the bounds variables.

```
function panNumericalScale(scale, delta) {
    var tickOpts = scale.options.ticks;
    var start = scale.start,
        end = scale.end;

    if (tickOpts.reverse) {
        tickOpts.max = scale.getValueForPixel(scale.getPixelForValue(start) - delta);
        tickOpts.min = scale.getValueForPixel(scale.getPixelForValue(end) - delta);
    } else {
        tickOpts.min = scale.getValueForPixel(scale.getPixelForValue(start) - delta);
        tickOpts.max = scale.getValueForPixel(scale.getPixelForValue(end) - delta);
    }
}
```

This issue is quite easily fixed by ensuring the difference between the two bounds values is always the same.

```
function panNumericalScale(scale, delta) {
    var tickOpts = scale.options.ticks;
    var start = scale.start,
        end = scale.end;
    var diff = scale.end - scale.start;

    if (tickOpts.reverse) {
        tickOpts.max = scale.getValueForPixel(scale.getPixelForValue(start) - delta);
        //tickOpts.min = scale.getValueForPixel(scale.getPixelForValue(end) - delta);
       tickOpts.min= tickOpts.max - diff;
    } else {
        tickOpts.min = scale.getValueForPixel(scale.getPixelForValue(start) - delta);
        //tickOpts.max = scale.getValueForPixel(scale.getPixelForValue(end) - delta);
        tickOpts.max = tickOpts.min + diff;
    }
}
```

This fix is obviously simplified for illustrative purposes, but I hope you get the idea.

Sorry I can't be of more help.  Maybe one day when other projects slow down.

As a side note

`Chart.pluginService.register(zoomPlugin);`

does not work with the latest version of chartjs.  Change to

`Chart.plugins.register(zoomPlugin);`

**Comment by etimberg** [comment]
Thats an interesting way to fix it. It would definitely work on the linear scale but I'm not sure about the logarithmic scale.

I'm surprised `Chart.pluginService.register` does not work, the change to `Chart.plugins` was supposed to be backwards compatible

**Comment by adeel3612** [comment]
@SamMcKay i am having same problem and having a hard time in default category scale in x-axis. By panning same issue arise. Intervals between the ticks expands can you help me in this regard because i am beginner and cant seem to understand the code. However i have dig down and pick piece of code which run at the category scale index. 

```
function panIndexScale(scale, delta, panOptions) {
	var labels = scale.chart.data.labels;
	var lastLabelIndex = labels.length - 1;
	var offsetAmt = Math.max((scale.ticks.length - ((scale.options.gridLines.offsetGridLines) ? 0 : 1)), 1);
	var panSpeed = panOptions.speed;
	var minIndex = scale.minIndex;
	var step = Math.round(scale.width / (offsetAmt * panSpeed));
	var maxIndex;

	zoomNS.panCumulativeDelta += delta;

	minIndex = zoomNS.panCumulativeDelta > step ? Math.max(0, minIndex -1) : zoomNS.panCumulativeDelta < -step ? Math.min(lastLabelIndex - offsetAmt + 1, minIndex + 1) : minIndex;
	zoomNS.panCumulativeDelta = minIndex !== scale.minIndex ? 0 : zoomNS.panCumulativeDelta;

	maxIndex = Math.min(lastLabelIndex, minIndex + offsetAmt - 1);

	scale.options.ticks.min = rangeMinLimiter(panOptions, labels[minIndex]);
	scale.options.ticks.max = rangeMaxLimiter(panOptions, labels[maxIndex]);
}
```
