### ISSUE TITLE
zoom mode: "x" drag: true can't work threshold

### ISSUE THREAD

**Issue by yoshimax** [chartjs/chartjs-plugin-zoom#496]
I just click graph select range 0 (+MAX) on zoom mode: "x" drag: true.

Looks mode: "x"
computeDragRect return value no calc always rerurn some value.

It means can't work here.
  if (dragDistanceX <= zoomThreshold && dragDistanceY <= zoomThreshold) {
    return;
  }

Report bug.

-------------------------------------------------------
 zoom: {
              enabled: true,
              drag: true,
              mode: "x",
              threshold: 2,
              onZoomComplete: this.onZoomComplete,
              onZoomStart: this.onZoomStart,
              onZoom: this.onZoom
            },

### mouseUp zoom.js 
chartjs-plugin-zoom.js?f634:462 xEnabled: true
chartjs-plugin-zoom.js?f634:463 yEnabled: false
chartjs-plugin-zoom.js?f634:506 rect.left: 341
chartjs-plugin-zoom.js?f634:507 rect.right: 341
chartjs-plugin-zoom.js?f634:508 rect.top: 32
chartjs-plugin-zoom.js?f634:509 rect.bottom: 286.07365326524837
chartjs-plugin-zoom.js?f634:510 zoomThreshold: 2

chartjs-plugin-zoom.js?f634:511 dragDistanceX: 0
chartjs-plugin-zoom.js?f634:512 dragDistanceY: 254.07365326524837

**Comment by kurkle** [comment]
Some clarification, did you select 0 pixels wide area, or did you select whole chart and it calculated the area to be 0 pixels wide?

**Comment by kurkle** [comment]
If I understand correctly, you just clicked and it selected a 0 wide area. Did it also zoom to that?

**Comment by yoshimax** [comment]
Yes, Just click (not drug) also Zoom.

Just one click  dragDistanceY  always return large value .

Will can't work here.
if (dragDistanceX <= zoomThreshold && dragDistanceY <= zoomThreshold) {
    return;
  }
