### ISSUE TITLE
Zoom Bug when only x axis

### ISSUE THREAD

**Issue by titipignataro** [chartjs/chartjs-plugin-zoom#511]
Hello,
Im using this library and I have noticed that if I use this demo https://www.chartjs.org/chartjs-plugin-zoom/samples/drag/time.html with time scale and zoom only on x axis the click event goes to empty area of the chart. Does someone knows how to fix that ? thanks in advance

**Comment by kurkle** [comment]
"click event goes to empty area of the chart", meaning you can zoom from the empty area? or you click on some other area and the click event goes somewhere else? Can you create a fiddle to reproduce?

**Comment by titipignataro** [comment]
> "click event goes to empty area of the chart", meaning you can zoom from the empty area? or you click on some other area and the click event goes somewhere else? Can you create a fiddle to reproduce?

![Zoom Bug when only x axis](https://user-images.githubusercontent.com/19999197/118381262-8209e680-b5bf-11eb-9ed2-f40321cdeaca.gif)

**Comment by titipignataro** [comment]
Thank you sou much for the quick fix
When can I get the corrected version ? Im using stacked bar with only x axis zoom and time scale and is still not working

**Comment by kurkle** [comment]
We've just released v1.0.0-rc, which includes this fix. Take a look at the release notes though, because there are breaking changes:
https://github.com/chartjs/chartjs-plugin-zoom/releases/tag/v1.0.0-rc
