### ISSUE TITLE
BUG : Plugin not working with Chart JS 3.2.1 - Cannot read property 'plugins' of undefined

### ISSUE THREAD

**Issue by sushmit-telaverge** [chartjs/chartjs-plugin-zoom#517]
![image](https://user-images.githubusercontent.com/77407027/118934519-12517e00-b968-11eb-8225-8061d436ff69.png)

import zoomPlugin from 'chartjs-plugin-zoom';

-- issue : 
Could not find a declaration file for module 'chartjs-plugin-zoom'. '/home/sushmit/Documents/resi-may/control/web/node_modules/chartjs-plugin-zoom/dist/chartjs-plugin-zoom.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/chartjs-plugin-zoom` if it exists or add a new declaration (.d.ts) file containing `declare module 'chartjs-plugin-zoom';`ts(7016)

Chart.register(zoomPlugin);

`    plugins: {
      zoom: {
        zoom: {
          wheel: {
            enabled: true,
          },
          pinch: {
            enabled: true
          },
          mode: 'x',
        }
      },
},`

**Comment by kurkle** [comment]
0.7.7 is for chart.js v2. v1.0.0-rc works for v3.

**Comment by kurkle** [comment]
Duplicate of #491
