### ISSUE TITLE
Using zoom and pan events to trigger zoom and pan of another component

### ISSUE THREAD

**Issue by sabres207** [chartjs/chartjs-plugin-zoom#521]
Hi all,
I'm trying to achieve a functionality of some other component we use inside our company to be able to get zoomed and panned upon events fired by chart js zoom plugin.

For example the event:
onZoom: chart => { // do something }

I tried to figure out how the zoom state of the chart is represented in the chart argument that is sent to the onZoom callback, but I couldnt find anything special representing where on the chart am I in right now.
What I expected to see is something like the points of the dataset that are visible at the moment, or some kind of coordinates or the exact percentage of the start and end point that is visible at the moment.

Would appreciate any help. Thanks!

**Comment by kurkle** [comment]
You can check the scale min/max values to see what range is visible. Would that help?
