### ISSUE TITLE
Setting drag threshold greater than 0 disables legend events

### ISSUE THREAD

**Issue by aanilyildiz** [chartjs/chartjs-plugin-zoom#525]
When I set the drag threshold anything other than 0 the toggle functionality of the legend buttons become disabled. The strange thing is it doesn't happen all the time, I can sometimes use the legend without any problems but sometimes I cannot.

**Comment by pmbert** [comment]
I have a similar problem:
- the legend buttons become not operable anymore
- the tooltip box freezes if displayed
- moving is still possible

But in my opinion (I'm not quite sure) it happens when panning around.
It happens sporadically, but very often.  I wasn't able yet to reproduce it.
I haven't set any threshold.
Sometimes the problem solves itself after heavy clicking. But I don't know why.
Zoom plugins 1.0.0 for chart.js versions > 3.0.0

**Comment by aanilyildiz** [comment]
> I have a similar problem:
> 
> * the legend buttons become not operable anymore
> * the tooltip box freezes if displayed
> * moving is still possible
> 
> But in my opinion (I'm not quite sure) it happens when panning around.
> It happens sporadically, but very often. I wasn't able yet to reproduce it.
> I haven't set any threshold.
> Sometimes the problem solves itself after heavy clicking. But I don't know why.
> Zoom plugins 1.0.0 for chart.js versions > 3.0.0

I forgot to mention that I too am using the 1.0.0 version of the plugin. Refreshing the page sometimes helps but not always. In my situation disabling the threshold altogether fixes the bug so I'm thinking it might be the cause of my issue. Not sure why your problem happens. Maybe the zoom plugin events override chart.js events?

**Comment by kurkle** [comment]
Sounds like a bug where the "dragging" state is true when it should not be.

**Comment by pmbert** [comment]
> Sometimes the problem solves itself after heavy clicking. But I don't know why.

After some reflection I'm not sure anymore, that it solves itself, because I have an automatic update function.
Probably in all cases a new start  with browser update is necessary.

**Comment by pmbert** [comment]
To be on the safe side, here is my configuration:

<//plugin chartjs-plugin-zoom:
zoom: {
    zoom: {
        wheel: { enabled: true, },
        pinch: { enabled: true },
        drag: { enabled: true, },
        mode: 'x',
        onZoomStart: function(x, y, data) { console.log(...); },
        onZoomComplete: function(x, y, data) { console.log(...); }
    },
    pan: {      
        enabled: true,
        mode: 'x',
        modifierKey: 'ctrl',
        onPanStart: function(x, y, data) { console.log(...); },
        onPanComplete: function(x, y, data) { console.log(...); }
    }
},  //zoom
>

**Comment by kurkle** [comment]
@pmbert if you comment out the events doing `console.log`, does that have any effect? (just narrowing it down)

**Comment by pmbert** [comment]
I will try that.

**Comment by kurkle** [comment]
> <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@next"></script>

You should actually use latest, we have a official release now. @next is still the 1.0.0-rc. Should remove that tag (cc @etimberg)

**Comment by pmbert** [comment]
> You should actually use latest, we have a official release now. `@next` is still the 1.0.0-rc. Should remove that tag (cc @etimberg)

I'm not familiar with that. I wanted to get always the latest version as long as the development continues.
Without this tag I'm getting always the correct version?

**Comment by pmbert** [comment]
> @pmbert if you comment out the events doing `console.log`, does that have any effect? (just narrowing it down)

I've done now:
- removed the @next tag
- commented out all functions on...Start and on...Complete
- cleared browsers cache

The problem stays as before.
But now I can reproduce it:
- start chart
- display a tooltip box
- with ctrl+mouse move the chart from one side of the box to the other and vice versa
- let ctrl key but still moving the mouse from one side to the other

Now there's the freeze.
