### ISSUE TITLE
Pan is not working for Bar Chart, Zoom is however.

### ISSUE THREAD

**Issue by bmomen** [chartjs/chartjs-plugin-zoom#53]
My barchart uses the chartjs-zoom plugin, however only the zoom functionality works. 

`$(document).ready(function () {
                    $.getJSON(
                        "@Url.Action("GetData")",
                        function (data) {
                            BarChart(data);
                        });
                });

                function BarChart(data) {
                    var barChartData = {
                        labels: data.Month,
                        datasets: [
                            {
                                label: 'Weight (kg)',
                                fillColor: "rgba(220,220,220,0.5)",
                                backgroundColor: "rgba(46, 44, 211, 0.7)",
                                highlightFill: "rgba(220,220,220,0.75)",
                                highlightStroke: "rgba(220,220,220,1)",
                                data: data.Weight
                            },
                            {
                                label: 'Steps',
                                fillColor: "rgba(0,0,0,0.5)",
                                backgroundColor: "rgba(215, 44, 44, 0.7)",
                                highlightFill: "rgba(0,0,0,0.5)",
                                highlightStroke: "rgba(0,0,0,0.5)",
                                data: data.Steps
                            }
                        ]

                    }
                    var ctx = document.getElementById("barchart").getContext("2d");
                    window.myBar =new Chart(ctx, {
                        type: 'bar',
                        data: barChartData,
                        options: {
                            pan: {
                                enabled: true,
                                mode: 'xy',
                                speed: 10,
                                threshold: 10
                            },
                            zoom: {
                                enabled: true,
                                mode: 'xy',
                                limits: {
                                    max: 1000,
                                    min: 0.5
                                }
                            },
                            responsive: true,
                            tooltips: {
                                callbacks: {
                                    afterLabel: function (e) { return "Owner: " + data.User[e.index] }
                                }
                            },
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: true
                                    }
                                }]
                            }
                        }
                    });
                    
                }`

I have included:
    Script.Require("ChartJS");
    Script.Require("ChartJSZoom");
    Script.Require("Hammer");
and these requires contain the mins and regular packages for ChartJS, ChartJSZoom and Hammer.

The barchart is in the canvas:
`<div id="container" style="width:1100px; overflow-x:scroll;">
                <canvas id="barchart"></canvas>
            </div>`
Some insight into why this isn't working would be great, I have tried to use the codepen example as a starting point (however the pan doesn't work on that either for me!?):  http://codepen.io/anon/pen/PGabEK

The documentation is unfortunately unable to help with this issue also.

Thanks to anyone who can help, I would just like basic horizontal panning, XY panning would just be a bonus :)

**Comment by bravenewworlds** [comment]
The codepen example is not working for me too.

**Comment by mathschy** [comment]
Same here, the pan doesn't work neither on codepen. (chrome Version 53.0.2785.116 (64-bit))

**Comment by shraddha30** [comment]
Zoom and pan both not working for me. (for line chart)
I'm using ```    "chart.js": "^2.4.0",
    "chartjs-plugin-zoom": "^0.4.4",
    "react-chartjs-2": "^1.5.1", ```

and using the same options as 

http://codepen.io/anon/pen/MbGMLX

Any help is appreciated! Do I need to include hammerjs as well?

**Comment by etimberg** [comment]
@shraddha30 you should include hammerjs

**Comment by shraddha30** [comment]
@etimberg, got zoom to work :), pan is still not working for line charts.

**Comment by electricBonfire** [comment]
+1 pan does not work

**Comment by compwright** [comment]
This could be because your scales are not both linear. Support for other scale types is buggy in these plugins.

**Comment by MickyCar** [comment]
For all those having issues with the Pan feature, I solved it on my side by manually downloading HammerJS (link on the project's page) and adding a reference to it BEFORE the chartjs-plugin-zoom.js reference.

`<script src="hammer.min.js"></script>
		<script src="chartjs-plugin-zoom.js"></script>`

Cheers

**Comment by MickyCar** [comment]
Here is an updated pen with HammerJS included :)
http://codepen.io/anon/pen/Grpxoo

**Comment by kitsunekyo** [comment]
both zoom and pan are extremely buggy and unresponsive unfortunately which make them unusable in any project

**Comment by simonl65** [comment]
I can confirm that you need to add a reference to hammerjs BEFORE the chartjs-plugin-zoom.js

**Comment by b-and-p** [comment]
The issue with pan not working persists with Chart.js v2.7.1 Including hammer.js does fix this.

**Comment by etimberg** [comment]
Pan for bar charts is working. See https://www.chartjs.org/chartjs-plugin-zoom/samples/bar.html

**Comment by Mathieu-DA** [comment]
I'm facing the issue with pan not working with a "time" (x) / "linear" (y) line chart

**Comment by Mathieu-DA** [comment]
Ok, I figured it out. I'm using charts (v3) in Angular (with the angular wrapper). I ended up adding an *ngIf on the canvas tag to check if chartData was defined (there's some classic asynchronous stuff going on before I actually get the data). This would have been a logical thing to do from the get-go...
What's weird is that the chart was being generated **without** the ngIf, and even the zoom was working but **not** the pan.
Sorry for having bothered you about this. Maybe this can be of help to someone who would forget to check if the data is actually there before generating the chart

**Comment by stefann01** [comment]
> Pan for bar charts is working. See https://www.chartjs.org/chartjs-plugin-zoom/samples/bar.html

This page give 404

**Comment by dastoyan** [comment]
import zoomPlugin from 'chartjs-plugin-zoom';
  constructor() { 
    Chart.register(...registerables,zoomPlugin);
  }

**Comment by elitwilliams** [comment]
Ok, for clarity - the order should be:

1) chart.js
2) hammer.js
3) chartjs-plugin

This works (via CDN):

`
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0"></script>`

**Comment by OmkarModak** [comment]
> Ok, for clarity - the order should be:
> 
> 1. chart.js
> 2. hammer.js
> 3. chartjs-plugin-zoom
> 
> This works (via CDN):
> 
> ```
> 
> <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0"></script>
> 
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
> 
> 
> <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0"></script>
> ```

this works with below functions:
 plugins: {
          zoom: {
            zoom: {
              wheel: {
                enabled: true,
              },
              mode: 'x',
            },
            pan: {
              enabled: true,
              mode: 'x',
            }
          }
        }
