### ISSUE TITLE
Panning line charts does not work well in x axis

### ISSUE THREAD

**Issue by Tesla2k** [chartjs/chartjs-plugin-zoom#537]
When trying to pan a line chart in the x axis, the behavior is not as excepted.
It only snaps on given data points of the x axis, what I except would be smooth panning like in the y axis

Here is an [example](http://jsfiddle.net/Tesla2k/n15aqh93/1)

Here is the code:
```
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [0,1,2,3,4,5,7,8,9,10,11],
        datasets: [{            
            data: [1,2,3,4,4,6,3,2,1,0,3],
            borderColor: 'rgb(255,0,0)',
            fill:false,
            
        }]
    },
    options: {              
        pan: {            
            enabled: true,            
            mode: 'xy',                    
        },

        // Container for zoom options
        zoom: {            
            enabled: true,						            
            mode: 'xy',
        }
    }
});
```

**Comment by kurkle** [comment]
That depends on the scale type. Your example is using Chart.Zoom.js 0.3.0, which is not supported.

Using recent versions and `linear` x-axis: https://jsfiddle.net/fhas0trc/

**Comment by Tesla2k** [comment]
Thank you, now it works!
