### ISSUE TITLE
.destroy() method broken

### ISSUE THREAD

**Issue by tyrex1975** [chartjs/chartjs-plugin-zoom#54]
Hi,

I'm getting a "Uncaught TypeError: Cannot read property 'canvas' of null" when using the .destroy() method in Chart JS with the Zoom plug-in loaded.

The error comes from the first line of the destroy() method in chartjs-plugin-zoom.js, which has this code:

`var node = chartInstance.chart.ctx.canvas;`

Looking at the file core.controller.js of the main Chart JS, I can see the following code inside the destroy method:

`if (canvas) {`
`	helpers.unbindEvents(me, me.events);`
`	helpers.removeResizeListener(canvas.parentNode);`
`	helpers.clear(me.chart);`
`	releaseCanvas(canvas);`
`	me.chart.canvas = null;`
`	me.chart.ctx = null;`
`}`

`Chart.plugins.notify('destroy', [me]);`

Given that me.chart.ctx is nullified prior to the plugins being notified, this would seem to prevent the first line of destroy() in chartjs-plugin-zoom ever succeeding. Or am I misreading the code?

TIA :-)

**Comment by compwright** [comment]
+1

**Comment by compwright** [comment]
Fixed in v0.4.1

**Comment by tyrex1975** [comment]
Thank you very much!
