### ISSUE TITLE
Uncaught TypeError: Cannot read property 'HALF_PI' of undefined

### ISSUE THREAD

**Issue by ShivamJoker** [chartjs/chartjs-plugin-zoom#545]
Can anyone help me with this I am using snowpack as bundler and react-chartjs-2
```json
    "react-chartjs-2": "^3.0.3",
    "chart.js": "^3.3.2",
    "chartjs-plugin-zoom": "^1.0.1",
```

![image](https://user-images.githubusercontent.com/23727670/122216233-c5f75080-cec9-11eb-8be9-13079f416c7e.png)

I start getting this error once I import the zoom plugin.
```js
import * as zoomPlugin from 'chartjs-plugin-zoom';
```

**Comment by t-animal** [comment]
I assume this is a problem of snowpack, because with an older version of snowpack the plugin works just fine. I also came across this problem when upgrading snowpack from 2.10.1 to current and decided to not upgrade.

**Comment by t-animal** [comment]
Maybe this helps you for now: https://github.com/snowpackjs/snowpack/discussions/1856#discussioncomment-809593

**Comment by kurkle** [comment]
Not an issue with this plugin, there is not reference to `HALF_PI` at all.
