### ISSUE TITLE
Documentation doesn't match released versions ('original' axis limit missing)

### ISSUE THREAD

**Issue by t-animal** [chartjs/chartjs-plugin-zoom#546]
When I go to https://www.chartjs.org/chartjs-plugin-zoom/ and click on "get started" it takes me to a version of the documentation that doesn't match what I get when installing the package from npm. I noticed this, because I need the "original" setting for the axis limits and it's documented but not yet released.

I assume the documentation was build from master but the commit with the setting was introced after the release but before the documentation was built.

**Comment by kurkle** [comment]
True, the documentation is (currently at least) build after each commit to master and we do not have docs for previous versions.

**Comment by kurkle** [comment]
Documentation versioning implemented in #596
