### ISSUE TITLE
Independent limits for pan and zoom

### ISSUE THREAD

**Issue by nullnullend** [chartjs/chartjs-plugin-zoom#551]
Version: 1.0.1. 

Can I somehow set independent limits for pan and zoom?

Something like this:
```js
pan: {
  enabled: true,
  mode: 'x',
  limits: {
    x: {
      min: max_date,
      max: max_date,
    }
  },
},
zoom: {
  wheel: {
    enabled: true,
  },
  mode: 'x',
  limits: {
    x: {
      min: max_date - 10,
      max: max_date,
    }
  },
},
```

**Comment by kurkle** [comment]
I'm curious about the use case? 

I'm thinking you might be looking for the `minRange` option that can be used to limit the zoom range (max-min).

**Comment by kurkle** [comment]
No input, closing
