### ISSUE TITLE
Pan animation with category axis? 

### ISSUE THREAD

**Issue by gterras** [chartjs/chartjs-plugin-zoom#570]
Hi, 

Most of axis types seem to trigger animation on pan except `type: 'category'`. I suppose this is due to `getValueForPixel()` returning the index of the column. Is there a convenient way to get a smooth animation on pan?

**Comment by kurkle** [comment]
That would require changes to the scale, because it rounds the min/max values to whole numbers.

**Comment by gterras** [comment]
Thanks for your answer so I don't get if that's possible or not?

**Comment by kurkle** [comment]
Everything is possible. But it might be easier to use linear scale with cuatom ticks instead.
