### ISSUE TITLE
Cannot read property 'merge' of undefined

### ISSUE THREAD

**Issue by arniepeloton** [chartjs/chartjs-plugin-zoom#572]
![image](https://user-images.githubusercontent.com/63336117/125718275-c2c36ffb-a076-4103-9a35-09203a3f41d2.png)

Hello! Can someone help me about the chartjs plugin datalabels? I got this error (see pic above).

![image](https://user-images.githubusercontent.com/63336117/125718841-e84ab591-21ce-462d-afb1-54a2a6f0e874.png)

And this is how I called the js files (see pic above)

My chart.js version is 3.4.1 while the datalabels version is 2.0.0.

**Comment by jledentu** [comment]
Hi @arniepeloton, I think you should post this issue in the [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) project.
