### ISSUE TITLE
UI Glitch when hiding/showing series while this plugin is enabled

### ISSUE THREAD

**Issue by philfontaine** [chartjs/chartjs-plugin-zoom#573]
The problem only occurs when this plugin is enabled. When we click on a dataset in the legend to hide it, then click again to show it **while it was still animating** there is a small UI glitch that happens. For a split second, the dataset is completely shown, and then it starts its animation from hidden to shown.

![recording](https://user-images.githubusercontent.com/16233697/126701620-9f3066bf-6e6e-4589-9158-b9e6dab86ef8.gif)

It's not very obvious from the GIF, but it is easy to notice when you run the code pen yourself.

https://codepen.io/philfontaine/pen/VwbMNMv

**Comment by kurkle** [comment]
This was fixed by #772
