### ISSUE TITLE
Documentation: Update to VuePress v2

### ISSUE THREAD

**Issue by Mastercuber** [chartjs/chartjs-plugin-zoom#581]
For comfortable reasons it would be great to detect, and then refresh the page, history changes in the documentation.

Example: 
When I am [here (Options)](https://www.chartjs.org/chartjs-plugin-zoom/guide/options.html) and go to [here (Otpions#zoom)](https://www.chartjs.org/chartjs-plugin-zoom/guide/options.html#zoom) and then want back again to Options with the browser back button or a back button on the mouse, I still be at Options#zoom.

**Comment by kurkle** [comment]
Will look into upgrading, when there is a stable release of vuepress 2

**Comment by kurkle** [comment]
Does not look like VuePress v2 will fly.
