### ISSUE TITLE
Error when installing?

### ISSUE THREAD

**Issue by jaminroe** [chartjs/chartjs-plugin-zoom#59]
![image](https://cloud.githubusercontent.com/assets/1559447/21900212/0891a656-d8c1-11e6-9b6f-9bd09772d247.png)

I'm kind of a beginner still to npm, gulp, etc. I'm getting this warning when installing this plug-in via npm. Ideas/comments? Thanks!

**Comment by compwright** [comment]
Run `npm init` to create a package.json file.

**Comment by jaminroe** [comment]
Ah yes, I did come across that. I thought because I had downloaded/installed the plug-in, it included the package.json file from this repo. Thanks!
