### ISSUE TITLE
Zooming in X-axis 

### ISSUE THREAD

**Issue by Poufy** [chartjs/chartjs-plugin-zoom#590]
I have the graph here 
![image](https://user-images.githubusercontent.com/35203098/137823369-6820aad1-b481-4c8a-b794-cfa0fffeae20.png)
and here is my config

```js
 predictionsChartOptions: {
        responsive: true,
        maintainAspectRatio: false,
        zoom: {
            enabled: true,
            drag: {
                enabled: true,
                backgroundColor: "rgb(138, 33, 84, 0.3)",
                borderColor: "rgb(138, 33, 84, 0.3)",
            },
            modifierKey: "shift",
            sensitivity: 0.5,
            mode: "x",
        },
        title: {
            display: true,
            text: 'Prediction Values'
        },
        scales: {
            xAxes: [
                {
                    ticks: {
                        display: true,
                    },
                },
            ],
        },
        transitions: {
            zoom: {
                animation: {
                    duration: 1000,
                    easing: "easeOutCubic",
                },
            },
        },
    },
```
The zooming does not work unless I choose the xAxes type as "time", however, my x-axis labels don't really represent time. They go from 0 to 16 in 0.03 intervals. What are my options here to get it working? When I pick the type to be time all the data points clump together like so:

![image](https://user-images.githubusercontent.com/35203098/137823638-09d4d4d4-3ee5-443b-bcd6-efdd2ae4a90e.png)

I would appreciate help with this!

**Comment by kurkle** [comment]
You could perhaps try linear x-axis?

**Comment by kurkle** [comment]
No input, closing
