### ISSUE TITLE
Line Chart zoomed to max when panning

### ISSUE THREAD

**Issue by KumG** [chartjs/chartjs-plugin-zoom#60]
Hello,

Here's an example : 

http://codepen.io/anon/pen/QdGvmV

Like you can see, when panning, the zoom is automatically set to max. (even if I disable zooming).

Is this a bug or am I missing something ?

Thanks

**Comment by rupalpatel0008** [comment]
Same thing is happening with me. Although I am facing this in ionic 2 project

**Comment by compwright** [comment]
The CodePen was acting pretty wonky, possibly due to Hammer.js not loading correctly (URL was http, not https). This one loads correctly: http://codepen.io/compwright/pen/YVRrqw

It appears this is due to using text labels rather than a numeric x-axis.

**Comment by SimplyCorey** [comment]
@compwright The last one has the same wonky behavior for me when trying to pan.  It zooms in all of the way.  On Chrome 58

**Comment by mazlixek** [comment]
Same here, but with bar chart it works correctly...

**Comment by ray558899** [comment]
I have encountered the same problem, but I bypassed the problem (Only for use, but the real problem is not resolved). I use of "combo-bar-line" source code, the data set inside insert empty bar type values, and insert real line type values, You can it works correctly. ( if you can not work, please input utils.js )
example : 
var chartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [{
                type: 'line',
                label: 'Dataset 1',
                borderColor: window.chartColors.blue,
                borderWidth: 2,
                fill: false,
                data: [1,2,3,4,5,6,7]
            }, {
                type: 'bar',
                label: 'Dataset 3',
                backgroundColor: window.chartColors.green,
                data: []
            }]
        };

**Comment by mdiokwe** [comment]
I don't know if this will work for you but I resolved this issue for me by modifying the following line in function panIndexScale(scale, delta, panOptions)

var offsetAmt = Math.max((scale.ticks.length - ((scale.options.gridLines.offsetGridLines) ? 0 : 1)), 1);
to
var offsetAmt = Math.max(scale.ticks.length, 1);

Very minimal testing, but you can give it a shot.

**Comment by ray558899** [comment]
@mdiokwe  It's working for me , thanks .

**Comment by JeongYoungHo** [comment]
@mdiokwe  thanks

**Comment by prabodh1194** [comment]
Hi,
If it matters, I made a simple bar chart & have confirmed that this works.
It'll be great if we can proceed with the merge.

**Comment by chrishamm** [comment]
Is there any update on this? At present panning is completely broken when using this plugin.
