### ISSUE TITLE
Y scale automatic range changes in a way that leaves the line off the chart

### ISSUE THREAD

**Issue by JanisE** [chartjs/chartjs-plugin-zoom#607]
I'm using pan and zoom `mode: 'x'`, my `scales` options for x is `type: 'time'` and for y is `beginAtZero: true`.

If we assume this as the starting point:
![attels](https://user-images.githubusercontent.com/1469104/146381441-3f3c5c0b-f128-4344-b9af-b99736ae680a.png)

And now drag it a bit to the left so the first two data points go out of the graph, we get this result:
![attels](https://user-images.githubusercontent.com/1469104/146381584-f1495636-778e-42be-bd99-4cb1521c1279.png)

The line up to the third (now first) data point is invisible, above the chart.

I'm testing with `stepped: true`, but I saw the same problem if not stepped.

**Comment by kurkle** [comment]
This is is a chart.js issue: https://github.com/chartjs/Chart.js/issues/9564
