### ISSUE TITLE
Calling .resetZoom() on a chart destroys all metadata, losing more metadata than necessary in the process

### ISSUE THREAD

**Issue by AlbinoDrought** [chartjs/chartjs-plugin-zoom#61]
When a user clicks a "legend square" to hide a line on the chart, ChartJS stores this in the metadata of the dataset.

When resetZoom() is called on a chart, it deletes all metadata. This causes, among other things, for the hidden metadata to be lost and the line to become visible again.

Example: http://codepen.io/albinodrought/pen/OWzqzY

### To Reproduce:
1. Hide a dataset by clicking on the legend "square"
2. Click the "Reset Zoom" link
3. Notice that the dataset hidden in step 1 is now visible again

**Comment by AlbinoDrought** [comment]
I did some fiddling and noticed if I comment out the call that nulls metadata, this issue no longer occurs.

That call is the only part of the code I can see that directly accesses the metadata. I'm not sure of ChartJS internals, though, so there could be something going on in the background (possibly related to hiding/slicing of datapoints?).

**Comment by mkoutli** [comment]
Hello, where did you comment out the call that nulls metadata? And have you faced problems since _meta was not cleared anymore?

**Comment by AlbinoDrought** [comment]
@mkoutli https://github.com/chartjs/chartjs-plugin-zoom/blob/master/src/chart.zoom.js#L307
