### ISSUE TITLE
pan not working on chatjs 3.6 (>3) with time scale in line chart.

### ISSUE THREAD

**Issue by sajanraj** [chartjs/chartjs-plugin-zoom#613]
Dependencies

cahtjs 3.6.0
hammer 2.0.8
momment js 2.29.1

'''
   var line_chart = new Chart(document.getElementById("line-chart"),{
      type: 'line',
      data: exdata_entry,
      options: {
        responsive: true,
        title: {
          display: true,
          text: 'station'
      },
        plugins: {
					zoom: {
            limits: {
              x: {min: 0,  minRange: 50},
              y: {min: 0,  minRange: 50}
            },
            pan: {
              enabled: true,
              mode: 'xy',
              modifierKey: 'ctrl'
            },
						zoom: {
							// enabled: true,
							drag: dragOptions,
							mode: 'xy',
							// speed: 0.005,
              pinch: {
                enabled: true
              },
              onZoomComplete({chart}) {
                // This update is needed to display up to date zoom level in the title.
                // Without this, previous zoom level is displayed.
                // The reason is: title uses the same beforeUpdate hook, and is evaluated before zoom.
                chart.update('none');
              }   
						}
					}
				},
        scales: {
					x: {
						type: 'time',
						time: {
						        unit: 'day',
						        // unitStepSize: 1,
						        displayFormats: {
						           'day': 'yyyy-MM-dd'
						        }
						},
						scaleLabel: {
							display: true,
							labelString: 'Date'
						},
						ticks: {
							maxRotation: 45
						}
					},
					y: {
						scaleLabel: {
							display: true,
							labelString: 'value'
						}
					}      
				}
      }
'''

**Comment by kurkle** [comment]
Works fine: https://www.chartjs.org/chartjs-plugin-zoom/latest/samples/wheel/time.html

If you however have a specific issue, please describe it and create an codepen or equivalent that reproduces it.

**Comment by sajanraj** [comment]
Fixed - problem caused by the order of scirpt inserted. hammer comes fist, after that chatjs-plugin-zoom inserted.
[https://jsfiddle.net/o0Lsr53v/1/](url)
