### ISSUE TITLE
onZoomStart is not called when using zoom via pinch on mobile.

### ISSUE THREAD

**Issue by airwalk741** [chartjs/chartjs-plugin-zoom#631]
onZoomStart is not called when using zoom via pinch on mobile_web.

OnZoomStart is called when zooming with the mouse wheel, but not when using pinch on mobile_web.

https://codesandbox.io/s/vue-chart-3-chart-js-issue-template-forked-ce6dtz?file=/src/App.vue

("zoom start" warning window does not appear)

**Comment by Isaac96SM** [comment]
I'm also having this issue. Is it planned to be solved soon?

**Comment by kurkle** [comment]
Fixed by #810
