### ISSUE TITLE
Not working with Browserify

### ISSUE THREAD

**Issue by rico345100** [chartjs/chartjs-plugin-zoom#65]
I don't think that it causes from Browserify, it causes from somewhere it didn't connected with Chart.js, anyway this is my code:

```javascript
import React, { Component, PropTypes } from 'react';
import Chart from 'chart.js/src/chart';
import 'hammerjs';
import 'chartjs-plugin-zoom';

...

const chartOptions = {
	responsive: true,
	maintainAspectRatio: false,
	type: 'line',
	backgroundColor: '#5092ce',
	data: { ... },
	options: {
		scales: {
			yAxes: [{
				ticks: {
					min: 0
				}
			}]
		},
		pan: {
			enabled: true,
			mode: 'xy',
			speed: 10,
			threshold: 10
		},
		zoom: {
			enabled: true,
			mode: 'y',
			limits: {
				max: 10,
				min: 0.5
			}
		}
	}
};

class GraphChart extends Component {
	...
	updateChart = async () => {
		const context = this.refs.chart.getContext('2d');
		const chart = new Chart(context, chartOptions);
	}
	render() {
		return (
			<div className="chart">
				<canvas ref="chart"></canvas>
			</div>
		);
	}
}
```

Chart.js itself working good, but when I try zoom, it just zoom the screen, not the chart! I checked hammer.js and chartjs-plugin-zoom modules were loaded, but it just not worked.

I tried with different types of chart, like 'bar', it wasn't worked at all. Also documentation is too lack of informations, you better to add some more information like collaborate with Webpack or Browserify something, I guess.

I checked that this module actually exposes some methods but there is no information about this and I'm quite confusing.

**Comment by compwright** [comment]
Have you tried switching to webpack?

**Comment by rico345100** [comment]
Should I do? I'm not using webpack.

**Comment by compwright** [comment]
Browserify is showing its age. You might want to try switching over.
