### ISSUE TITLE
Zoom does not work

### ISSUE THREAD

**Issue by M5rian** [chartjs/chartjs-plugin-zoom#655]
Hello!

I hope that it's okay to ask questions here too, instead of just bug reports. I couldn't find a solution online.
I wanted to add a zoom feature in my chart. Sadly I can't figure out why my code is not working. I don't get any errors but using the scroll wheel to zoom does nothing. Here is my chart setup:
```js
		const {Chart, registerables} = await import('chart.js');
		const zoomPlugin = await import('chartjs-plugin-zoom');

		Chart.register(...registerables, zoomPlugin)

		const chart = new Chart(document.querySelector('#guild-chart'), {
			type: 'scatter',
			data: {
				datasets: [{
					data: [],
					label: 'Guilds count',
					parsing: {xAxisKey: 'time', yAxisKey: 'value'},
					borderColor: 'rgba(0, 177, 106, 1)',
					backgroundColor: 'rgba(0, 177, 106, 1)'
				}],
				labels: []
			},
			options: {
				scales: {
					x: {
						ticks: {
							callback: function (value, index, values) {
								return new Date(value).toLocaleDateString();
							}
						}
					}
				},
				datasets: {scatter: {showLine: true}},
				plugins: {
					zoom: {
						zoom: {
							wheel: {enabled: true,},
							pinch: {enabled: true},
							mode: 'xy',
						}
					}
				}
			},
		});
```
My chart gets filled with data by a websocket. So the chart won't stay empty. Here is a preview of it:
![preview](https://user-images.githubusercontent.com/69646823/168292198-efce0459-7da2-491e-9874-6a0db4dfd9ab.png)

What am I doing wrong? I am following the docs how its mentioned here <https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/options.html>

* Chart.js 3.7.1
* chartjs-plugin-zoom 1.2.1

Thanks in advance!

**Comment by joshkel** [comment]
Can you please put together a codesandbox.io page or similar demonstrating your problem? I just tried using your sample code, and it seems to work (using the touchpad on my MacBook to zoom): https://codesandbox.io/s/amazing-wood-e4fsbp?file=/src/index.js

**Comment by M5rian** [comment]
Oh through your example code I already found my problem! I registered the zoom plugin like this
```js
Chart.register(...registerables, Zoom)
```
After setting it to
```js
Chart.register(...registerables, Zoom.default)
```
it works fine.

Thank you, was a bit of an embarrassing issue..

**Comment by M5rian** [comment]
Also the documentation doesn't make clear that you have to do that, see
```js
import { Chart } from 'chart.js';
import zoomPlugin from 'chartjs-plugin-zoom';

Chart.register(zoomPlugin);
```
https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/integration.html#bundlers-webpack-rollup-etc

**Comment by joshkel** [comment]
This is a quirk of how ES6 modules work. With ES6 modules,

```js
import zoomPlugin from 'chartjs-plugin-zoom';
```

gets interpreted as "take the default export from chartjs-plugin-zoom." However, when using a CommonJS-style `require`, you have to access the default property yourself:

```
const Zoom = require("chartjs-plugin-zoom").default;
```

(Or by accessing `Zoom.default`, as I did in my codesandbox page.)

**Comment by M5rian** [comment]
Oh interesting, didn't know that. Nice to know! Thanks again, I'll keep that in mind for next time (:
