### ISSUE TITLE
zoom only the borders and and axes lines ? 

### ISSUE THREAD

**Issue by ghost** [chartjs/chartjs-plugin-zoom#66]
Hello, can you please tell me how can I achieve zooming and panning only the border (lines) and not the side labels or data values. Those should remain the same size when zooming. Basically I want to zoom and pan only the area inside the red rectangle (see picture link). Is it possible ?
![screenshot_2](https://cloud.githubusercontent.com/assets/8223986/23742240/c65cdfec-04b4-11e7-9b8d-47bd43e4c3b7.png)

**Comment by compwright** [comment]
Your query doesn't make sense. Could you please elaborate?
