### ISSUE TITLE
Moblie drag Tooltip UI Error

### ISSUE THREAD

**Issue by Minseok0917** [chartjs/chartjs-plugin-zoom#662]
Moblie Chart Drag Tooltip UI Error
**Is there a way to solve this?**
![KakaoTalk_20220614_165404567](https://user-images.githubusercontent.com/37059223/173524214-a9d5fc35-7fec-4e1c-9eaf-bdcc82e5b7ef.jpg)

**Comment by LeeLenaleee** [comment]
From what you describe it does not sound like a zoom issue, but even if it is, please include a codepen with a reproducable samle.
Because in its current state it is near impossible to help you.

**Comment by Minseok0917** [comment]
T-T .... 
https://codepen.io/minseok0917/pen/YzeBrjY 

It wasn't supposed to be NPM
It works again with CDN.
