### ISSUE TITLE
chartjs plugin zoom reset function not work in React js

### ISSUE THREAD

**Issue by raselmahmud22** [chartjs/chartjs-plugin-zoom#668]
I want to add a reset button with my Chart component when it will zoom out user can click on the button and then reset the Chart but

I couldn't find any example of how to do that.

Could you please help me with how to do zoom and pen reset?

Here is my code please check it. I got it in the vanilla JavaScript [Link-here](https://stackoverflow.com/questions/44282734/how-to-reset-the-graph-chart-after-zoomin-pan-using-chartjs) example but I need it in react.

thanks in advance
import { Bar, Line } from "react-chartjs-2";
import { LineData } from "./LineData";
import { Chart, Legend, Title, Tooltip} from "chart.js";
import zoomPlugin from 'chartjs-plugin-zoom';
import { resetZoom } from "chartjs-plugin-zoom";
Chart.register(zoomPlugin);

Chart.register(
  Title,
  Tooltip,
  Legend
);
export function MultiType() {

  const data = LineData();//datasets exports from another component
  const scales = {
    x: {
      type: 'category',
      min: 50,
      max: 100,
    },
    y: {
      type: 'linear'
    },
  };
 const options = {
    scales: scales,
    plugins: {
      zoom: {
        animation: {
          duration: 1000,
          easing: 'easeOutCubic'
        },
        pan: {
          enabled: true,
          mode: 'xy',
          threshold: 155,
        },
        zoom: {
          wheel: {
            enabled: true
          },
          pinch: {
            enabled: true
          },
          mode: 'xy',
        },
      }
    },
  }

  const handleReset = () => {
    resetZoom(Chart.register(
      Title,
      Tooltip,
      Legend
    ),'reset')
  }

  return (
    <>
      <div className="w-10/12 mx-auto">
        <Bar data={data} options={options} />

        <button onClick={handleReset}>Reset</button>
      </div>
    </>
  );
}

<img width="490" alt="image" src="https://user-images.githubusercontent.com/61463085/184448081-bfe985c5-1c02-4e9d-8c92-79b75cddd14e.png">

**Comment by stockiNail** [comment]
Maybe you can have a look to this sample: [codesandbox.io/s/zealous-currying-0zgyzq?file=/App.tsx](https://codesandbox.io/s/zealous-currying-0zgyzq?file=/App.tsx)

**Comment by raselmahmud22** [comment]
thank you
