### ISSUE TITLE
Zoom out/pan scale animation?

### ISSUE THREAD

**Issue by gazpachoking** [chartjs/chartjs-plugin-zoom#678]
I'm doing something similar to the dynamic data fetching [example](https://www.chartjs.org/chartjs-plugin-zoom/latest/samples/fetch-data.html). The animation when zooming in is very nice. I'm wondering if there is a way to have something similar when zooming out or panning? When zooming out or panning, new data is loaded, which might change the min/max on the y axis. I'd just like to add a transition time for the y axis scaling, so that it doesn't look like the existing line jumps when the new data loads. Is there some way to achieve this?

**Comment by kurkle** [comment]
This issue should be resolved in the main repo

**Comment by kurkle** [comment]
https://github.com/chartjs/Chart.js/issues/10894
