### ISSUE TITLE
more explanation on Advance usage

### ISSUE THREAD

**Issue by alexdoso** [chartjs/chartjs-plugin-zoom#68]
Could you please do some more explanation about the Advanced usage > Prototype Methods like resize(). It's hard for a novice to understand all these topics.
Perhaps a small tutorial (video preferably). 
Thanks!

**Comment by alexdoso** [comment]
I have tested this example of yours: https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom-time.html

I zoom up the chart in the chrome browser but the reset zoom button does nothing :(

**Comment by compwright** [comment]
It's working here: https://codepen.io/compwright/pen/PmxJbm
