### ISSUE TITLE
I can't disable zoom by pinch while `wheel` zoom is enabled

### ISSUE THREAD

**Issue by Waseem-Isaac** [chartjs/chartjs-plugin-zoom#685]
I want to disable zoom by pinch.
When I set `options.zoom.pinch.enabled` by `false`. while setting `options.zoom.wheel.enabled: true`, I still can zoom by pinch.

For reproduce the case you can try the samples at [https://www.chartjs.org/chartjs-plugin-zoom/latest/samples/basic.html]()

Is there something I missed?

**Comment by kurkle** [comment]
What device are you using?

**Comment by kurkle** [comment]
closing as stale
