### ISSUE TITLE
Initial Zoomed View & Limits

### ISSUE THREAD

**Issue by cubicool** [chartjs/chartjs-plugin-zoom#686]
I've uploaded a self-contained demo here: https://output.jsbin.com/zetewapufu/1

Essentially, my question is this: In the included dataset, I've manually set the "limits" to sensible values. However, on the "initial" page load, these limits don't appear to be used. For example, if you perform a single tick of zoom--in either direction--the limits seem to subsequently apply, and the scatter data quickly translates itself to look like what I'm going for. I've also added a small callback, bound to the spacebar, that will call `resetZoom`; unfortunately, this seems to put the chart back into the "initial" state, where another single zoom action is required to get the limits to constrain the points based on the bounds specified in the options. My instinct is that this isn't actually a bug, but rather a misunderstanding on my part, or perhaps my own misuse of the library.

If anyone has any advice on how I can get the default state of the chart (the "initial" state and the state that results from the call to `resetZoom`) to apply the limits without requiring any immediate feedback/input from the user, I would greatly appreciate it. I **did** some due diligence in researching this before asking here, but wasn't able to find anything that helped (although I'm perfectly willing to admit that perhaps my search-fu isn't very strong).

Thanks!

P. S. ChartJS and its Zoom/Pan plugin LITERALLY saved me tons of time and effort! I sincerely appreciate the work this community does...

**Comment by kurkle** [comment]
I'm not quite sure what you'd like to limit in the initial state, but you can set min/max in the scales.

The scales get their initial range from the data, rounding to something sensible. This can be tuned in very many ways. For example: `bounds: 'data'` will disable the rounding and just use min/max values from data.

For available configuration options, see: https://www.chartjs.org/docs/latest/axes/cartesian/#common-configuration

**Comment by cubicool** [comment]
To clarify, the state I'm wanting to achieve "happens" after a single zoom event (in either direction).

Thank you for the response; I'll take a look and see what I've buggered up. :)

**Comment by cubicool** [comment]
@kurkle So, as you might have guessed, I was able to easily solve this problem with the documentation you linked. :) Thank you very much!
