### ISSUE TITLE
Weird zoom and pan behavior if labels are numbers 

### ISSUE THREAD

**Issue by toonevdb** [chartjs/chartjs-plugin-zoom#689]
Hi,

Minor bug probably. If the labels are numbers the chart zooms and pans in a weird way. If I use strings for the labels it doesn't occur.
See: https://codepen.io/toonevdb/pen/MWXwRKj

According to the docs (https://www.chartjs.org/docs/latest/general/data-structures.html) numbers should be supported too.

**Comment by icefee** [comment]
I face the same problem. I fixed it by setting scales.x.type =  'linear'

**Comment by kurkle** [comment]
Category scale requires the labels to be strings:
https://www.chartjs.org/docs/latest/axes/cartesian/category.html#category-axis-specific-options
