### ISSUE TITLE
Artifacts while paning or zooming chart

### ISSUE THREAD

**Issue by Swieshy** [chartjs/chartjs-plugin-zoom#69]
Hi, I have an issue with paning and zooming chart.
http://oi67.tinypic.com/jb2ys4.jpg

Regards.

**Comment by compwright** [comment]
Thanks for the screenshot, but to address your issue we will need a jsfiddle or codepen that reproduces your issue. Can you post a link?

**Comment by Swieshy** [comment]
Thanks for reply.
I noticed the problem appears when I have about 400 and more points on my chart.

https://jsfiddle.net/w528aph0/4/
I don't know why zoom and pan does not work on jsfiddle.

**Comment by etimberg** [comment]
@Swieshy the pan and zoom don't work because the zoom plugin was included from a source that does not serve the script with the correct MIME type. Updated fiddle that reproduces the issue: https://jsfiddle.net/q9k0vscp/1/

**Comment by Swieshy** [comment]
Thank you. Problem occurs only in Google Chrome. In Firefox and Microsoft Edge work fine, but much slower than in Google Chrome.

**Comment by jledentu** [comment]
The fiddle still have the bug in Google Chrome 78. But the bug doesn't appear anymore in new versions of Chart.js and chartjs-plugin-zoom: https://jsfiddle.net/L59x4j7p/

So I think we can now close this issue.
