### ISSUE TITLE
Zoom edge cases

### ISSUE THREAD

**Issue by AsturaPhoenix** [chartjs/chartjs-plugin-zoom#690]
I ran into a couple edge cases zooming with dynamic data and limits:

* [unexpected `isZoomedOrPanned()` true after `resetZoom` if data changed while zoomed](https://codepen.io/AsturaPhoenix/pen/JjZKoNR)
* [jitter on zoom-in with fully constrained limits (like a "locked" axis)](https://codepen.io/AsturaPhoenix/pen/GRGqRRp)
* [zoom out against a limit vanishes to a no-op as the focal point approaches the other side of the chart](https://codepen.io/AsturaPhoenix/pen/wvXWBvj)

The first issue seems related to, and can be fixed by fixing, `getInitialScaleBounds()` not updating the scale limits (relying on a previous zoom or pan operation to have done so). An easy fix that covers the `resetZoom` case is to call [`storeOriginalScaleLimits` at the beginning of `getInitialScaleBounds`](https://github.com/chartjs/chartjs-plugin-zoom/compare/master...AsturaPhoenix:chartjs-plugin-zoom:reset-zoom?expand=1#diff-8ab41fe13597e1554b5d6b4c227b5f123ff2d6726a7f3688a8b8d1224fe1d4f3), though this does still return stale bounds until `resetZoom` is actually called; a full fix would be more involved, and it's not clear to me that the functionality is exposed on scales that would make for something correct in all cases (e.g. `"original"` limits as data change while zoomed for scales with unset `min`/`max`, especially if they pad).

The second and third issues can be fixed by simplifying the arithmetic in [`updateRange(...)`](https://github.com/chartjs/chartjs-plugin-zoom/compare/master...AsturaPhoenix:chartjs-plugin-zoom:reset-zoom?expand=1#diff-edc35b4bed6a3769c39dc35cf36ecec6cb7944e12d3314d3d03d7a86392f60cf) to always respect the zoom range, though this does also affect zooming out from category scales in a potentially unintuitive way. Since category zooming tended to round the vanishing case up to 1, preserving the range in the limit case may now zoom out by two categories on the side opposite the limit in the case where the focal point falls between categories, as illustrated in the [changed test spec](https://github.com/chartjs/chartjs-plugin-zoom/compare/master...AsturaPhoenix:chartjs-plugin-zoom:reset-zoom?expand=1#diff-f5c5851e716af87ee8e01f68a408df80a2f777c667f87fd6c0eb19b3c99b97c1). It may be worth evaluating what the actual desired behavior is here.

Another possible issue it might not be my place to bring up is the definition of zoom amount/level. These don't seem to be spelled out in the documentation as far as I can tell, but the behavior doesn't seem as one might intend:

```
chart.getZoomLevel() = 1
chart.zoom(1.99);
chart.getZoomLevel() = 100
chart.zoom(-98);
chart.getZoomLevel() = 1
```

where `chart.zoom(2)` is a zoom to infinity (`min = max`). (https://codepen.io/AsturaPhoenix/pen/zYaBqRp)

**Comment by kurkle** [comment]
Thank you for these findings! Looks like you already have fixes for them too, would you like to open a pull request (or several)?
The category scale zooming two categories could be an issue, but then again I don't think it can be good until we can zoom partial categories. So this could be acceptable.

I did not evaluate the zoom levels at that point, but looks like that could also be improved.
