### ISSUE TITLE
Bug in chartjs-plugin-zoom with chartjs-plugin-datalabels

### ISSUE THREAD

**Issue by BlackyUmbreon** [chartjs/chartjs-plugin-zoom#693]
![Bug](https://user-images.githubusercontent.com/67033857/201278710-fc2f7985-e95d-4be2-9134-b337d7bed271.PNG)
I installed 1 react chartjs plugins called "chartjs-plugin-datalabels" for better bar chart design. However, the problem is when you zoom in the chart, the data labels still **showing outside the graph**, it should be hide. The bug has highlighted in picture shown.

**Comment by kurkle** [comment]
I think you should use `auto` display mode on the labels. Zoom plugin does not know anything about the labels, so this can not be changed here.
