### ISSUE TITLE
Compatible Chart Version

### ISSUE THREAD

**Issue by ghjwa** [chartjs/chartjs-plugin-zoom#698]
Current Version of Chart.js does not work with the plugin.

What version is compatible? Or what changes are needed for it to work in Chart.js (V 4.01)

**Comment by ElenaLj** [comment]
I am facing the same problem but with version 3.8.0

**Comment by ghjwa** [comment]
> I am facing the same problem but with version 3.8.0

It only works with chart.js (V 3.6) and chartjs-plugin-zoom.js ( V 1.21 )

What i don't see in any documentation is, how to dis/enable zoom after initialization.

I'm using 3.6 for the moment. But it would be nice to have all the bugfixes in 4.01 and zooming

**Comment by LeeLenaleee** [comment]
If you update to version `1.3.0` it works with chart.js V4

**Comment by kurkle** [comment]
Will actually be v2.0.0, because we had already merged some breaking change (#658).
