### ISSUE TITLE
Zoom on mixed charts : scales may be unsynchronized

### ISSUE THREAD

**Issue by denis-migdal** [chartjs/chartjs-plugin-zoom#715]
Hi,

When zooming on mixed charts, scales may be unsynchronized. For example, if I have 2 scales :

- x1: scatter data on linear scale ;
- x2: bar data on category scale.

When zooming, x1 will be zoomed smoothly, while x2 will be zoomed step by step (bar will not be show partially, it will either be shown in full or not shown).

Therefore, if I have points at positions (0;2),  (0.5;2), and (1;2) as well as a bar that is supposed to be in the [0;1[ abscissa range, the points should be respectively at the start, middle, and end of the bar (in the x direction). However, when zooming this may not be the case, as the zoom process is different between the 2 type of scales.

I think an option should be added in order to specify the zoom behavior on category scales in order to enable them to be shown partially, therefore enabling to synchronize charts with multiples scales.

Temporary what would you recommend me to do in order to synchronize this 2 scales while zooming (or panning).

Cordially,

**Comment by kurkle** [comment]
I'd use a linear scale instead of the category one. I'm not sure if the issues with category scale can be fixed without breaking changes in chart.js

To use linear scale like category scale, you'd need at least configure the stepSize, to make sure it creates the ticks for chosen interval, and in one of the many ways format the ticks to equal labels.

**Comment by denis-migdal** [comment]
Thanks for your answer.

Doesn't bar datasets require a category scale ?
I tried to replace my category scale with a linear scale with ticks (min: 0, max: 100, stepSize: 1), but no bars are shown.

Another way would be to make the zoom on linear scale behaving like the zoom on the category scale, but I am not sure how to do it. Though it wouldn't work in graphs having different category scales with different "stepSize".

Another hack would be to make my own bars with filled scatter curves, the issue is that it'll fuck up the bars tooltips/highlight.

**Comment by kurkle** [comment]
You can use {x,y} data for bars (too).

**Comment by kurkle** [comment]
Also, you can use {x,y} data for lines on category scale, where the x is relative to the category index. There one can use fractions.

**Comment by denis-migdal** [comment]
> You can use {x,y} data for bars (too).

I am not sure what you mean by that.

> Also, you can use {x,y} data for lines on category scale, where the x is relative to the category index. There one can use fractions.

You mean I can put scatter datasets on a category scale ?
Ticks would be a pain in the ass to format, but that could be a solution.

**Comment by kurkle** [comment]
Yes, you can: https://codepen.io/kurkle/pen/xxJKOzG

**Comment by denis-migdal** [comment]
Thanks for your answer.

It seems that "parsing: false" solves lot of issues. Strange that such important behavior isn't better documented/recommended (I though that is was just an optimization option).

I will try to use a linear scale.

I'd try to see during this week-end if I can reduce the width of the bars (stepSize ?) without fucking up the highlight/tooltips (e.g. bars for [0;0.5[ and [0.5;1[ x axis ranges). I will also try to see if this enables to partially show the bars when zooming (as the scale would now be linear).

One strange thing, is that even with an explicit linear scale + scatter graph, ticks labels position is still changed when a bar dataset is added. I guess I'd have to explicitly set some options.

I will try to post a full example here if other people have the same issue in the futur.
