### ISSUE TITLE
Pan functionality in basic sample does not work in Chrome (107,108)

### ISSUE THREAD

**Issue by kk49** [chartjs/chartjs-plugin-zoom#716]
The pan functionality in the basic sample https://www.chartjs.org/chartjs-plugin-zoom/samples/basic.html does not work in Chrome (v107, v108) it does work in Firefox. (this is under Ubuntu 20.04 amd64 running in VirtualBox under Windows 10)

It also doesn't work in my code which uses
* "chart.js": "^4.0.1"
* "chartjs-plugin-zoom": "^2.0.0"
* "hammerjs": "^2.0.8"

**Comment by kk49** [comment]
Digging deeper, it's probably related to these. I have virtual box 6.1.34

https://bugs.chromium.org/p/chromium/issues/detail?id=1330162#c7

https://github.com/openlayers/openlayers/issues/12934

**Comment by kurkle** [comment]
closing as not related to this repository directly
