### ISSUE TITLE
 Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by rabinadk1** [chartjs/chartjs-plugin-zoom#717]
I got this during the diagnostics from the Chrome Lighthouse.

> Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr).

**Comment by Sergiobop** [comment]
+1

**Comment by estanglerbm** [comment]
wheelPreconditions() can call preventDefault().

Hammer.js (for touch events) also can call preventDefault().  Don't know if CSS touch-action + touchAction = auto would be a future possibility.

Maybe all this doesn't matter with latest browsers if <a href="https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#using_passive_listeners">they default these events to passive</a>, anyway.

**Comment by kurkle** [comment]
fixed by #856
