### ISSUE TITLE
Navigator Zoom

### ISSUE THREAD

**Issue by droidpills** [chartjs/chartjs-plugin-zoom#719]
Is navigator zoom like https://www.jscharting.com/Javascript_Finance_Pan_Zoom_Chart.htm on roadmap?

**Comment by zfei** [comment]
Interested in this as well.

A range selector box is a fairly standard setup for a timeseries charting library.
It gives users a much better idea where they're looking at, with respect to the entire timeline.

**Comment by kurkle** [comment]
I think this would be best done as a separate plugin or extension or even chart type.
