### ISSUE TITLE
Drag-to-zoom when text labels are used

### ISSUE THREAD

**Issue by frankego** [chartjs/chartjs-plugin-zoom#72]
Trying to use drag: true in graphs that they do not have DateTime type in X axis, don't work. 
In your CodePen example, adding drag: true does not work as it should.

**Comment by compwright** [comment]
Guessing this is an issue with the fact that text labels are used rather than a numeric scale. It works here: https://codepen.io/compwright/pen/PmxJbm

**Comment by etimberg** [comment]
Resolved in 1.0.0-beta.2 https://jsfiddle.net/9evkfxr8/
