### ISSUE TITLE
Invalid value used as weak map key

### ISSUE THREAD

**Issue by nikkorejz** [chartjs/chartjs-plugin-zoom#720]
I have Vue application with vue-chartjs library. Zoom plugin works fine. I added button for reset zoom:
```
onResetZoom() {
  if (this.$refs.Chart) {
    resetZoom(this.$refs.Chart.$data._chart)
  }
},
```
And it works.

Now I install annotation plugin for chartjs. It works, but after:
```
ChartJS.register(
  // ...
  ZoomPlugin,
  AnnotationPlugin, // this line
)
```

..."reset zoom" crashed the app
```
client.js?06a0:103 TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at getState (chartjs-plugin-zoom.esm.js?7375:127:1)
    at resetZoom (chartjs-plugin-zoom.esm.js?7375:429:1)
    at VueComponent.onResetZoom (BScatter.vue?9af9:381:1)
```

**Comment by stockiNail** [comment]
@nikkorejz I have tried to reproduce the issue in a codesandbox: https://codesandbox.io/s/throbbing-sky-s29tt4?file=/src/App.vue
It seems working. Can you provide a sample to reproduce the issue?

**Comment by nikkorejz** [comment]
Sorry, I switched to Vue 3 and a new version of Chart.js, the logic of my component has not changed, but the error has disappeared
