### ISSUE TITLE
Error TS2567 when using this plugin in version 2.0.0

### ISSUE THREAD

**Issue by hemmoleg** [chartjs/chartjs-plugin-zoom#721]
Hi,

when I install this plugin and import it I get two errors:

```
Error: node_modules/chart.js/types/index.esm.d.ts:561:21 - error TS2567: Enum declarations can only merge with namespace or other enum declarations.

561 export declare enum UpdateModeEnum {
                        ~~~~~~~~~~~~~~

  node_modules/chartjs-plugin-zoom/types/index.d.ts:16:14
    16   const enum UpdateModeEnum {
                    ~~~~~~~~~~~~~~
    'UpdateModeEnum' was also declared here.
```
    
and

```
Error: node_modules/chartjs-plugin-zoom/types/index.d.ts:16:14 - error TS2567: Enum declarations can only merge with namespace or other enum declarations.

16   const enum UpdateModeEnum {
                ~~~~~~~~~~~~~~

  node_modules/chart.js/types/index.esm.d.ts:561:21
    561 export declare enum UpdateModeEnum {
                            ~~~~~~~~~~~~~~
    'UpdateModeEnum' was also declared here.
```
    
I am using chartjs 3.8.0.
When using version 1.2.1 of this plugin everything works. However I dont think thats a proper solution.
Has anyone else run into this issue?

**Comment by krisanselmo** [comment]
Hi. I have the same issue with chartjs 3.9.1.
Thx for the temporary solution.

**Comment by danielmcquillen** [comment]
Same issue.

**Comment by CoooWeee** [comment]
any updates?

**Comment by elinake** [comment]
Issue is replicated here: https://stackblitz.com/edit/angular-chart-js-a2tqkw?file=node_modules/chartjs-plugin-zoom/types/index.d.ts

When you click Zoom in Chart.register, you will see that UpdateModeEnum in chartjs-plugin-zoom has red squiggly line with error:
```
Enum declarations can only merge with namespace or other enum declarations.(2567)
index.d.ts(570, 21): 'UpdateModeEnum' was also declared here.
```
This project does build, however, in real projects it is often not even allowed to disable typescript entirely.

**Comment by yKicchan** [comment]
I have the same issue with chart.js 4.2.1 and typescript 4.4.4 too.
