### ISSUE TITLE
TypeScript error since updating chart.js to v4.2.1

### ISSUE THREAD

**Issue by StefanNedelchev** [chartjs/chartjs-plugin-zoom#731]
After updating chart.js from 4.2.0 to 4.2.1 I started getting this TypeScrip error at build:
![image](https://user-images.githubusercontent.com/15238282/219469823-515c8bbc-eb03-4f00-8202-bd8e408cb891.png)

I use v2.0.0 of the zoom plugin. Reverting chart.js back to 4.2.0 solved the problem

**Comment by dt-bib** [comment]
Same issue and revert to 4.2.0 solve the problem

Related to this issue : https://github.com/chartjs/chartjs-plugin-zoom/issues/721
