### ISSUE TITLE
The enum UpdateModeEnum is the same name as Chartjs enum name and the typescript is broken.

### ISSUE THREAD

**Issue by luisrodriguesds** [chartjs/chartjs-plugin-zoom#745]
Whem I installed the chartjs and zoom plugin in this version

![image](https://user-images.githubusercontent.com/42545036/226574680-abb4834f-d077-4619-aec8-539034075cf6.png)

the typescript is broken because of this error:

![image](https://user-images.githubusercontent.com/42545036/226574544-bb203b4f-fa2a-4569-a13c-d16a1e1638bc.png)

So, I needed to change manually the names of this enum at the `node_modules\chartjs-plugin-zoom\types\index.d.ts` file, like this: 
![image](https://user-images.githubusercontent.com/42545036/226574942-436f143e-d637-448d-ac7d-4386ad8802ea.png)

Then, the typescript stopped to complain.

Should I create a PR for this? 

Thank you!

**Comment by kurkle** [comment]
You could create the version bump to 2.0.1 pr instead (I just can't do it myself right now, but can do the release after the bump)

**Comment by shrujalshah28** [comment]
@kurkle https://github.com/chartjs/chartjs-plugin-zoom/pull/746
