### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.Chart.helpers')

### ISSUE THREAD

**Issue by ghost** [chartjs/chartjs-plugin-zoom#749]
I always receive the error message. Any ways to get rid of it?

I'm using: 
`chart-js-plugin-zoom: 1.2.1
chart.js: 3.9.1
...`

**Comment by kurkle** [comment]
This coild have been a bug in mentioned versions. But as there is no stack trace or reproduction, there is nothing that can be done.
