### ISSUE TITLE
Drag immediately after pan keeps panning

### ISSUE THREAD

**Issue by aeqz** [chartjs/chartjs-plugin-zoom#750]
With every zoom configuration combining drag and pan that I tried, if it does not pass a certain amount of time after having performed a pan action and before starting to draw a drag region, pan keeps active during draw even if its modifier key has been released:

![demo](https://user-images.githubusercontent.com/97341740/228833842-922a2799-8e27-405f-a83d-e38f56840289.gif)

It can be experienced in the [basic sample](https://www.chartjs.org/chartjs-plugin-zoom/latest/samples/basic.html) with the following zoom configuration:

```js
const zoomOptions = {
  limits: {
    x: {min: -200, max: 200, minRange: 50},
    y: {min: -200, max: 200, minRange: 50}
  },
  pan: {
    modifierKey: 'shift',
    enabled: true,
    mode: 'xy',
  },
  zoom: {
    wheel: {
      enabled: true,
    },
    pinch: {
      enabled: true
    },
    drag: {
      enabled: true
    },
    mode: 'xy',
    onZoomComplete({chart}) {
      // This update is needed to display up to date zoom level in the title.
      // Without this, previous zoom level is displayed.
      // The reason is: title uses the same beforeUpdate hook, and is evaluated before zoom.
      chart.update('none');
    }
  }
};
```

**Comment by lowzyyy** [comment]
This still exists if you zoom at least once.
