### ISSUE TITLE
Plugin not work for ionic 2&3 app

### ISSUE THREAD

**Issue by qiluo** [chartjs/chartjs-plugin-zoom#76]
I'm building an Ionic 3 app, my env is
1. chart.js 2.5
2. ionic 3 & Angular 4

I've built a line chart, and configure zoom as guide,
```
let options = {
      pan: {
        enabled: true,
        mode: 'xy'
      },
      zoom: {
        enabled: true,
        mode: 'x',
      },
      legend: {
        display: false
      }
......
```

I've tested the app on a real device, however neither pan nor zoom worked. Please take a look, thanks

I also read this closed [issue 42](https://github.com/chartjs/chartjs-plugin-zoom/issues/42), the last one confirmed it doesn't work for ionic app

**Comment by compwright** [comment]
Sorry unless you can provide a test case in an Ionic simulator there's nothing really we can do. It works with Hammer.js in the web browser on mobile devices, I suggest you get in touch with the Ionic dev community for assistance with your project.

**Comment by krushitpatel** [comment]
import 'chartjs-plugin-zoom'; in app.module.ts
