### ISSUE TITLE
do not intercept scroll gestures when both pan and zoom are disabled

### ISSUE THREAD

**Issue by mingyuan-xia** [chartjs/chartjs-plugin-zoom#77]
When both pan and zoom are disabled, HammerJS would still intercept gestures on the chart. Suppose a user is scrolling down the page with some charts. When the mouse encounters any chart, the page becomes non-scrollable.

**Comment by BabOuDev** [comment]
+1, very annoying... will have a look on how to solve this!

**Comment by BabOuDev** [comment]
solved for you, waiting for merge.  =)
https://github.com/chartjs/chartjs-plugin-zoom/pull/80

**Comment by mingyuan-xia** [comment]
short but looks great. Thanks a lot. Waiting for the owner.

**Comment by mingyuan-xia** [comment]
@compwright please release the patch to npmjs, thanks.

**Comment by qxzcode** [comment]
This bug appears to be back in the current version on NPM (0.7.0). I'm having the same problem @mingyuan-xia was having: scrolling doesn't work on charts, even when both `pan` and `zoom` are disabled.

**Comment by benmccann** [comment]
@jledentu I'm guessing this might be related to https://github.com/chartjs/chartjs-plugin-zoom/pull/196. Do you think you'd be able to take a look?
