### ISSUE TITLE
Data disappearing with Scatter plot

### ISSUE THREAD

**Issue by gaitat** [chartjs/chartjs-plugin-zoom#782]
When I zoom into a scatter plot, then at some point the data disappears. 
Don't zoom in too fast, one mouse-wheel step at a time.
If you go to the center of the plot and zoom in, then after 5-6 steps the issue is apparent.

I have recreated the issue with the packages:

  "react-chartjs-2": "5.2.0"
  "chart.js": "4.2.1"
  "chartjs-plugin-zoom": "2.0.1"

A sandbox with the issue can be found at: [https://codesandbox.io/s/withered-microservice-stlwl6](https://codesandbox.io/s/withered-microservice-stlwl6)

Any ideas what might be causing it?

**Comment by kurkle** [comment]
You are passing `normalized: true`, but the data is not sorted.
