### ISSUE TITLE
minRange for Category

### ISSUE THREAD

**Issue by mBreyerBG** [chartjs/chartjs-plugin-zoom#796]
I have a barChart with categories. i am using drag to zoom. How can i define a minimum amount of categories, just like e.g: limits.x.minRange would work? Is this possible?!
Right now i can zoom, so that only one category is visible and fills the whole chart. i want like minimum of 4 categories to be visible

**Comment by jgrayson-apl** [comment]
+1

**Comment by alimertcakar** [comment]
+1

**Comment by fecipo** [comment]
+1
