### ISSUE TITLE
Dataset goes out of Axis

### ISSUE THREAD

**Issue by vivekaccelq** [chartjs/chartjs-plugin-zoom#826]
Hi, on Zoom the dataset goes out of bounds of Axis region

![GetImage (1)](https://github.com/user-attachments/assets/7d6ce328-1347-44ad-a7f1-51ae70420e75)
![GetImage](https://github.com/user-attachments/assets/d56b91ec-fd0d-42cb-8f68-57f6e07f94b2)

**Comment by kurkle** [comment]
Are you using the `clip` option in the charts?
https://www.chartjs.org/docs/latest/charts/line.html#general

**Comment by vivekaccelq** [comment]
Hi, forgot to update here. a combination of clip and zoom mode "xy" on column chart caused the issue. I used to think the bars will be redrawn on the newer x-y dim, but that doesn't seems to be the case here.
