### ISSUE TITLE
Zoom to a specific point

### ISSUE THREAD

**Issue by adeel3612** [chartjs/chartjs-plugin-zoom#83]
I have read the issues but they were old and in all that contributors were saying that we are going to implement this. I want to know is this resolve? I want to zoom to the specific point to the mouse cursor. If this is not possible is there any hack i can use to achieve this ?

Also there is another problem when i enable the zoom only on the x-axis and zoom in after sometime it is not possible to zoom out. zooming out did not work and i dont know what reason is.

Waiting for reply.
Any kind of help would be much appreciated.

**Comment by adeel3612** [comment]
Okay now i have just figured exactly what is the problem but not the solution. In my chart at the x-axis i have dates which were only to show the readability to the viewers which were giving a problem i replaced it with something else and it was zooming out successfully. Can somebody help me in this regard

**Comment by etimberg** [comment]
@adeel3612 do you have a fiddle with your chart in it? If I understand correctly you are using a time axis as the x-axis for the chart. Is that correct?

**Comment by adeel3612** [comment]
@etimberg thank you for your response. I was not using the time axis but there were only dates in a string form in the x-axis. I dig in it and figured out that what is the problem. Actually when you zoom out the dates which are not unique they got stuck. Like i have 10-Mar-2017 three times, in order in axis so when i zoom in 10-Mar-2017 date., and zoom out it stucked there because it did not know which date to be reversed. So i fixed it through a bit of hack. Where the date is duplicate i appended a little unique id string with it. Like dates will be now like this 10-Mar-2017(20nA) 10-Mar-2017(015d) 10-Mar-2017(98H). And everything works perfectly but i hope there should be a support for this error.

**Comment by adeel3612** [comment]
@etimberg @compwright  is anything i can do to make these strings appear as it is and also zoom out to be worked properly?

**Comment by adeel3612** [comment]
For the people looking for this in future here is hack what i did. 
From the backend i have sent dates like this 13-Mar-2017(201509) 13-Mar-2017(32334). Actually i appended an id with the date so zooming out problem resolved.

But the problem was how to show these without these ids on the axes. So i did a hack actually by using a callback function. in call back function it only shows the ticks and it did not have any work on graph itself. Like this 
` callback: function (tick) {
                         return tick.split("(")[0];
                    }`
