### ISSUE TITLE
Mouse pointer interferes with animation

### ISSUE THREAD

**Issue by mhornbech** [chartjs/chartjs-plugin-zoom#84]
When using drag mode for zooming any movement of the mouse pointer across the chart will move the animation to the end step immediately. The issue seems to be in the mouseMoveHandler attached for the dragging:

```
chartInstance.zoom._mouseMoveHandler = function(event){
  if (chartInstance.zoom._dragZoomStart) {
    chartInstance.zoom._dragZoomEnd = event;
    chartInstance.update(0);
  }

  chartInstance.update(0);
};
```
If I remove the update call that is always executed everything seems to work out well.

**Comment by nagix** [comment]
#144 fixed this problem.
