### ISSUE TITLE
scroll bar functionality with the zoom

### ISSUE THREAD

**Issue by adeel3612** [chartjs/chartjs-plugin-zoom#85]
Is it possible to integrate the scroll bar upon the zooming?? usually canvas have a fixed width and point go out of bound when zoom in. So is there any solution that i can scroll thought the canvas and still can view the zoomed in points??

like this https://www.google.com/finance?q=NASDAQ%3AGOOGL&ei=U7dAWaiYOc3Eepq5j5AL

**Comment by anubhavng** [comment]
@adeel3612 Did you able to achieve that?
