### ISSUE TITLE
Pan not working for simple chart or category scale.

### ISSUE THREAD

**Issue by adeel3612** [chartjs/chartjs-plugin-zoom#86]
Hello i am getting a main problem. Most of the charts are simple line charts and did not use logarithmic or linear or time. I am also using simple graph without specifying and i think it is category?.
Problem is pan is not working for this when i use pan it actually zoom the graph. I have search every issue and still not get any help. I know @compwright  and @etimberg  you people are busy and i digging it in the chartjs-zoom-plugin file. but i need your help in how to approach this issue. Did i have to go through whole file? 

for category scale plugin uses this line of code ?

```
function panIndexScale(scale, delta, panOptions) {
            var labels = scale.chart.data.labels;
            var lastLabelIndex = labels.length - 1;
            var offsetAmt = Math.max((scale.ticks.length - ((scale.options.gridLines.offsetGridLines) ? 0 : 1)), 1);
            var panSpeed = panOptions.speed;
            var minIndex = scale.minIndex;
            var step = Math.round(scale.width / (offsetAmt * panSpeed));
            var maxIndex;

            zoomNS.panCumulativeDelta += delta;

            minIndex = zoomNS.panCumulativeDelta > step ? Math.max(0, minIndex - 1) : zoomNS.panCumulativeDelta < -step ? Math.min(lastLabelIndex - offsetAmt + 1, minIndex + 1) : minIndex;
            zoomNS.panCumulativeDelta = minIndex !== scale.minIndex ? 0 : zoomNS.panCumulativeDelta;

            maxIndex = Math.min(lastLabelIndex, minIndex + offsetAmt - 1);

            scale.options.ticks.min = rangeMinLimiter(panOptions, labels[minIndex]);
            scale.options.ticks.max = rangeMaxLimiter(panOptions, labels[maxIndex]);
        }
```

**Comment by byeonghun-lee** [comment]
@adeel3612 Did you add hammerjs? When I use this plugin first, pan and zoom(pinch gesture) are didn't  work. 

I solved it adding hammerjs.

**Comment by adeel3612** [comment]
@byeonghun-lee  this is not an issue with the hammerjs. This is the problem with the category scales. Like simple scales on the x-axis. @compwright  Any update of the category scale panning it will be a great help if you can provide help in this regard.

**Comment by etimberg** [comment]
See https://www.chartjs.org/chartjs-plugin-zoom/samples/bar.html for an example of this working
