### ISSUE TITLE
No x-axis pan or zoom using Chart.js 2.6.0

### ISSUE THREAD

**Issue by meisterlampe** [chartjs/chartjs-plugin-zoom#90]
chartjs-plugin-zoom seems to have some problems in conjunction with Chart.js 2.6.0:
In my case, I cannot pan or zoom on the x-axis.

When I simply run `npm install chart.js@2.5.0` x-axis panning and zooming starts working again immediately. Running `npm install chart.js@2.6.0` breaks x-axis pan&zoom again. So it looks like a problem with the chart.js version.

Are you experiencing the same problems or is this working for you?
Any ideas what I can do to upgrade to the latest version of chartjs-plugin-zoom (it has 2.6.0 as dependency)?
Please help.

In my config I use:

   ```
pan: {
      enabled: true,
      mode: 'xy',
      rangeMin: {
        x: null,
        y: null
      },
      rangeMax: {
        x: null,
        y: null
      }
    },
    zoom: {
      enabled: true,
      mode: 'xy',
    }
```

Enviroment:
- Ionic 3.5.3
- ng2-charts 1.6.0

Edit:
Chart-type: time

**Comment by WeaVaer** [comment]
+1 having exactly the same problem.
Even the chart in the live codepen demo link doesn't work on zooming.
I would like to go to chart.js 2.5.0 but I am worried I will have to change my app code and also might be missing some features by downgrading to chart.js 2.5.0

**Comment by adeel3612** [comment]
i have chartjs 2.6 zoom is working fine on x-axis. But panning of x-axis (simple x-axis which is by default category axis) is not supported. Whether it is 2.5 or any version.

**Comment by WeaVaer** [comment]
My chart is a timeline series (x axis is date-time).
Neither zoom nor pan works for chart.js 2.6.
As soon as I tried @meisterlampe 's idea using chart.js 2.5 without changing any line of my code, both pan and zoom started working.
Weird...

**Comment by adeel3612** [comment]
weird! i have not experienced this in my time axis.

**Comment by meisterlampe** [comment]
I too have a time series with moment.js-datetime-objects on the x-Axis (will add this info to my original post, maybe it's important).

**Comment by adeel3612** [comment]
yeah may be may be you should stick 2.5 chart.

**Comment by meisterlampe** [comment]
`zoom-time.html` in the [samples-folder](https://github.com/chartjs/chartjs-plugin-zoom/tree/master/samples) is a good example:

Running `npm install` after a fresh clone gets you chart.js 2.6.0 and drag-zooming is not working in this sample, when I open it in chromium 59.

Now just change line 7 in `zoom-time.html`:
Change: 
`<script src="../node_modules/chart.js/dist/Chart.js"></script>`
to this:  
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>`

In my case zooming is working again after this little change.. 
I tried to debug and found out that the function zoomTimeScale isn't called at all, when using chart.js 2.6.0. But I have no idea why..
..maybe I'm testing the wrong way. Any ideas much appreciated..

**Comment by Evertvdw** [comment]
Having the same problem here, using timeaxis and zooming works when using chartjs 2.5 but not for 2.6. Nothing else is changed in the code.

**Comment by hilljh82** [comment]
I had the same problem with time x axis. After some investigation, it seems that `firstTick` and `lastTick` is no longer available on the `ChartElement` object. Instead, the pan function for time needs to manually index into the ticks array to get both `firstTick` and `lastTick`. I am working on a patch, and will test if this solves the problems for `2.6.0`.

**Comment by Techn1x** [comment]
How'd you go @hilljh82 ?

**Comment by NujiaLin** [comment]
@hilljh82 very nice tips! for a quick fix, since there are no more firstTick and lastTicks, how about instead to use scale.min and scale.max?
although my tick unit doesn't seem to zoom in (only zoom out)

**Comment by meisterlampe** [comment]
Also hoping for a solution on this. ChartJS is already at 2.7.0 now.
Maybe @hilljh82 can get it to work.

**Comment by jarrodbell** [comment]
Thanks to @hilljh82 for pinpointing the issue, I believe pull request #105 will fix this (worked for me)

**Comment by jarrodbell** [comment]
Also, figured out why the axis ticks were not updating when zooming in - the ticks are being built before the time.options.min and max are taken into account.

Editing the release build of Chart.js "buildTicks" (line ~13844) function to move the following lines:
```javascript
// Enforce limits with user min/max options
min = parse(timeOpts.min, me) || min;
max = parse(timeOpts.max, me) || max;
```
Just after this one:
```javascript
var timeOpts = options.time;
```
Then the ticks update as you would expect.

**Comment by NujiaLin** [comment]
@jarrodbell Thanks!! this will save me a great deal of time 😄

**Comment by meisterlampe** [comment]
@jarrodbell Thanks for your PR! I'm having some problems getting this to work.
Is your fix for the buildTicks for 2.6.0 or 2.7.0?

**Comment by meisterlampe** [comment]
Ah ok.. now I got it to work. Thanks :)

**Comment by demesiooliveira** [comment]
Hi guys, anyone with some link or example integration of chat.js + chartjs-plugin-zoom for Ionic. I tried in every possible way and I can not use chartjs-plugin-zoom.

**Comment by maggask** [comment]
I don't seem to be able to get chartjs-plugin-zoom (v0.5.0) to work with chart.js (v2.7.0), the two lines always end up with invalid date:
`options.time.min = rangeMinLimiter(zoomOptions, scale.getValueForPixel(scale.getPixelForValue(scale.firstTick) + minDelta));
options.time.max = rangeMaxLimiter(zoomOptions, scale.getValueForPixel(scale.getPixelForValue(scale.lastTick) - maxDelta));`

Any ideas about what I'm doing wrong?  Here is my chart options:
`var chartOptions = {
                scales: {
                    xAxes: [{
                        type: 'time',
                        time: {
                            displayFormats: {
                                minute: 'Y-MM-DD LTS',
                                hour: 'Y-MM-DD LTS',
                                day: 'Y-MM-DD',
                                week: 'Y-MM-DD',
                                month: 'MMM Y'
                            },
                            minUnit: 'minute',
                            tooltipFormat: 'Y-MM-DD LTS'
                        },
                        ticks: {
                            callback: function (arg) {
                                var matches = arg.match(/([0-9-]{10})(.*)/);

                                if (matches) {
                                    return [matches[1], matches[2]];
                                }

                                return arg;
                            },
                            minRotation: 0,
                            maxRotation: 0
                        }
                    }],
                    yAxes: []
                },
                animation: {
                    duration: 0
                },
                legend: {
                    position: 'top',
                    labels: {
                        usePointStyle: true
                    }
                },
                maintainAspectRatio: false,
                zoom: {
                    enabled: true,
                    mode: 'x'
                },
                pan: {
                    enabled: true,
                    mode: 'x'
                },
                elements: {
                    line: { tension: 0 }
                }
            };`

I'm inserting moment objects in to the time axes. The chart works fine but breaks if I try to zoom.

**Comment by byeonghun-lee** [comment]
@demesiooliveira  Hi, i think you should consider using [angular-chart library](http://jtblin.github.io/angular-chart.js/).

already using plugin, and except for a few issues... zoom plugin work. If the gesture(may be zoom with pinch gesture) does not work well, you should check hammerjs added plugin list.

**Comment by Techn1x** [comment]
Honestly I am *so* confused as to the state of this addon.

I've managed to get it to work perfectly (both pan & zoom) in my scatter chart in my webapp (using latest Chart.JS 2.7.1 and this plugin @ 0.5.0), so I tried to make a codepen demonstrating this, but only the zoom works in the codepen.

Here's the codepen I made, with exactly the same chart options (but I have mocked the data), zoom works well (scroll the mousewheel) but pan is completely disabled?!
https://codepen.io/anon/pen/GOWRZB

**Comment by benmccann** [comment]
@jarrodbell you said you were editing the release build of Chart.js "buildTicks" (line ~13844). Can you see if that's still necessary in 2.7.1? I'm hoping that https://github.com/chartjs/Chart.js/pull/4860 might fix that

**Comment by mrgreen8** [comment]
My Chart.js and Zoom Plug-Ins are:
Chart.bundle.min.js - Version: 2.7.0
Chart.Zoom.min.js - Version: 0.3.0

I agree.  When I set this:
scales: -> xAxes: -> type: 'time'
It will not zoom in on the X axis (time), but it will zoom in on both Axes if type: 'linear'.

**Comment by mrgreen8** [comment]
My Chart.js and Zoom Plug-Ins are now:
Chart.bundle.min.js - Version: 2.7.1
Chart.Zoom.min.js - Version: 0.5.0

It's doing the same thing when I set this:
scales: -> xAxes: -> type: 'time'
It will not zoom in on the X axis (time), but it will zoom in on both Axes if:
scales: -> xAxes: -> type: 'linear'

**Comment by mrgreen8** [comment]
This works:
Chart.bundle.min.js - Version: 2.5.0
Chart.Zoom.min.js - Version: 0.5.0
scales: -> xAxes: -> type: 'time'

**Comment by benmccann** [comment]
@jarrodbell thanks for the fix! It's been merged now

**Comment by mrgreen8** [comment]
I'm confused.  If it's fixed, where are the updated js files?

**Comment by compwright** [comment]
@mrgreen8 I believe @benmccann is working on releasing another official version that will include the fixes. In the meantime, you can configure NPM/yarn or Bower to pull from the master branch which will include the latest changes.

**Comment by benmccann** [comment]
I pushed updated JS files to GitHub this morning. I just asked @compwright and @etimberg to give me access to push them to npm as well, so hopefully I will be able to complete that final step shortly

Thanks @compwright for showing me how to cut the release!

**Comment by compwright** [comment]
@benmccann you should have access to publish on NPM now.

**Comment by benmccann** [comment]
Thanks @compwright !

New version has been published on npm!

**Comment by adeel3612** [comment]
guys does this solve the issue for the x-axis category scale panning?

**Comment by benmccann** [comment]
This issue was for the time scale

**Comment by kghandi** [comment]
I just tried using x scale "drag" zoom feature on a time scale, and find that the calculations in zoomTimeScale() are off. The resulting range which the zoom goes to do not seem to correspond to the dragged region. I was able to fix this by changing zoomTimeScale() as follows. I suspect this might break pinch-zoom feature and y time scales but have not tried those cases.

Replace following in zoomTimeScale()
```
	var max_percent = 1 - min_percent;
	var newDiff = range * (zoom - 1);

	var minDelta = newDiff * min_percent;
	var maxDelta = newDiff * max_percent;
	var newMin = scale.getValueForPixel(scale.getPixelForValue(scale.min) + minDelta);
	var newMax = scale.getValueForPixel(scale.getPixelForValue(scale.max) - maxDelta);

```
with:
```
	var newDiff = range * (zoom - 1);       // corresponds to chartDistance - dragDistance
	var dragDistance = range - newDiff;
	var startX = center.x - dragDistance / 2;
	var endX = startX + dragDistance;
	var newMin = scale.getValueForPixel(scale.getPixelForValue(scale.min) + startX - scale.left);
	var newMax = scale.getValueForPixel(scale.getPixelForValue(scale.min) + endX - scale.left);

```

**Comment by krushitpatel** [comment]
import 'chartjs-plugin-zoom'; in app.module.ts
