### ISSUE TITLE
resetZoom() does not restore original min/max

### ISSUE THREAD

**Issue by Evertvdw** [chartjs/chartjs-plugin-zoom#95]
Hello,

There is a problem with the resetZoom() function that is added to each chart. When calling this it deletes the min/max values for the scale and this results in scales resetting to defaults. 

I isolated the code here (line 299 in version 0.5.0 of the plugin)
```
chartInstance.resetZoom = function() {
	helpers.each(chartInstance.scales, function(scale, id) {
		var timeOptions = scale.options.time;
		var tickOptions = scale.options.ticks;

		if (timeOptions) {
			scale.options.time.min = scale.originalOptions.time.min //new line
			scale.options.time.max = scale.originalOptions.time.max //new line
			// delete timeOptions.min;
			// delete timeOptions.max;
		}

		if (tickOptions) {
			scale.options.ticks.min = scale.originalOptions.ticks.min //new line
			scale.options.ticks.max = scale.originalOptions.ticks.max //new line
			// delete tickOptions.min;
			// delete tickOptions.max;
		}
		// scale.options = helpers.configMerge(scale.options, scale.originalOptions);
	});	
	helpers.each(chartInstance.data.datasets, function(dataset, id) {
		dataset._meta = null;
	});

	chartInstance.update();
};
```

I commented out the original code and inserted my own statements that do have the desired effect. I'm not quite sure why the original code does not work. The `helpers.configMerge(scale.options, scale.originalOptions)` does return the correct object with the restored min/max values but it does not save them in the actual chartInstance. When I log the chartInstance just before the update the min/max values are missing from the scales. 

Can this be fixed?

**Comment by Fridthjof** [comment]
This is still not fixed in current version.

**Comment by etimberg** [comment]
This is working as of 1.0.0-beta.1. See https://www.chartjs.org/chartjs-plugin-zoom/samples/bar.html where the X axis has initial zoom limits and the reset zoom resets to those
